// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: ingress_route_find_by_fqdn.sql

package db

import (
	"context"
	"database/sql"
)

const findFrontlineRouteByFQDN = `-- name: FindFrontlineRouteByFQDN :one
SELECT
  environment_id,
  deployment_id
FROM frontline_routes
WHERE fully_qualified_domain_name = ?
`

type FindFrontlineRouteByFQDNRow struct {
	EnvironmentID sql.NullString `db:"environment_id"`
	DeploymentID  sql.NullString `db:"deployment_id"`
}

// FindFrontlineRouteByFQDN resolves a hostname to the environment and
// deployment IDs frontline needs to route a request.
// The projection intentionally stays narrow because this lookup is on the
// request path and callers do not need the rest of the route row.
//
//	SELECT
//	  environment_id,
//	  deployment_id
//	FROM frontline_routes
//	WHERE fully_qualified_domain_name = ?
func (q *Queries) FindFrontlineRouteByFQDN(ctx context.Context, fullyQualifiedDomainName string) (FindFrontlineRouteByFQDNRow, error) {
	row := q.db.QueryRowContext(ctx, findFrontlineRouteByFQDN, fullyQualifiedDomainName)
	var i FindFrontlineRouteByFQDNRow
	err := row.Scan(&i.EnvironmentID, &i.DeploymentID)
	return i, err
}
