// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sentinel_find_by_environment_id.sql

package db

import (
	"context"
	"database/sql"
)

const findHealthyRoutableSentinelsByEnvironmentID = `-- name: FindHealthyRoutableSentinelsByEnvironmentID :many
SELECT
  s.k8s_address,
  r.name AS region_name,
  r.platform AS region_platform
FROM sentinels s
LEFT JOIN regions r ON s.region_id = r.id
WHERE s.environment_id = ?
  AND s.health = 'healthy'
`

type FindHealthyRoutableSentinelsByEnvironmentIDRow struct {
	K8sAddress     string         `db:"k8s_address"`
	RegionName     sql.NullString `db:"region_name"`
	RegionPlatform sql.NullString `db:"region_platform"`
}

// FindHealthyRoutableSentinelsByEnvironmentID returns only healthy sentinel
// endpoints plus region identity needed for locality-based routing decisions.
// Health filtering happens in SQL so callers do not load or cache unhealthy
// rows in the request path.
//
// LEFT JOIN is intentional: it preserves sentinel rows when region metadata is
// temporarily missing. Callers can discard rows with NULL region fields while
// still using complete rows from the same environment.
//
// Example: if an environment has three sentinels and one is unhealthy, this
// query returns only the two healthy endpoints with their region name and
// platform data.
//
//	SELECT
//	  s.k8s_address,
//	  r.name AS region_name,
//	  r.platform AS region_platform
//	FROM sentinels s
//	LEFT JOIN regions r ON s.region_id = r.id
//	WHERE s.environment_id = ?
//	  AND s.health = 'healthy'
func (q *Queries) FindHealthyRoutableSentinelsByEnvironmentID(ctx context.Context, environmentID string) ([]FindHealthyRoutableSentinelsByEnvironmentIDRow, error) {
	rows, err := q.db.QueryContext(ctx, findHealthyRoutableSentinelsByEnvironmentID, environmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FindHealthyRoutableSentinelsByEnvironmentIDRow
	for rows.Next() {
		var i FindHealthyRoutableSentinelsByEnvironmentIDRow
		if err := rows.Scan(&i.K8sAddress, &i.RegionName, &i.RegionPlatform); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
