// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: acme_challenge_update_status.sql

package db

import (
	"context"
	"database/sql"
)

const updateAcmeChallengeStatus = `-- name: UpdateAcmeChallengeStatus :exec
UPDATE acme_challenges
SET status = ?, updated_at = ?
WHERE domain_id = ?
`

type UpdateAcmeChallengeStatusParams struct {
	Status    AcmeChallengesStatus `db:"status"`
	UpdatedAt sql.NullInt64        `db:"updated_at"`
	DomainID  string               `db:"domain_id"`
}

// UpdateAcmeChallengeStatus
//
//	UPDATE acme_challenges
//	SET status = ?, updated_at = ?
//	WHERE domain_id = ?
func (q *Queries) UpdateAcmeChallengeStatus(ctx context.Context, db DBTX, arg UpdateAcmeChallengeStatusParams) error {
	_, err := db.ExecContext(ctx, updateAcmeChallengeStatus, arg.Status, arg.UpdatedAt, arg.DomainID)
	return err
}
