// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: acme_user_update_registration_uri.sql

package db

import (
	"context"
	"database/sql"
)

const updateAcmeUserRegistrationURI = `-- name: UpdateAcmeUserRegistrationURI :exec
UPDATE acme_users SET registration_uri = ? WHERE id = ?
`

type UpdateAcmeUserRegistrationURIParams struct {
	RegistrationUri sql.NullString `db:"registration_uri"`
	ID              string         `db:"id"`
}

// UpdateAcmeUserRegistrationURI
//
//	UPDATE acme_users SET registration_uri = ? WHERE id = ?
func (q *Queries) UpdateAcmeUserRegistrationURI(ctx context.Context, db DBTX, arg UpdateAcmeUserRegistrationURIParams) error {
	_, err := db.ExecContext(ctx, updateAcmeUserRegistrationURI, arg.RegistrationUri, arg.ID)
	return err
}
