// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: app_find_by_project_id.sql

package db

import (
	"context"
)

const findAppsByProjectId = `-- name: FindAppsByProjectId :many
SELECT id, slug
FROM apps
WHERE project_id = ?
`

type FindAppsByProjectIdRow struct {
	ID   string `db:"id"`
	Slug string `db:"slug"`
}

// FindAppsByProjectId
//
//	SELECT id, slug
//	FROM apps
//	WHERE project_id = ?
func (q *Queries) FindAppsByProjectId(ctx context.Context, db DBTX, projectID string) ([]FindAppsByProjectIdRow, error) {
	rows, err := db.QueryContext(ctx, findAppsByProjectId, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FindAppsByProjectIdRow
	for rows.Next() {
		var i FindAppsByProjectIdRow
		if err := rows.Scan(&i.ID, &i.Slug); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
