// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: app_build_settings_delete_by_environment.sql

package db

import (
	"context"
)

const deleteAppBuildSettingsByEnvironmentId = `-- name: DeleteAppBuildSettingsByEnvironmentId :exec
DELETE FROM app_build_settings WHERE environment_id = ?
`

// DeleteAppBuildSettingsByEnvironmentId
//
//	DELETE FROM app_build_settings WHERE environment_id = ?
func (q *Queries) DeleteAppBuildSettingsByEnvironmentId(ctx context.Context, db DBTX, environmentID string) error {
	_, err := db.ExecContext(ctx, deleteAppBuildSettingsByEnvironmentId, environmentID)
	return err
}
