// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: app_update_depot_id.sql

package db

import (
	"context"
	"database/sql"
)

const updateAppDepotID = `-- name: UpdateAppDepotID :exec
UPDATE apps
SET depot_project_id = ?,
    updated_at = ?
WHERE id = ?
`

type UpdateAppDepotIDParams struct {
	DepotProjectID sql.NullString `db:"depot_project_id"`
	UpdatedAt      sql.NullInt64  `db:"updated_at"`
	ID             string         `db:"id"`
}

// UpdateAppDepotID
//
//	UPDATE apps
//	SET depot_project_id = ?,
//	    updated_at = ?
//	WHERE id = ?
func (q *Queries) UpdateAppDepotID(ctx context.Context, db DBTX, arg UpdateAppDepotIDParams) error {
	_, err := db.ExecContext(ctx, updateAppDepotID, arg.DepotProjectID, arg.UpdatedAt, arg.ID)
	return err
}
