// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: build_slot_pick_next_waiter.sql

package db

import (
	"context"
)

const pickNextBuildSlotWaiter = `-- name: PickNextBuildSlotWaiter :one
SELECT deployment_id, awakeable_id
FROM build_slot_waiters
WHERE workspace_id = ?
ORDER BY is_production DESC, enqueued_at ASC
LIMIT 1
FOR UPDATE
`

type PickNextBuildSlotWaiterRow struct {
	DeploymentID string `db:"deployment_id"`
	AwakeableID  string `db:"awakeable_id"`
}

// Returns the next waiter for a workspace, production waiters first then
// by enqueue order. Wrap in a tx with FOR UPDATE to serialize promotion
// across concurrent Release calls.
//
//	SELECT deployment_id, awakeable_id
//	FROM build_slot_waiters
//	WHERE workspace_id = ?
//	ORDER BY is_production DESC, enqueued_at ASC
//	LIMIT 1
//	FOR UPDATE
func (q *Queries) PickNextBuildSlotWaiter(ctx context.Context, db DBTX, workspaceID string) (PickNextBuildSlotWaiterRow, error) {
	row := db.QueryRowContext(ctx, pickNextBuildSlotWaiter, workspaceID)
	var i PickNextBuildSlotWaiterRow
	err := row.Scan(&i.DeploymentID, &i.AwakeableID)
	return i, err
}
