// Code generated by sqlc bulk insert plugin. DO NOT EDIT.

package db

import (
	"context"
	"fmt"
	"strings"
)

// bulkInsertPortalConfig is the base query for bulk insert
const bulkInsertPortalConfig = `INSERT INTO portal_configurations ( id, workspace_id, app_id, key_auth_id, enabled, return_url, created_at, updated_at ) VALUES %s`

// InsertPortalConfigs performs bulk insert in a single query
func (q *BulkQueries) InsertPortalConfigs(ctx context.Context, db DBTX, args []InsertPortalConfigParams) error {

	if len(args) == 0 {
		return nil
	}

	// Build the bulk insert query
	valueClauses := make([]string, len(args))
	for i := range args {
		valueClauses[i] = "( ?, ?, ?, ?, ?, ?, ?, ? )"
	}

	bulkQuery := fmt.Sprintf(bulkInsertPortalConfig, strings.Join(valueClauses, ", "))

	// Collect all arguments
	var allArgs []any
	for _, arg := range args {
		allArgs = append(allArgs, arg.ID)
		allArgs = append(allArgs, arg.WorkspaceID)
		allArgs = append(allArgs, arg.AppID)
		allArgs = append(allArgs, arg.KeyAuthID)
		allArgs = append(allArgs, arg.Enabled)
		allArgs = append(allArgs, arg.ReturnUrl)
		allArgs = append(allArgs, arg.CreatedAt)
		allArgs = append(allArgs, arg.UpdatedAt)
	}

	// Execute the bulk insert
	_, err := db.ExecContext(ctx, bulkQuery, allArgs...)
	return err
}
