// Code generated by sqlc bulk insert plugin. DO NOT EDIT.

package db

import (
	"context"
	"fmt"
	"strings"
)

// bulkInsertRolePermission is the base query for bulk insert
const bulkInsertRolePermission = `INSERT INTO roles_permissions ( role_id, permission_id, workspace_id, created_at_m ) VALUES %s`

// InsertRolePermissions performs bulk insert in a single query
func (q *BulkQueries) InsertRolePermissions(ctx context.Context, db DBTX, args []InsertRolePermissionParams) error {

	if len(args) == 0 {
		return nil
	}

	// Build the bulk insert query
	valueClauses := make([]string, len(args))
	for i := range args {
		valueClauses[i] = "( ?, ?, ?, ? )"
	}

	bulkQuery := fmt.Sprintf(bulkInsertRolePermission, strings.Join(valueClauses, ", "))

	// Collect all arguments
	var allArgs []any
	for _, arg := range args {
		allArgs = append(allArgs, arg.RoleID)
		allArgs = append(allArgs, arg.PermissionID)
		allArgs = append(allArgs, arg.WorkspaceID)
		allArgs = append(allArgs, arg.CreatedAtM)
	}

	// Execute the bulk insert
	_, err := db.ExecContext(ctx, bulkQuery, allArgs...)
	return err
}
