// Code generated by sqlc bulk insert plugin. DO NOT EDIT.

package db

import (
	"context"
	"fmt"
	"strings"
)

// bulkInsertAppEnvironmentVariable is the base query for bulk insert
const bulkInsertAppEnvironmentVariable = `INSERT INTO app_environment_variables (id, workspace_id, app_id, environment_id, ` + "`" + `key` + "`" + `, value, created_at) VALUES %s`

// InsertAppEnvironmentVariables performs bulk insert in a single query
func (q *BulkQueries) InsertAppEnvironmentVariables(ctx context.Context, db DBTX, args []InsertAppEnvironmentVariableParams) error {

	if len(args) == 0 {
		return nil
	}

	// Build the bulk insert query
	valueClauses := make([]string, len(args))
	for i := range args {
		valueClauses[i] = "(?, ?, ?, ?, ?, ?, ?)"
	}

	bulkQuery := fmt.Sprintf(bulkInsertAppEnvironmentVariable, strings.Join(valueClauses, ", "))

	// Collect all arguments
	var allArgs []any
	for _, arg := range args {
		allArgs = append(allArgs, arg.ID)
		allArgs = append(allArgs, arg.WorkspaceID)
		allArgs = append(allArgs, arg.AppID)
		allArgs = append(allArgs, arg.EnvironmentID)
		allArgs = append(allArgs, arg.EnvKey)
		allArgs = append(allArgs, arg.Value)
		allArgs = append(allArgs, arg.CreatedAt)
	}

	// Execute the bulk insert
	_, err := db.ExecContext(ctx, bulkQuery, allArgs...)
	return err
}
