// Code generated by sqlc bulk insert plugin. DO NOT EDIT.

package db

import (
	"context"
	"fmt"
	"strings"
)

// bulkInsertLogdrain is the base query for bulk insert
const bulkInsertLogdrain = `INSERT INTO logdrains (id, workspace_id, name, stream, config, committed_offset_inserted_at, lease_id, fencing_token, created_at, updated_at) VALUES %s`

// InsertLogdrains performs bulk insert in a single query
func (q *BulkQueries) InsertLogdrains(ctx context.Context, db DBTX, args []InsertLogdrainParams) error {

	if len(args) == 0 {
		return nil
	}

	// Build the bulk insert query
	valueClauses := make([]string, len(args))
	for i := range args {
		valueClauses[i] = "(?, ?, ?, ?, ?, ?, '', '', ?, ?)"
	}

	bulkQuery := fmt.Sprintf(bulkInsertLogdrain, strings.Join(valueClauses, ", "))

	// Collect all arguments
	var allArgs []any
	for _, arg := range args {
		allArgs = append(allArgs, arg.ID)
		allArgs = append(allArgs, arg.WorkspaceID)
		allArgs = append(allArgs, arg.Name)
		allArgs = append(allArgs, arg.Stream)
		allArgs = append(allArgs, arg.Config)
		allArgs = append(allArgs, arg.CreatedAt)
		allArgs = append(allArgs, arg.CreatedAt)
		allArgs = append(allArgs, arg.UpdatedAt)
	}

	// Execute the bulk insert
	_, err := db.ExecContext(ctx, bulkQuery, allArgs...)
	return err
}
