// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: cilium_network_policy_find_by_id_and_region.sql

package db

import (
	"context"
)

const findCiliumNetworkPolicyByIDAndRegion = `-- name: FindCiliumNetworkPolicyByIDAndRegion :one
SELECT pk, id, workspace_id, project_id, app_id, environment_id, deployment_id, k8s_name, k8s_namespace, region_id, policy, created_at, updated_at
FROM ` + "`" + `cilium_network_policies` + "`" + `
WHERE region_id = ? AND id = ?
LIMIT 1
`

type FindCiliumNetworkPolicyByIDAndRegionParams struct {
	RegionID              string `db:"region_id"`
	CiliumNetworkPolicyID string `db:"cilium_network_policy_id"`
}

// FindCiliumNetworkPolicyByIDAndRegion
//
//	SELECT pk, id, workspace_id, project_id, app_id, environment_id, deployment_id, k8s_name, k8s_namespace, region_id, policy, created_at, updated_at
//	FROM `cilium_network_policies`
//	WHERE region_id = ? AND id = ?
//	LIMIT 1
func (q *Queries) FindCiliumNetworkPolicyByIDAndRegion(ctx context.Context, db DBTX, arg FindCiliumNetworkPolicyByIDAndRegionParams) (CiliumNetworkPolicy, error) {
	row := db.QueryRowContext(ctx, findCiliumNetworkPolicyByIDAndRegion, arg.RegionID, arg.CiliumNetworkPolicyID)
	var i CiliumNetworkPolicy
	err := row.Scan(
		&i.Pk,
		&i.ID,
		&i.WorkspaceID,
		&i.ProjectID,
		&i.AppID,
		&i.EnvironmentID,
		&i.DeploymentID,
		&i.K8sName,
		&i.K8sNamespace,
		&i.RegionID,
		&i.Policy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
