// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: clickhouse_outbox_find_batch.sql

package db

import (
	"context"
	"strings"
)

const findClickhouseOutboxBatch = `-- name: FindClickhouseOutboxBatch :many
SELECT pk, version, workspace_id, event_id, payload, created_at
FROM clickhouse_outbox
WHERE version IN (/*SLICE:versions*/?)
ORDER BY pk
LIMIT ?
FOR UPDATE SKIP LOCKED
`

type FindClickhouseOutboxBatchParams struct {
	Versions []string `db:"versions"`
	Limit    int32    `db:"limit"`
}

// FindClickhouseOutboxBatch returns the next batch of outbox rows for a
// known set of payload versions. Must be called inside a transaction.
// FOR UPDATE SKIP LOCKED locks the batch so a second cron tick (if Restate
// VO serialization ever fails) silently skips them rather than re-
// processing the same set. The lock is released when the caller commits
// or rolls back. Ordered by pk so retries see a deterministic row set,
// which lets CH's block-level deduplication collapse re-inserts after a
// partial failure.
//
// The version filter means a drainer never reads a payload it can't
// decode. Unknown versions stay in the table until a drainer with the
// matching handler ships.
//
//	SELECT pk, version, workspace_id, event_id, payload, created_at
//	FROM clickhouse_outbox
//	WHERE version IN (/*SLICE:versions*/?)
//	ORDER BY pk
//	LIMIT ?
//	FOR UPDATE SKIP LOCKED
func (q *Queries) FindClickhouseOutboxBatch(ctx context.Context, db DBTX, arg FindClickhouseOutboxBatchParams) ([]ClickhouseOutbox, error) {
	query := findClickhouseOutboxBatch
	var queryParams []interface{}
	if len(arg.Versions) > 0 {
		for _, v := range arg.Versions {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:versions*/?", strings.Repeat(",?", len(arg.Versions))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:versions*/?", "NULL", 1)
	}
	queryParams = append(queryParams, arg.Limit)
	rows, err := db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ClickhouseOutbox
	for rows.Next() {
		var i ClickhouseOutbox
		if err := rows.Scan(
			&i.Pk,
			&i.Version,
			&i.WorkspaceID,
			&i.EventID,
			&i.Payload,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
