// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: custom_domain_find_by_id.sql

package db

import (
	"context"
)

const findCustomDomainById = `-- name: FindCustomDomainById :one
SELECT pk, id, workspace_id, domain, challenge_type, created_at, updated_at
FROM custom_domains
WHERE id = ?
`

// FindCustomDomainById
//
//	SELECT pk, id, workspace_id, domain, challenge_type, created_at, updated_at
//	FROM custom_domains
//	WHERE id = ?
func (q *Queries) FindCustomDomainById(ctx context.Context, db DBTX, id string) (CustomDomain, error) {
	row := db.QueryRowContext(ctx, findCustomDomainById, id)
	var i CustomDomain
	err := row.Scan(
		&i.Pk,
		&i.ID,
		&i.WorkspaceID,
		&i.Domain,
		&i.ChallengeType,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
