// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: custom_domain_insert.sql

package db

import (
	"context"
	"database/sql"
)

const insertCustomDomain = `-- name: InsertCustomDomain :exec
INSERT INTO custom_domains (
    id, workspace_id, project_id, environment_id, domain,
    challenge_type, verification_status, target_cname, invocation_id, created_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertCustomDomainParams struct {
	ID                 string                          `db:"id"`
	WorkspaceID        string                          `db:"workspace_id"`
	ProjectID          string                          `db:"project_id"`
	EnvironmentID      string                          `db:"environment_id"`
	Domain             string                          `db:"domain"`
	ChallengeType      CustomDomainsChallengeType      `db:"challenge_type"`
	VerificationStatus CustomDomainsVerificationStatus `db:"verification_status"`
	TargetCname        string                          `db:"target_cname"`
	InvocationID       sql.NullString                  `db:"invocation_id"`
	CreatedAt          int64                           `db:"created_at"`
}

// InsertCustomDomain
//
//	INSERT INTO custom_domains (
//	    id, workspace_id, project_id, environment_id, domain,
//	    challenge_type, verification_status, target_cname, invocation_id, created_at
//	) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
func (q *Queries) InsertCustomDomain(ctx context.Context, db DBTX, arg InsertCustomDomainParams) error {
	_, err := db.ExecContext(ctx, insertCustomDomain,
		arg.ID,
		arg.WorkspaceID,
		arg.ProjectID,
		arg.EnvironmentID,
		arg.Domain,
		arg.ChallengeType,
		arg.VerificationStatus,
		arg.TargetCname,
		arg.InvocationID,
		arg.CreatedAt,
	)
	return err
}
