// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: custom_domain_find_with_cert_by_domain.sql

package db

import (
	"context"
	"database/sql"
)

const findCustomDomainWithCertByDomain = `-- name: FindCustomDomainWithCertByDomain :one
SELECT
    cd.pk, cd.id, cd.workspace_id, cd.project_id, cd.environment_id, cd.domain, cd.challenge_type, cd.verification_status, cd.verification_token, cd.ownership_verified, cd.cname_verified, cd.target_cname, cd.last_checked_at, cd.check_attempts, cd.verification_error, cd.invocation_id, cd.created_at, cd.updated_at,
    c.id AS certificate_id
FROM custom_domains cd
LEFT JOIN certificates c ON c.hostname = cd.domain
WHERE cd.domain = ?
`

type FindCustomDomainWithCertByDomainRow struct {
	Pk                 uint64                          `db:"pk"`
	ID                 string                          `db:"id"`
	WorkspaceID        string                          `db:"workspace_id"`
	ProjectID          string                          `db:"project_id"`
	EnvironmentID      string                          `db:"environment_id"`
	Domain             string                          `db:"domain"`
	ChallengeType      CustomDomainsChallengeType      `db:"challenge_type"`
	VerificationStatus CustomDomainsVerificationStatus `db:"verification_status"`
	VerificationToken  string                          `db:"verification_token"`
	OwnershipVerified  bool                            `db:"ownership_verified"`
	CnameVerified      bool                            `db:"cname_verified"`
	TargetCname        string                          `db:"target_cname"`
	LastCheckedAt      sql.NullInt64                   `db:"last_checked_at"`
	CheckAttempts      int32                           `db:"check_attempts"`
	VerificationError  sql.NullString                  `db:"verification_error"`
	InvocationID       sql.NullString                  `db:"invocation_id"`
	CreatedAt          int64                           `db:"created_at"`
	UpdatedAt          sql.NullInt64                   `db:"updated_at"`
	CertificateID      sql.NullString                  `db:"certificate_id"`
}

// FindCustomDomainWithCertByDomain
//
//	SELECT
//	    cd.pk, cd.id, cd.workspace_id, cd.project_id, cd.environment_id, cd.domain, cd.challenge_type, cd.verification_status, cd.verification_token, cd.ownership_verified, cd.cname_verified, cd.target_cname, cd.last_checked_at, cd.check_attempts, cd.verification_error, cd.invocation_id, cd.created_at, cd.updated_at,
//	    c.id AS certificate_id
//	FROM custom_domains cd
//	LEFT JOIN certificates c ON c.hostname = cd.domain
//	WHERE cd.domain = ?
func (q *Queries) FindCustomDomainWithCertByDomain(ctx context.Context, db DBTX, domain string) (FindCustomDomainWithCertByDomainRow, error) {
	row := db.QueryRowContext(ctx, findCustomDomainWithCertByDomain, domain)
	var i FindCustomDomainWithCertByDomainRow
	err := row.Scan(
		&i.Pk,
		&i.ID,
		&i.WorkspaceID,
		&i.ProjectID,
		&i.EnvironmentID,
		&i.Domain,
		&i.ChallengeType,
		&i.VerificationStatus,
		&i.VerificationToken,
		&i.OwnershipVerified,
		&i.CnameVerified,
		&i.TargetCname,
		&i.LastCheckedAt,
		&i.CheckAttempts,
		&i.VerificationError,
		&i.InvocationID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CertificateID,
	)
	return i, err
}
