// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: custom_domain_reset_verification.sql

package db

import (
	"context"
	"database/sql"
)

const resetCustomDomainVerification = `-- name: ResetCustomDomainVerification :exec
UPDATE custom_domains
SET verification_status = ?,
    check_attempts = ?,
    verification_error = NULL,
    last_checked_at = NULL,
    invocation_id = ?,
    updated_at = ?
WHERE domain = ?
`

type ResetCustomDomainVerificationParams struct {
	VerificationStatus CustomDomainsVerificationStatus `db:"verification_status"`
	CheckAttempts      int32                           `db:"check_attempts"`
	InvocationID       sql.NullString                  `db:"invocation_id"`
	UpdatedAt          sql.NullInt64                   `db:"updated_at"`
	Domain             string                          `db:"domain"`
}

// ResetCustomDomainVerification
//
//	UPDATE custom_domains
//	SET verification_status = ?,
//	    check_attempts = ?,
//	    verification_error = NULL,
//	    last_checked_at = NULL,
//	    invocation_id = ?,
//	    updated_at = ?
//	WHERE domain = ?
func (q *Queries) ResetCustomDomainVerification(ctx context.Context, db DBTX, arg ResetCustomDomainVerificationParams) error {
	_, err := db.ExecContext(ctx, resetCustomDomainVerification,
		arg.VerificationStatus,
		arg.CheckAttempts,
		arg.InvocationID,
		arg.UpdatedAt,
		arg.Domain,
	)
	return err
}
