// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: custom_domain_find_with_cert_by_domain.sql

package db

import (
	"context"
	"database/sql"
)

const findCustomDomainWithCertByDomain = `-- name: FindCustomDomainWithCertByDomain :one
SELECT
    cd.pk, cd.id, cd.workspace_id, cd.domain, cd.challenge_type, cd.created_at, cd.updated_at,
    c.id AS certificate_id
FROM custom_domains cd
LEFT JOIN certificates c ON c.hostname = cd.domain
WHERE cd.domain = ?
`

type FindCustomDomainWithCertByDomainRow struct {
	Pk            uint64                     `db:"pk"`
	ID            string                     `db:"id"`
	WorkspaceID   string                     `db:"workspace_id"`
	Domain        string                     `db:"domain"`
	ChallengeType CustomDomainsChallengeType `db:"challenge_type"`
	CreatedAt     int64                      `db:"created_at"`
	UpdatedAt     sql.NullInt64              `db:"updated_at"`
	CertificateID sql.NullString             `db:"certificate_id"`
}

// FindCustomDomainWithCertByDomain
//
//	SELECT
//	    cd.pk, cd.id, cd.workspace_id, cd.domain, cd.challenge_type, cd.created_at, cd.updated_at,
//	    c.id AS certificate_id
//	FROM custom_domains cd
//	LEFT JOIN certificates c ON c.hostname = cd.domain
//	WHERE cd.domain = ?
func (q *Queries) FindCustomDomainWithCertByDomain(ctx context.Context, db DBTX, domain string) (FindCustomDomainWithCertByDomainRow, error) {
	row := db.QueryRowContext(ctx, findCustomDomainWithCertByDomain, domain)
	var i FindCustomDomainWithCertByDomainRow
	err := row.Scan(
		&i.Pk,
		&i.ID,
		&i.WorkspaceID,
		&i.Domain,
		&i.ChallengeType,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CertificateID,
	)
	return i, err
}
