// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: custom_domain_resolve_projects.sql

package db

import (
	"context"
)

const resolveCustomDomainProjects = `-- name: ResolveCustomDomainProjects :many
SELECT p.id
FROM projects p
WHERE p.workspace_id = ?
  AND (p.id = ? OR p.slug = ?)
`

type ResolveCustomDomainProjectsParams struct {
	WorkspaceID string `db:"workspace_id"`
	Project     string `db:"project"`
}

// ResolveCustomDomainProjects resolves the domain-list scope when only a project
// identifier is supplied. It returns every matching project ID in the authorized
// workspace without enumerating apps or environments. Missing projects return no IDs.
// Results are unordered and do not establish permission to read any domain.
//
// For example, project=payments returns proj_1 when proj_1 has slug payments.
// If another project in the same workspace has ID payments, both IDs are returned:
// an ID match does not take precedence over a slug match. The caller loads domains
// by project_id and authorizes each row.
//
//	SELECT p.id
//	FROM projects p
//	WHERE p.workspace_id = ?
//	  AND (p.id = ? OR p.slug = ?)
func (q *Queries) ResolveCustomDomainProjects(ctx context.Context, db DBTX, arg ResolveCustomDomainProjectsParams) ([]string, error) {
	rows, err := db.QueryContext(ctx, resolveCustomDomainProjects, arg.WorkspaceID, arg.Project, arg.Project)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
