// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: deployment_resolve_scope.sql

package db

import (
	"context"
	"database/sql"
)

const resolveDeploymentScope = `-- name: ResolveDeploymentScope :one
SELECT
    p.id AS project_id,
    a.id AS app_id,
    e.id AS environment_id
FROM (
    SELECT p1.id, p1.workspace_id
    FROM projects p1
    WHERE p1.workspace_id = ? AND p1.id = ?
    UNION ALL
    SELECT p2.id, p2.workspace_id
    FROM projects p2
    WHERE p2.workspace_id = ? AND p2.slug = ?
    LIMIT 1
) p
LEFT JOIN apps a
    ON a.project_id = p.id
    AND a.workspace_id = p.workspace_id
    AND (a.id = ? OR a.slug = ?)
LEFT JOIN environments e
    ON e.app_id = a.id
    AND e.workspace_id = a.workspace_id
    AND (e.id = ? OR e.slug = ?)
LIMIT 1
`

type ResolveDeploymentScopeParams struct {
	WorkspaceID string `db:"workspace_id"`
	Project     string `db:"project"`
	App         string `db:"app"`
	Environment string `db:"environment"`
}

type ResolveDeploymentScopeRow struct {
	ProjectID     string         `db:"project_id"`
	AppID         sql.NullString `db:"app_id"`
	EnvironmentID sql.NullString `db:"environment_id"`
}

// Resolves a project (required) + optional app/environment, each an id or slug, to
// their ids in one query. app/environment LEFT JOIN on the parent id, so a value that
// doesn't match yields NULL for that level (caller reads NULL as not-found).
// Project uses UNION ALL of two index seeks instead of `id = ? OR slug = ?`, which
// can't use both indexes and would scan the workspace. app/environment keep the OR
// since the parent-id join already narrows them to a few rows.
//
//	SELECT
//	    p.id AS project_id,
//	    a.id AS app_id,
//	    e.id AS environment_id
//	FROM (
//	    SELECT p1.id, p1.workspace_id
//	    FROM projects p1
//	    WHERE p1.workspace_id = ? AND p1.id = ?
//	    UNION ALL
//	    SELECT p2.id, p2.workspace_id
//	    FROM projects p2
//	    WHERE p2.workspace_id = ? AND p2.slug = ?
//	    LIMIT 1
//	) p
//	LEFT JOIN apps a
//	    ON a.project_id = p.id
//	    AND a.workspace_id = p.workspace_id
//	    AND (a.id = ? OR a.slug = ?)
//	LEFT JOIN environments e
//	    ON e.app_id = a.id
//	    AND e.workspace_id = a.workspace_id
//	    AND (e.id = ? OR e.slug = ?)
//	LIMIT 1
func (q *Queries) ResolveDeploymentScope(ctx context.Context, db DBTX, arg ResolveDeploymentScopeParams) (ResolveDeploymentScopeRow, error) {
	row := db.QueryRowContext(ctx, resolveDeploymentScope,
		arg.WorkspaceID,
		arg.Project,
		arg.WorkspaceID,
		arg.Project,
		arg.App,
		arg.App,
		arg.Environment,
		arg.Environment,
	)
	var i ResolveDeploymentScopeRow
	err := row.Scan(&i.ProjectID, &i.AppID, &i.EnvironmentID)
	return i, err
}
