// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: deployment_topology_delete_by_deployment_region.sql

package db

import (
	"context"
)

const deleteDeploymentTopologyByDeploymentRegion = `-- name: DeleteDeploymentTopologyByDeploymentRegion :exec
DELETE FROM ` + "`" + `deployment_topology` + "`" + `
WHERE deployment_id = ?
  AND region_id = ?
`

type DeleteDeploymentTopologyByDeploymentRegionParams struct {
	DeploymentID string `db:"deployment_id"`
	RegionID     string `db:"region_id"`
}

// DeleteDeploymentTopologyByDeploymentRegion
//
//	DELETE FROM `deployment_topology`
//	WHERE deployment_id = ?
//	  AND region_id = ?
func (q *Queries) DeleteDeploymentTopologyByDeploymentRegion(ctx context.Context, db DBTX, arg DeleteDeploymentTopologyByDeploymentRegionParams) error {
	_, err := db.ExecContext(ctx, deleteDeploymentTopologyByDeploymentRegion, arg.DeploymentID, arg.RegionID)
	return err
}
