// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: deployment_topology_list_all_by_region.sql

package db

import (
	"context"
	"database/sql"
)

const listAllDeploymentTopologiesByRegion = `-- name: ListAllDeploymentTopologiesByRegion :many
SELECT
    dt.pk, dt.workspace_id, dt.deployment_id, dt.region_id, dt.autoscaling_replicas_min, dt.autoscaling_replicas_max, dt.autoscaling_threshold_cpu, dt.autoscaling_threshold_memory, dt.vpa_update_mode, dt.vpa_controlled_resources, dt.vpa_controlled_values, dt.vpa_cpu_min_millicores, dt.vpa_cpu_max_millicores, dt.vpa_memory_min_mib, dt.vpa_memory_max_mib, dt.desired_status, dt.created_at, dt.updated_at,
    d.pk, d.id, d.k8s_name, d.workspace_id, d.project_id, d.environment_id, d.app_id, d.image, d.build_id, d.git_commit_sha, d.git_branch, d.git_commit_message, d.git_commit_author_handle, d.git_commit_author_avatar_url, d.git_commit_timestamp, d.sentinel_config, d.cpu_millicores, d.memory_mib, d.storage_mib, d.desired_state, d.encrypted_environment_variables, d.command, d.port, d.shutdown_signal, d.healthcheck, d.pr_number, d.fork_repository_full_name, d.github_deployment_id, d.status, d.created_at, d.updated_at,
    w.k8s_namespace,
    e.slug AS environment_slug,
    r.name AS region_name,
    grc.repository_full_name AS git_repo,
    ars.replicas AS regional_replicas
FROM ` + "`" + `deployment_topology` + "`" + ` dt
INNER JOIN ` + "`" + `deployments` + "`" + ` d ON dt.deployment_id = d.id
INNER JOIN ` + "`" + `workspaces` + "`" + ` w ON d.workspace_id = w.id
INNER JOIN ` + "`" + `regions` + "`" + ` r ON dt.region_id = r.id
INNER JOIN ` + "`" + `environments` + "`" + ` e ON d.environment_id = e.id
LEFT JOIN ` + "`" + `github_repo_connections` + "`" + ` grc ON d.app_id = grc.app_id
LEFT JOIN ` + "`" + `app_regional_settings` + "`" + ` ars ON ars.app_id = d.app_id AND ars.environment_id = d.environment_id AND ars.region_id = dt.region_id
WHERE r.id = ? AND dt.pk > ?
ORDER BY dt.pk ASC
LIMIT ?
`

type ListAllDeploymentTopologiesByRegionParams struct {
	RegionID string `db:"region_id"`
	AfterPk  uint64 `db:"after_pk"`
	Limit    int32  `db:"limit"`
}

type ListAllDeploymentTopologiesByRegionRow struct {
	DeploymentTopology DeploymentTopology `db:"deployment_topology"`
	Deployment         Deployment         `db:"deployment"`
	K8sNamespace       sql.NullString     `db:"k8s_namespace"`
	EnvironmentSlug    string             `db:"environment_slug"`
	RegionName         string             `db:"region_name"`
	GitRepo            sql.NullString     `db:"git_repo"`
	RegionalReplicas   sql.NullInt32      `db:"regional_replicas"`
}

// ListAllDeploymentTopologiesByRegion returns deployment topologies for a region, paginated by pk.
// Used during full sync (version=0) to bootstrap krane agents with current state.
//
//	SELECT
//	    dt.pk, dt.workspace_id, dt.deployment_id, dt.region_id, dt.autoscaling_replicas_min, dt.autoscaling_replicas_max, dt.autoscaling_threshold_cpu, dt.autoscaling_threshold_memory, dt.vpa_update_mode, dt.vpa_controlled_resources, dt.vpa_controlled_values, dt.vpa_cpu_min_millicores, dt.vpa_cpu_max_millicores, dt.vpa_memory_min_mib, dt.vpa_memory_max_mib, dt.desired_status, dt.created_at, dt.updated_at,
//	    d.pk, d.id, d.k8s_name, d.workspace_id, d.project_id, d.environment_id, d.app_id, d.image, d.build_id, d.git_commit_sha, d.git_branch, d.git_commit_message, d.git_commit_author_handle, d.git_commit_author_avatar_url, d.git_commit_timestamp, d.sentinel_config, d.cpu_millicores, d.memory_mib, d.storage_mib, d.desired_state, d.encrypted_environment_variables, d.command, d.port, d.shutdown_signal, d.healthcheck, d.pr_number, d.fork_repository_full_name, d.github_deployment_id, d.status, d.created_at, d.updated_at,
//	    w.k8s_namespace,
//	    e.slug AS environment_slug,
//	    r.name AS region_name,
//	    grc.repository_full_name AS git_repo,
//	    ars.replicas AS regional_replicas
//	FROM `deployment_topology` dt
//	INNER JOIN `deployments` d ON dt.deployment_id = d.id
//	INNER JOIN `workspaces` w ON d.workspace_id = w.id
//	INNER JOIN `regions` r ON dt.region_id = r.id
//	INNER JOIN `environments` e ON d.environment_id = e.id
//	LEFT JOIN `github_repo_connections` grc ON d.app_id = grc.app_id
//	LEFT JOIN `app_regional_settings` ars ON ars.app_id = d.app_id AND ars.environment_id = d.environment_id AND ars.region_id = dt.region_id
//	WHERE r.id = ? AND dt.pk > ?
//	ORDER BY dt.pk ASC
//	LIMIT ?
func (q *Queries) ListAllDeploymentTopologiesByRegion(ctx context.Context, db DBTX, arg ListAllDeploymentTopologiesByRegionParams) ([]ListAllDeploymentTopologiesByRegionRow, error) {
	rows, err := db.QueryContext(ctx, listAllDeploymentTopologiesByRegion, arg.RegionID, arg.AfterPk, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAllDeploymentTopologiesByRegionRow
	for rows.Next() {
		var i ListAllDeploymentTopologiesByRegionRow
		if err := rows.Scan(
			&i.DeploymentTopology.Pk,
			&i.DeploymentTopology.WorkspaceID,
			&i.DeploymentTopology.DeploymentID,
			&i.DeploymentTopology.RegionID,
			&i.DeploymentTopology.AutoscalingReplicasMin,
			&i.DeploymentTopology.AutoscalingReplicasMax,
			&i.DeploymentTopology.AutoscalingThresholdCpu,
			&i.DeploymentTopology.AutoscalingThresholdMemory,
			&i.DeploymentTopology.VpaUpdateMode,
			&i.DeploymentTopology.VpaControlledResources,
			&i.DeploymentTopology.VpaControlledValues,
			&i.DeploymentTopology.VpaCpuMinMillicores,
			&i.DeploymentTopology.VpaCpuMaxMillicores,
			&i.DeploymentTopology.VpaMemoryMinMib,
			&i.DeploymentTopology.VpaMemoryMaxMib,
			&i.DeploymentTopology.DesiredStatus,
			&i.DeploymentTopology.CreatedAt,
			&i.DeploymentTopology.UpdatedAt,
			&i.Deployment.Pk,
			&i.Deployment.ID,
			&i.Deployment.K8sName,
			&i.Deployment.WorkspaceID,
			&i.Deployment.ProjectID,
			&i.Deployment.EnvironmentID,
			&i.Deployment.AppID,
			&i.Deployment.Image,
			&i.Deployment.BuildID,
			&i.Deployment.GitCommitSha,
			&i.Deployment.GitBranch,
			&i.Deployment.GitCommitMessage,
			&i.Deployment.GitCommitAuthorHandle,
			&i.Deployment.GitCommitAuthorAvatarUrl,
			&i.Deployment.GitCommitTimestamp,
			&i.Deployment.SentinelConfig,
			&i.Deployment.CpuMillicores,
			&i.Deployment.MemoryMib,
			&i.Deployment.StorageMib,
			&i.Deployment.DesiredState,
			&i.Deployment.EncryptedEnvironmentVariables,
			&i.Deployment.Command,
			&i.Deployment.Port,
			&i.Deployment.ShutdownSignal,
			&i.Deployment.Healthcheck,
			&i.Deployment.PrNumber,
			&i.Deployment.ForkRepositoryFullName,
			&i.Deployment.GithubDeploymentID,
			&i.Deployment.Status,
			&i.Deployment.CreatedAt,
			&i.Deployment.UpdatedAt,
			&i.K8sNamespace,
			&i.EnvironmentSlug,
			&i.RegionName,
			&i.GitRepo,
			&i.RegionalReplicas,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
