// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: deployment_env_app_state.sql

package db

import (
	"context"
	"database/sql"
	"strings"
)

const listDeploymentEnvAndAppState = `-- name: ListDeploymentEnvAndAppState :many
SELECT
  d.id AS deployment_id,
  p.slug AS project_slug,
  a.slug AS app_slug,
  e.slug AS environment_slug,
  a.current_deployment_id AS app_current_deployment_id,
  a.is_rolled_back AS app_is_rolled_back
FROM deployments d
JOIN projects p ON p.id = d.project_id
JOIN environments e ON e.id = d.environment_id
JOIN apps a ON a.id = d.app_id
WHERE d.workspace_id = ?
  AND d.id IN (/*SLICE:deployment_ids*/?)
`

type ListDeploymentEnvAndAppStateParams struct {
	WorkspaceID   string   `db:"workspace_id"`
	DeploymentIds []string `db:"deployment_ids"`
}

type ListDeploymentEnvAndAppStateRow struct {
	DeploymentID           string         `db:"deployment_id"`
	ProjectSlug            string         `db:"project_slug"`
	AppSlug                string         `db:"app_slug"`
	EnvironmentSlug        string         `db:"environment_slug"`
	AppCurrentDeploymentID sql.NullString `db:"app_current_deployment_id"`
	AppIsRolledBack        bool           `db:"app_is_rolled_back"`
}

// ListDeploymentEnvAndAppState
//
//	SELECT
//	  d.id AS deployment_id,
//	  p.slug AS project_slug,
//	  a.slug AS app_slug,
//	  e.slug AS environment_slug,
//	  a.current_deployment_id AS app_current_deployment_id,
//	  a.is_rolled_back AS app_is_rolled_back
//	FROM deployments d
//	JOIN projects p ON p.id = d.project_id
//	JOIN environments e ON e.id = d.environment_id
//	JOIN apps a ON a.id = d.app_id
//	WHERE d.workspace_id = ?
//	  AND d.id IN (/*SLICE:deployment_ids*/?)
func (q *Queries) ListDeploymentEnvAndAppState(ctx context.Context, db DBTX, arg ListDeploymentEnvAndAppStateParams) ([]ListDeploymentEnvAndAppStateRow, error) {
	query := listDeploymentEnvAndAppState
	var queryParams []interface{}
	queryParams = append(queryParams, arg.WorkspaceID)
	if len(arg.DeploymentIds) > 0 {
		for _, v := range arg.DeploymentIds {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:deployment_ids*/?", strings.Repeat(",?", len(arg.DeploymentIds))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:deployment_ids*/?", "NULL", 1)
	}
	rows, err := db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDeploymentEnvAndAppStateRow
	for rows.Next() {
		var i ListDeploymentEnvAndAppStateRow
		if err := rows.Scan(
			&i.DeploymentID,
			&i.ProjectSlug,
			&i.AppSlug,
			&i.EnvironmentSlug,
			&i.AppCurrentDeploymentID,
			&i.AppIsRolledBack,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
