// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: environment_build_settings_upsert.sql

package db

import (
	"context"
)

const upsertEnvironmentBuildSettings = `-- name: UpsertEnvironmentBuildSettings :exec
INSERT INTO environment_build_settings (
    id,
    workspace_id,
    environment_id,
    dockerfile,
    docker_context,
    build_cpu_millicores,
    build_memory_mib,
    created_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?)
ON DUPLICATE KEY UPDATE
    dockerfile = VALUES(dockerfile),
    docker_context = VALUES(docker_context),
    build_cpu_millicores = VALUES(build_cpu_millicores),
    build_memory_mib = VALUES(build_memory_mib)
`

type UpsertEnvironmentBuildSettingsParams struct {
	ID                 string `db:"id"`
	WorkspaceID        string `db:"workspace_id"`
	EnvironmentID      string `db:"environment_id"`
	Dockerfile         string `db:"dockerfile"`
	DockerContext      string `db:"docker_context"`
	BuildCpuMillicores int32  `db:"build_cpu_millicores"`
	BuildMemoryMib     int32  `db:"build_memory_mib"`
	CreatedAt          int64  `db:"created_at"`
}

// UpsertEnvironmentBuildSettings
//
//	INSERT INTO environment_build_settings (
//	    id,
//	    workspace_id,
//	    environment_id,
//	    dockerfile,
//	    docker_context,
//	    build_cpu_millicores,
//	    build_memory_mib,
//	    created_at
//	) VALUES (?, ?, ?, ?, ?, ?, ?, ?)
//	ON DUPLICATE KEY UPDATE
//	    dockerfile = VALUES(dockerfile),
//	    docker_context = VALUES(docker_context),
//	    build_cpu_millicores = VALUES(build_cpu_millicores),
//	    build_memory_mib = VALUES(build_memory_mib)
func (q *Queries) UpsertEnvironmentBuildSettings(ctx context.Context, db DBTX, arg UpsertEnvironmentBuildSettingsParams) error {
	_, err := db.ExecContext(ctx, upsertEnvironmentBuildSettings,
		arg.ID,
		arg.WorkspaceID,
		arg.EnvironmentID,
		arg.Dockerfile,
		arg.DockerContext,
		arg.BuildCpuMillicores,
		arg.BuildMemoryMib,
		arg.CreatedAt,
	)
	return err
}
