// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: frontline_route_delete_by_environment.sql

package db

import (
	"context"
)

const deleteFrontlineRoutesByEnvironmentId = `-- name: DeleteFrontlineRoutesByEnvironmentId :exec
DELETE FROM frontline_routes WHERE environment_id = ?
`

// DeleteFrontlineRoutesByEnvironmentId
//
//	DELETE FROM frontline_routes WHERE environment_id = ?
func (q *Queries) DeleteFrontlineRoutesByEnvironmentId(ctx context.Context, db DBTX, environmentID string) error {
	_, err := db.ExecContext(ctx, deleteFrontlineRoutesByEnvironmentId, environmentID)
	return err
}
