// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: github_repo_connection_delete_by_project.sql

package db

import (
	"context"
)

const deleteGithubRepoConnectionsByProjectId = `-- name: DeleteGithubRepoConnectionsByProjectId :exec
DELETE FROM github_repo_connections WHERE project_id = ?
`

// DeleteGithubRepoConnectionsByProjectId
//
//	DELETE FROM github_repo_connections WHERE project_id = ?
func (q *Queries) DeleteGithubRepoConnectionsByProjectId(ctx context.Context, db DBTX, projectID string) error {
	_, err := db.ExecContext(ctx, deleteGithubRepoConnectionsByProjectId, projectID)
	return err
}
