// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: identity_soft_delete.sql

package db

import (
	"context"
)

const softDeleteIdentity = `-- name: SoftDeleteIdentity :exec
UPDATE identities
SET deleted = 1
WHERE id = ?
  AND workspace_id = ?
`

type SoftDeleteIdentityParams struct {
	IdentityID  string `db:"identity_id"`
	WorkspaceID string `db:"workspace_id"`
}

// SoftDeleteIdentity
//
//	UPDATE identities
//	SET deleted = 1
//	WHERE id = ?
//	  AND workspace_id = ?
func (q *Queries) SoftDeleteIdentity(ctx context.Context, db DBTX, arg SoftDeleteIdentityParams) error {
	_, err := db.ExecContext(ctx, softDeleteIdentity, arg.IdentityID, arg.WorkspaceID)
	return err
}
