// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: identity_update_rate_card.sql

package db

import (
	"context"
	"database/sql"
)

const updateIdentityRateCard = `-- name: UpdateIdentityRateCard :exec
UPDATE identities
SET rate_card_id = ?
WHERE workspace_id = ?
  AND id = ?
  AND deleted = false
`

type UpdateIdentityRateCardParams struct {
	RateCardID  sql.NullString `db:"rate_card_id"`
	WorkspaceID string         `db:"workspace_id"`
	IdentityID  string         `db:"identity_id"`
}

// UpdateIdentityRateCard
//
//	UPDATE identities
//	SET rate_card_id = ?
//	WHERE workspace_id = ?
//	  AND id = ?
//	  AND deleted = false
func (q *Queries) UpdateIdentityRateCard(ctx context.Context, db DBTX, arg UpdateIdentityRateCardParams) error {
	_, err := db.ExecContext(ctx, updateIdentityRateCard, arg.RateCardID, arg.WorkspaceID, arg.IdentityID)
	return err
}
