// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: identity_delete_many_by_workspace_id.sql

package db

import (
	"context"
)

const deleteManyIdentitiesByWorkspaceID = `-- name: DeleteManyIdentitiesByWorkspaceID :exec
DELETE FROM identities
WHERE workspace_id = ?
`

// DeleteManyIdentitiesByWorkspaceID hard deletes every identity in a
// workspace. Intended for tests that reset reusable fixtures.
//
//	DELETE FROM identities
//	WHERE workspace_id = ?
func (q *Queries) DeleteManyIdentitiesByWorkspaceID(ctx context.Context, db DBTX, workspaceID string) error {
	_, err := db.ExecContext(ctx, deleteManyIdentitiesByWorkspaceID, workspaceID)
	return err
}
