// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: ingress_route_find_by_id.sql

package db

import (
	"context"
)

const findFrontlineRouteByID = `-- name: FindFrontlineRouteByID :one
SELECT pk, id, project_id, app_id, deployment_id, environment_id, fully_qualified_domain_name, sticky, created_at, updated_at
FROM frontline_routes
WHERE id = ?
`

// FindFrontlineRouteByID
//
//	SELECT pk, id, project_id, app_id, deployment_id, environment_id, fully_qualified_domain_name, sticky, created_at, updated_at
//	FROM frontline_routes
//	WHERE id = ?
func (q *Queries) FindFrontlineRouteByID(ctx context.Context, db DBTX, id string) (FrontlineRoute, error) {
	row := db.QueryRowContext(ctx, findFrontlineRouteByID, id)
	var i FrontlineRoute
	err := row.Scan(
		&i.Pk,
		&i.ID,
		&i.ProjectID,
		&i.AppID,
		&i.DeploymentID,
		&i.EnvironmentID,
		&i.FullyQualifiedDomainName,
		&i.Sticky,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
