// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: ingress_route_find_by_fqdn.sql

package db

import (
	"context"
)

const findFrontlineRouteByFQDN = `-- name: FindFrontlineRouteByFQDN :one
SELECT pk, id, project_id, deployment_id, environment_id, fully_qualified_domain_name, sticky, created_at, updated_at FROM frontline_routes WHERE fully_qualified_domain_name = ?
`

// FindFrontlineRouteByFQDN
//
//	SELECT pk, id, project_id, deployment_id, environment_id, fully_qualified_domain_name, sticky, created_at, updated_at FROM frontline_routes WHERE fully_qualified_domain_name = ?
func (q *Queries) FindFrontlineRouteByFQDN(ctx context.Context, db DBTX, fullyQualifiedDomainName string) (FrontlineRoute, error) {
	row := db.QueryRowContext(ctx, findFrontlineRouteByFQDN, fullyQualifiedDomainName)
	var i FrontlineRoute
	err := row.Scan(
		&i.Pk,
		&i.ID,
		&i.ProjectID,
		&i.DeploymentID,
		&i.EnvironmentID,
		&i.FullyQualifiedDomainName,
		&i.Sticky,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
