// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: key_find_live_by_id.sql

package db

import (
	"context"
	"database/sql"
)

const findLiveKeyByID = `-- name: FindLiveKeyByID :one
SELECT
    k.id AS key_id,
    k.key_auth_id AS key_key_auth_id,
    k.hash AS key_hash,
    k.start AS key_start,
    k.workspace_id AS key_workspace_id,
    k.for_workspace_id AS key_for_workspace_id,
    k.name AS key_name,
    k.identity_id AS key_identity_id,
    k.meta AS key_meta,
    k.expires AS key_expires,
    k.created_at_m AS key_created_at_m,
    k.updated_at_m AS key_updated_at_m,
    k.refill_day AS key_refill_day,
    k.refill_amount AS key_refill_amount,
    k.enabled AS key_enabled,
    k.remaining_requests AS key_remaining_requests,
    k.last_used_at AS key_last_used_at,
    a.id AS api_id,
    a.name AS api_name,
    ka.id AS key_auth_id,
    ka.project_id AS key_auth_project_id,
    ka.store_encrypted_keys AS key_auth_store_encrypted_keys,
    ka.default_prefix AS key_auth_default_prefix,
    ka.default_bytes AS key_auth_default_bytes,
    i.id as identity_table_id,
    i.external_id as identity_external_id,
    i.meta as identity_meta,
    ek.encrypted as encrypted_key,
    ek.encryption_key_id as encryption_key_id,

    -- Roles with both IDs and names
    COALESCE(
        (SELECT JSON_ARRAYAGG(
            JSON_OBJECT(
                'id', r.id,
                'name', r.name,
                'description', r.description
            )
        )
        FROM keys_roles kr
        JOIN roles r ON r.id = kr.role_id
        WHERE k.id = kr.key_id),
        JSON_ARRAY()
    ) as roles,

    -- Direct permissions attached to the key
    COALESCE(
        (SELECT JSON_ARRAYAGG(
            JSON_OBJECT(
                'id', p.id,
                'name', p.name,
                'slug', p.slug,
                'description', p.description
            )
        )
        FROM keys_permissions kp
        JOIN permissions p ON kp.permission_id = p.id
        WHERE k.id = kp.key_id),
        JSON_ARRAY()
    ) as permissions,

    -- Permissions from roles
    COALESCE(
        (SELECT JSON_ARRAYAGG(
            JSON_OBJECT(
                'id', p.id,
                'name', p.name,
                'slug', p.slug,
                'description', p.description
            )
        )
        FROM keys_roles kr
        JOIN roles_permissions rp ON kr.role_id = rp.role_id
        JOIN permissions p ON rp.permission_id = p.id
        WHERE k.id = kr.key_id),
        JSON_ARRAY()
    ) as role_permissions,

    -- Rate limits
    COALESCE(
        (SELECT JSON_ARRAYAGG(
            JSON_OBJECT(
                'id', rl.id,
                'name', rl.name,
                'key_id', rl.key_id,
                'identity_id', rl.identity_id,
                'limit', rl.` + "`" + `limit` + "`" + `,
                'duration', rl.duration,
                'auto_apply', rl.auto_apply = 1
            )
        )
        FROM ratelimits rl
        WHERE k.id = rl.key_id
            OR i.id = rl.identity_id),
        JSON_ARRAY()
    ) as ratelimits

FROM ` + "`" + `keys` + "`" + ` k
JOIN apis a ON a.key_auth_id = k.key_auth_id
JOIN key_auth ka ON ka.id = k.key_auth_id
JOIN workspaces ws ON k.workspace_id = ws.id
LEFT JOIN identities i ON k.identity_id = i.id AND i.deleted = false
LEFT JOIN encrypted_keys ek ON k.id = ek.key_id
WHERE k.id = ?
    AND k.deleted_at_m IS NULL
    AND a.deleted_at_m IS NULL
    AND ka.deleted_at_m IS NULL
    AND ws.deleted_at_m IS NULL
`

type FindLiveKeyByIDRow struct {
	KeyID                     string         `db:"key_id"`
	KeyKeyAuthID              string         `db:"key_key_auth_id"`
	KeyHash                   string         `db:"key_hash"`
	KeyStart                  string         `db:"key_start"`
	KeyWorkspaceID            string         `db:"key_workspace_id"`
	KeyForWorkspaceID         sql.NullString `db:"key_for_workspace_id"`
	KeyName                   sql.NullString `db:"key_name"`
	KeyIdentityID             sql.NullString `db:"key_identity_id"`
	KeyMeta                   sql.NullString `db:"key_meta"`
	KeyExpires                sql.NullTime   `db:"key_expires"`
	KeyCreatedAtM             int64          `db:"key_created_at_m"`
	KeyUpdatedAtM             sql.NullInt64  `db:"key_updated_at_m"`
	KeyRefillDay              sql.NullInt16  `db:"key_refill_day"`
	KeyRefillAmount           sql.NullInt64  `db:"key_refill_amount"`
	KeyEnabled                bool           `db:"key_enabled"`
	KeyRemainingRequests      sql.NullInt64  `db:"key_remaining_requests"`
	KeyLastUsedAt             uint64         `db:"key_last_used_at"`
	ApiID                     string         `db:"api_id"`
	ApiName                   string         `db:"api_name"`
	KeyAuthID                 string         `db:"key_auth_id"`
	KeyAuthProjectID          string         `db:"key_auth_project_id"`
	KeyAuthStoreEncryptedKeys bool           `db:"key_auth_store_encrypted_keys"`
	KeyAuthDefaultPrefix      sql.NullString `db:"key_auth_default_prefix"`
	KeyAuthDefaultBytes       sql.NullInt32  `db:"key_auth_default_bytes"`
	IdentityTableID           sql.NullString `db:"identity_table_id"`
	IdentityExternalID        sql.NullString `db:"identity_external_id"`
	IdentityMeta              []byte         `db:"identity_meta"`
	EncryptedKey              sql.NullString `db:"encrypted_key"`
	EncryptionKeyID           sql.NullString `db:"encryption_key_id"`
	Roles                     interface{}    `db:"roles"`
	Permissions               interface{}    `db:"permissions"`
	RolePermissions           interface{}    `db:"role_permissions"`
	Ratelimits                interface{}    `db:"ratelimits"`
}

// FindLiveKeyByID
//
//	SELECT
//	    k.id AS key_id,
//	    k.key_auth_id AS key_key_auth_id,
//	    k.hash AS key_hash,
//	    k.start AS key_start,
//	    k.workspace_id AS key_workspace_id,
//	    k.for_workspace_id AS key_for_workspace_id,
//	    k.name AS key_name,
//	    k.identity_id AS key_identity_id,
//	    k.meta AS key_meta,
//	    k.expires AS key_expires,
//	    k.created_at_m AS key_created_at_m,
//	    k.updated_at_m AS key_updated_at_m,
//	    k.refill_day AS key_refill_day,
//	    k.refill_amount AS key_refill_amount,
//	    k.enabled AS key_enabled,
//	    k.remaining_requests AS key_remaining_requests,
//	    k.last_used_at AS key_last_used_at,
//	    a.id AS api_id,
//	    a.name AS api_name,
//	    ka.id AS key_auth_id,
//	    ka.project_id AS key_auth_project_id,
//	    ka.store_encrypted_keys AS key_auth_store_encrypted_keys,
//	    ka.default_prefix AS key_auth_default_prefix,
//	    ka.default_bytes AS key_auth_default_bytes,
//	    i.id as identity_table_id,
//	    i.external_id as identity_external_id,
//	    i.meta as identity_meta,
//	    ek.encrypted as encrypted_key,
//	    ek.encryption_key_id as encryption_key_id,
//
//	    -- Roles with both IDs and names
//	    COALESCE(
//	        (SELECT JSON_ARRAYAGG(
//	            JSON_OBJECT(
//	                'id', r.id,
//	                'name', r.name,
//	                'description', r.description
//	            )
//	        )
//	        FROM keys_roles kr
//	        JOIN roles r ON r.id = kr.role_id
//	        WHERE k.id = kr.key_id),
//	        JSON_ARRAY()
//	    ) as roles,
//
//	    -- Direct permissions attached to the key
//	    COALESCE(
//	        (SELECT JSON_ARRAYAGG(
//	            JSON_OBJECT(
//	                'id', p.id,
//	                'name', p.name,
//	                'slug', p.slug,
//	                'description', p.description
//	            )
//	        )
//	        FROM keys_permissions kp
//	        JOIN permissions p ON kp.permission_id = p.id
//	        WHERE k.id = kp.key_id),
//	        JSON_ARRAY()
//	    ) as permissions,
//
//	    -- Permissions from roles
//	    COALESCE(
//	        (SELECT JSON_ARRAYAGG(
//	            JSON_OBJECT(
//	                'id', p.id,
//	                'name', p.name,
//	                'slug', p.slug,
//	                'description', p.description
//	            )
//	        )
//	        FROM keys_roles kr
//	        JOIN roles_permissions rp ON kr.role_id = rp.role_id
//	        JOIN permissions p ON rp.permission_id = p.id
//	        WHERE k.id = kr.key_id),
//	        JSON_ARRAY()
//	    ) as role_permissions,
//
//	    -- Rate limits
//	    COALESCE(
//	        (SELECT JSON_ARRAYAGG(
//	            JSON_OBJECT(
//	                'id', rl.id,
//	                'name', rl.name,
//	                'key_id', rl.key_id,
//	                'identity_id', rl.identity_id,
//	                'limit', rl.`limit`,
//	                'duration', rl.duration,
//	                'auto_apply', rl.auto_apply = 1
//	            )
//	        )
//	        FROM ratelimits rl
//	        WHERE k.id = rl.key_id
//	            OR i.id = rl.identity_id),
//	        JSON_ARRAY()
//	    ) as ratelimits
//
//	FROM `keys` k
//	JOIN apis a ON a.key_auth_id = k.key_auth_id
//	JOIN key_auth ka ON ka.id = k.key_auth_id
//	JOIN workspaces ws ON k.workspace_id = ws.id
//	LEFT JOIN identities i ON k.identity_id = i.id AND i.deleted = false
//	LEFT JOIN encrypted_keys ek ON k.id = ek.key_id
//	WHERE k.id = ?
//	    AND k.deleted_at_m IS NULL
//	    AND a.deleted_at_m IS NULL
//	    AND ka.deleted_at_m IS NULL
//	    AND ws.deleted_at_m IS NULL
func (q *Queries) FindLiveKeyByID(ctx context.Context, db DBTX, id string) (FindLiveKeyByIDRow, error) {
	row := db.QueryRowContext(ctx, findLiveKeyByID, id)
	var i FindLiveKeyByIDRow
	err := row.Scan(
		&i.KeyID,
		&i.KeyKeyAuthID,
		&i.KeyHash,
		&i.KeyStart,
		&i.KeyWorkspaceID,
		&i.KeyForWorkspaceID,
		&i.KeyName,
		&i.KeyIdentityID,
		&i.KeyMeta,
		&i.KeyExpires,
		&i.KeyCreatedAtM,
		&i.KeyUpdatedAtM,
		&i.KeyRefillDay,
		&i.KeyRefillAmount,
		&i.KeyEnabled,
		&i.KeyRemainingRequests,
		&i.KeyLastUsedAt,
		&i.ApiID,
		&i.ApiName,
		&i.KeyAuthID,
		&i.KeyAuthProjectID,
		&i.KeyAuthStoreEncryptedKeys,
		&i.KeyAuthDefaultPrefix,
		&i.KeyAuthDefaultBytes,
		&i.IdentityTableID,
		&i.IdentityExternalID,
		&i.IdentityMeta,
		&i.EncryptedKey,
		&i.EncryptionKeyID,
		&i.Roles,
		&i.Permissions,
		&i.RolePermissions,
		&i.Ratelimits,
	)
	return i, err
}
