// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: key_permission_insert.sql

package db

import (
	"context"
	"database/sql"
)

const insertKeyPermission = `-- name: InsertKeyPermission :exec
INSERT INTO ` + "`" + `keys_permissions` + "`" + ` (
    key_id,
    permission_id,
    workspace_id,
    created_at_m
) VALUES (
    ?,
    ?,
    ?,
    ?
) ON DUPLICATE KEY UPDATE updated_at_m = ?
`

type InsertKeyPermissionParams struct {
	KeyID        string        `db:"key_id"`
	PermissionID string        `db:"permission_id"`
	WorkspaceID  string        `db:"workspace_id"`
	CreatedAt    int64         `db:"created_at"`
	UpdatedAt    sql.NullInt64 `db:"updated_at"`
}

// InsertKeyPermission
//
//	INSERT INTO `keys_permissions` (
//	    key_id,
//	    permission_id,
//	    workspace_id,
//	    created_at_m
//	) VALUES (
//	    ?,
//	    ?,
//	    ?,
//	    ?
//	) ON DUPLICATE KEY UPDATE updated_at_m = ?
func (q *Queries) InsertKeyPermission(ctx context.Context, db DBTX, arg InsertKeyPermissionParams) error {
	_, err := db.ExecContext(ctx, insertKeyPermission,
		arg.KeyID,
		arg.PermissionID,
		arg.WorkspaceID,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}
