// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: portal_session_find_by_exchange_code.sql

package db

import (
	"context"
)

const findPortalSessionByExchangeCodeHash = `-- name: FindPortalSessionByExchangeCodeHash :one
SELECT pk, id, workspace_id, portal_id, external_id, scopes, preview, exchange_code_hash, exchange_code_expires_at, access_token_hash, access_token_created_at, access_token_expires_at, revoked_at, created_at FROM portal_sessions
WHERE exchange_code_hash = ?
`

// Reads back the row a redemption just claimed, to build the response and the
// audit log. Safe to run unconditionally after ExchangePortalSessionCode
// reported one affected row: the hash is UNIQUE, so this is the same row, and
// the caller already established it won the race.
//
//	SELECT pk, id, workspace_id, portal_id, external_id, scopes, preview, exchange_code_hash, exchange_code_expires_at, access_token_hash, access_token_created_at, access_token_expires_at, revoked_at, created_at FROM portal_sessions
//	WHERE exchange_code_hash = ?
func (q *Queries) FindPortalSessionByExchangeCodeHash(ctx context.Context, db DBTX, exchangeCodeHash string) (PortalSession, error) {
	row := db.QueryRowContext(ctx, findPortalSessionByExchangeCodeHash, exchangeCodeHash)
	var i PortalSession
	err := row.Scan(
		&i.Pk,
		&i.ID,
		&i.WorkspaceID,
		&i.PortalID,
		&i.ExternalID,
		&i.Scopes,
		&i.Preview,
		&i.ExchangeCodeHash,
		&i.ExchangeCodeExpiresAt,
		&i.AccessTokenHash,
		&i.AccessTokenCreatedAt,
		&i.AccessTokenExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}
