// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: portal_session_exchange_code.sql

package db

import (
	"context"
	"database/sql"
)

const exchangePortalSessionCode = `-- name: ExchangePortalSessionCode :execresult
UPDATE portal_sessions
SET access_token_hash = ?,
    access_token_created_at = ?,
    access_token_expires_at = ?
WHERE exchange_code_hash = ?
  AND access_token_hash IS NULL
  AND revoked_at IS NULL
  AND exchange_code_expires_at > ?
`

type ExchangePortalSessionCodeParams struct {
	AccessTokenHash      sql.NullString `db:"access_token_hash"`
	AccessTokenCreatedAt sql.NullInt64  `db:"access_token_created_at"`
	AccessTokenExpiresAt sql.NullInt64  `db:"access_token_expires_at"`
	ExchangeCodeHash     string         `db:"exchange_code_hash"`
	Now                  int64          `db:"now"`
}

// Redeems an exchange code for an access token, in place, on the one row that
// owns the code.
//
// Single use is structural rather than a check the caller has to remember: the
// `access_token_hash IS NULL` predicate plus the UNIQUE index on
// `exchange_code_hash` mean concurrent redemptions race on a single row and
// exactly one wins. Callers decide via rowsAffected; zero means the code was
// unknown, already redeemed, or expired.
//
//	UPDATE portal_sessions
//	SET access_token_hash = ?,
//	    access_token_created_at = ?,
//	    access_token_expires_at = ?
//	WHERE exchange_code_hash = ?
//	  AND access_token_hash IS NULL
//	  AND revoked_at IS NULL
//	  AND exchange_code_expires_at > ?
func (q *Queries) ExchangePortalSessionCode(ctx context.Context, db DBTX, arg ExchangePortalSessionCodeParams) (sql.Result, error) {
	return db.ExecContext(ctx, exchangePortalSessionCode,
		arg.AccessTokenHash,
		arg.AccessTokenCreatedAt,
		arg.AccessTokenExpiresAt,
		arg.ExchangeCodeHash,
		arg.Now,
	)
}
