// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: portal_frontline_route_insert.sql

package db

import (
	"context"
	"database/sql"
)

const insertPortalFrontlineRoute = `-- name: InsertPortalFrontlineRoute :exec
INSERT INTO frontline_routes (
    id,
    route_type,
    portal_config_id,
    path_prefix,
    fully_qualified_domain_name,
    sticky,
    created_at,
    updated_at
) VALUES (
    ?,
    'portal',
    ?,
    ?,
    ?,
    'none',
    ?,
    ?
)
`

type InsertPortalFrontlineRouteParams struct {
	ID                       string         `db:"id"`
	PortalConfigID           sql.NullString `db:"portal_config_id"`
	PathPrefix               sql.NullString `db:"path_prefix"`
	FullyQualifiedDomainName string         `db:"fully_qualified_domain_name"`
	CreatedAt                int64          `db:"created_at"`
	UpdatedAt                sql.NullInt64  `db:"updated_at"`
}

// InsertPortalFrontlineRoute
//
//	INSERT INTO frontline_routes (
//	    id,
//	    route_type,
//	    portal_config_id,
//	    path_prefix,
//	    fully_qualified_domain_name,
//	    sticky,
//	    created_at,
//	    updated_at
//	) VALUES (
//	    ?,
//	    'portal',
//	    ?,
//	    ?,
//	    ?,
//	    'none',
//	    ?,
//	    ?
//	)
func (q *Queries) InsertPortalFrontlineRoute(ctx context.Context, db DBTX, arg InsertPortalFrontlineRouteParams) error {
	_, err := db.ExecContext(ctx, insertPortalFrontlineRoute,
		arg.ID,
		arg.PortalConfigID,
		arg.PathPrefix,
		arg.FullyQualifiedDomainName,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}
