// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: portal_find_by_keyspace.sql

package db

import (
	"context"
	"database/sql"
)

const findPortalByKeyspace = `-- name: FindPortalByKeyspace :one
SELECT pk, id, workspace_id, project_id, slug, display_name, app_id, key_auth_id, enabled, logo_url, primary_color, created_at, updated_at FROM portals
WHERE key_auth_id = ?
  AND workspace_id = ?
LIMIT 1
`

type FindPortalByKeyspaceParams struct {
	KeyAuthID   sql.NullString `db:"key_auth_id"`
	WorkspaceID string         `db:"workspace_id"`
}

// Resolves the portal mapped to a keyspace within a workspace. See
// portal_find_by_app.sql for why this is workspace-scoped.
//
//	SELECT pk, id, workspace_id, project_id, slug, display_name, app_id, key_auth_id, enabled, logo_url, primary_color, created_at, updated_at FROM portals
//	WHERE key_auth_id = ?
//	  AND workspace_id = ?
//	LIMIT 1
func (q *Queries) FindPortalByKeyspace(ctx context.Context, db DBTX, arg FindPortalByKeyspaceParams) (Portal, error) {
	row := db.QueryRowContext(ctx, findPortalByKeyspace, arg.KeyAuthID, arg.WorkspaceID)
	var i Portal
	err := row.Scan(
		&i.Pk,
		&i.ID,
		&i.WorkspaceID,
		&i.ProjectID,
		&i.Slug,
		&i.DisplayName,
		&i.AppID,
		&i.KeyAuthID,
		&i.Enabled,
		&i.LogoUrl,
		&i.PrimaryColor,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
