// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: project_delete_by_id.sql

package db

import (
	"context"
)

const deleteProjectById = `-- name: DeleteProjectById :exec
DELETE FROM projects WHERE id = ?
`

// DeleteProjectById
//
//	DELETE FROM projects WHERE id = ?
func (q *Queries) DeleteProjectById(ctx context.Context, db DBTX, id string) error {
	_, err := db.ExecContext(ctx, deleteProjectById, id)
	return err
}
