// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: project_delete_many_by_workspace_id.sql

package db

import (
	"context"
)

const deleteManyProjectsByWorkspaceID = `-- name: DeleteManyProjectsByWorkspaceID :exec
DELETE FROM projects
WHERE workspace_id = ?
`

// DeleteManyProjectsByWorkspaceID hard deletes every project in a workspace.
// Intended for tests that reset reusable fixtures.
//
//	DELETE FROM projects
//	WHERE workspace_id = ?
func (q *Queries) DeleteManyProjectsByWorkspaceID(ctx context.Context, db DBTX, workspaceID string) error {
	_, err := db.ExecContext(ctx, deleteManyProjectsByWorkspaceID, workspaceID)
	return err
}
