// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: ratelimit_override_find_by_identifier.sql

package db

import (
	"context"
)

const findRatelimitOverrideByIdentifier = `-- name: FindRatelimitOverrideByIdentifier :one
SELECT ratelimit_overrides.pk, ratelimit_overrides.id, ratelimit_overrides.workspace_id, ratelimit_overrides.namespace_id, ratelimit_overrides.identifier, ratelimit_overrides.` + "`" + `limit` + "`" + `, ratelimit_overrides.duration, ratelimit_overrides.created_at_m, ratelimit_overrides.updated_at_m, ratelimit_overrides.deleted_at_m FROM ratelimit_overrides
WHERE
    workspace_id = ?
    AND namespace_id = ?
    AND identifier = ?
`

type FindRatelimitOverrideByIdentifierParams struct {
	WorkspaceID string `db:"workspace_id"`
	NamespaceID string `db:"namespace_id"`
	Identifier  string `db:"identifier"`
}

// FindRatelimitOverrideByIdentifier
//
//	SELECT ratelimit_overrides.pk, ratelimit_overrides.id, ratelimit_overrides.workspace_id, ratelimit_overrides.namespace_id, ratelimit_overrides.identifier, ratelimit_overrides.`limit`, ratelimit_overrides.duration, ratelimit_overrides.created_at_m, ratelimit_overrides.updated_at_m, ratelimit_overrides.deleted_at_m FROM ratelimit_overrides
//	WHERE
//	    workspace_id = ?
//	    AND namespace_id = ?
//	    AND identifier = ?
func (q *Queries) FindRatelimitOverrideByIdentifier(ctx context.Context, db DBTX, arg FindRatelimitOverrideByIdentifierParams) (RatelimitOverride, error) {
	row := db.QueryRowContext(ctx, findRatelimitOverrideByIdentifier, arg.WorkspaceID, arg.NamespaceID, arg.Identifier)
	var i RatelimitOverride
	err := row.Scan(
		&i.Pk,
		&i.ID,
		&i.WorkspaceID,
		&i.NamespaceID,
		&i.Identifier,
		&i.Limit,
		&i.Duration,
		&i.CreatedAtM,
		&i.UpdatedAtM,
		&i.DeletedAtM,
	)
	return i, err
}
