// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: ratelimit_namespace_find_by_name.sql

package db

import (
	"context"
)

const findRatelimitNamespaceByName = `-- name: FindRatelimitNamespaceByName :one
SELECT ratelimit_namespaces.pk, ratelimit_namespaces.id, ratelimit_namespaces.workspace_id, ratelimit_namespaces.project_id, ratelimit_namespaces.name, ratelimit_namespaces.created_at_m, ratelimit_namespaces.updated_at_m, ratelimit_namespaces.deleted_at_m FROM ` + "`" + `ratelimit_namespaces` + "`" + `
WHERE name = ?
AND workspace_id = ?
`

type FindRatelimitNamespaceByNameParams struct {
	Name        string `db:"name"`
	WorkspaceID string `db:"workspace_id"`
}

// FindRatelimitNamespaceByName
//
//	SELECT ratelimit_namespaces.pk, ratelimit_namespaces.id, ratelimit_namespaces.workspace_id, ratelimit_namespaces.project_id, ratelimit_namespaces.name, ratelimit_namespaces.created_at_m, ratelimit_namespaces.updated_at_m, ratelimit_namespaces.deleted_at_m FROM `ratelimit_namespaces`
//	WHERE name = ?
//	AND workspace_id = ?
func (q *Queries) FindRatelimitNamespaceByName(ctx context.Context, db DBTX, arg FindRatelimitNamespaceByNameParams) (RatelimitNamespace, error) {
	row := db.QueryRowContext(ctx, findRatelimitNamespaceByName, arg.Name, arg.WorkspaceID)
	var i RatelimitNamespace
	err := row.Scan(
		&i.Pk,
		&i.ID,
		&i.WorkspaceID,
		&i.ProjectID,
		&i.Name,
		&i.CreatedAtM,
		&i.UpdatedAtM,
		&i.DeletedAtM,
	)
	return i, err
}
