// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: resource_names_list_by_ids.sql

package db

import (
	"context"
	"strings"
)

const listResourceNamesByIDs = `-- name: ListResourceNamesByIDs :many
SELECT 'project' AS kind, p.id, p.name, '' AS parent_id
FROM projects p
WHERE p.workspace_id = ?
  AND p.id IN (/*SLICE:project_ids*/?)
UNION ALL
SELECT 'project' AS kind, p.id, p.name, '' AS parent_id
FROM apps a
JOIN projects p ON p.id = a.project_id
WHERE a.workspace_id = ?
  AND a.id IN (/*SLICE:project_of_app_ids*/?)
  AND p.workspace_id = ?
UNION ALL
SELECT 'app' AS kind, a.id, a.name, a.project_id AS parent_id
FROM apps a
WHERE a.workspace_id = ?
  AND a.id IN (/*SLICE:app_ids*/?)
UNION ALL
SELECT 'app' AS kind, a.id, a.name, a.project_id AS parent_id
FROM environments e
JOIN apps a ON a.id = e.app_id
WHERE e.workspace_id = ?
  AND e.id IN (/*SLICE:app_of_environment_ids*/?)
  AND a.workspace_id = ?
UNION ALL
SELECT 'environment' AS kind, e.id, e.slug AS name, e.app_id AS parent_id
FROM environments e
WHERE e.workspace_id = ?
  AND e.id IN (/*SLICE:environment_ids*/?)
`

type ListResourceNamesByIDsParams struct {
	WorkspaceID         string   `db:"workspace_id"`
	ProjectIds          []string `db:"project_ids"`
	ProjectOfAppIds     []string `db:"project_of_app_ids"`
	AppIds              []string `db:"app_ids"`
	AppOfEnvironmentIds []string `db:"app_of_environment_ids"`
	EnvironmentIds      []string `db:"environment_ids"`
}

type ListResourceNamesByIDsRow struct {
	Kind     string `db:"kind"`
	ID       string `db:"id"`
	Name     string `db:"name"`
	ParentID string `db:"parent_id"`
}

// A deleted app or environment does not hide the name of its parent. The query
// also finds an app through its environment and a project through its app. Each
// branch finds its rows through the id_unique index of its table
//
//	SELECT 'project' AS kind, p.id, p.name, '' AS parent_id
//	FROM projects p
//	WHERE p.workspace_id = ?
//	  AND p.id IN (/*SLICE:project_ids*/?)
//	UNION ALL
//	SELECT 'project' AS kind, p.id, p.name, '' AS parent_id
//	FROM apps a
//	JOIN projects p ON p.id = a.project_id
//	WHERE a.workspace_id = ?
//	  AND a.id IN (/*SLICE:project_of_app_ids*/?)
//	  AND p.workspace_id = ?
//	UNION ALL
//	SELECT 'app' AS kind, a.id, a.name, a.project_id AS parent_id
//	FROM apps a
//	WHERE a.workspace_id = ?
//	  AND a.id IN (/*SLICE:app_ids*/?)
//	UNION ALL
//	SELECT 'app' AS kind, a.id, a.name, a.project_id AS parent_id
//	FROM environments e
//	JOIN apps a ON a.id = e.app_id
//	WHERE e.workspace_id = ?
//	  AND e.id IN (/*SLICE:app_of_environment_ids*/?)
//	  AND a.workspace_id = ?
//	UNION ALL
//	SELECT 'environment' AS kind, e.id, e.slug AS name, e.app_id AS parent_id
//	FROM environments e
//	WHERE e.workspace_id = ?
//	  AND e.id IN (/*SLICE:environment_ids*/?)
func (q *Queries) ListResourceNamesByIDs(ctx context.Context, db DBTX, arg ListResourceNamesByIDsParams) ([]ListResourceNamesByIDsRow, error) {
	query := listResourceNamesByIDs
	var queryParams []interface{}
	queryParams = append(queryParams, arg.WorkspaceID)
	if len(arg.ProjectIds) > 0 {
		for _, v := range arg.ProjectIds {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:project_ids*/?", strings.Repeat(",?", len(arg.ProjectIds))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:project_ids*/?", "NULL", 1)
	}
	queryParams = append(queryParams, arg.WorkspaceID)
	if len(arg.ProjectOfAppIds) > 0 {
		for _, v := range arg.ProjectOfAppIds {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:project_of_app_ids*/?", strings.Repeat(",?", len(arg.ProjectOfAppIds))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:project_of_app_ids*/?", "NULL", 1)
	}
	queryParams = append(queryParams, arg.WorkspaceID)
	queryParams = append(queryParams, arg.WorkspaceID)
	if len(arg.AppIds) > 0 {
		for _, v := range arg.AppIds {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:app_ids*/?", strings.Repeat(",?", len(arg.AppIds))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:app_ids*/?", "NULL", 1)
	}
	queryParams = append(queryParams, arg.WorkspaceID)
	if len(arg.AppOfEnvironmentIds) > 0 {
		for _, v := range arg.AppOfEnvironmentIds {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:app_of_environment_ids*/?", strings.Repeat(",?", len(arg.AppOfEnvironmentIds))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:app_of_environment_ids*/?", "NULL", 1)
	}
	queryParams = append(queryParams, arg.WorkspaceID)
	queryParams = append(queryParams, arg.WorkspaceID)
	if len(arg.EnvironmentIds) > 0 {
		for _, v := range arg.EnvironmentIds {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:environment_ids*/?", strings.Repeat(",?", len(arg.EnvironmentIds))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:environment_ids*/?", "NULL", 1)
	}
	rows, err := db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListResourceNamesByIDsRow
	for rows.Next() {
		var i ListResourceNamesByIDsRow
		if err := rows.Scan(
			&i.Kind,
			&i.ID,
			&i.Name,
			&i.ParentID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
