// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: root_keys_list.sql

package db

import (
	"context"
	"database/sql"
)

const listRootKeys = `-- name: ListRootKeys :many
SELECT
    id,
    name,
    prefix,
    start,
    end,
    enabled,
    expires,
    created_at
FROM unkey_root_keys
WHERE unkey_root_keys.for_workspace_id = ?
    AND unkey_root_keys.deleted_at IS NULL
    AND unkey_root_keys.id >= ?
UNION ALL
SELECT
    id,
    name,
    prefix,
    start,
    end,
    enabled,
    expires,
    created_at_m AS created_at
FROM ` + "`" + `keys` + "`" + `
WHERE ` + "`" + `keys` + "`" + `.for_workspace_id = ?
    AND ` + "`" + `keys` + "`" + `.deleted_at_m IS NULL
    AND ` + "`" + `keys` + "`" + `.id >= ?
    AND NOT EXISTS (
        SELECT 1
        FROM unkey_root_keys shadow
        WHERE shadow.id = ` + "`" + `keys` + "`" + `.id
            AND shadow.for_workspace_id = ` + "`" + `keys` + "`" + `.for_workspace_id
            AND shadow.deleted_at IS NULL
    )
ORDER BY id ASC
LIMIT ?
`

type ListRootKeysParams struct {
	ForWorkspaceID sql.NullString `db:"for_workspace_id"`
	IDCursor       string         `db:"id_cursor"`
	Limit          int32          `db:"limit"`
}

type ListRootKeysRow struct {
	ID        string         `db:"id"`
	Name      sql.NullString `db:"name"`
	Prefix    string         `db:"prefix"`
	Start     string         `db:"start"`
	End       string         `db:"end"`
	Enabled   bool           `db:"enabled"`
	Expires   sql.NullTime   `db:"expires"`
	CreatedAt int64          `db:"created_at"`
}

// ListRootKeys merges both root-key stores into one workspace-scoped ID stream.
// The cursor is inclusive: a cursor of key_b returns key_b before key_c.
// Disabled and expired keys remain visible; soft-deleted keys are excluded.
// A new key hides a legacy key with the same ID during migration.
//
//	SELECT
//	    id,
//	    name,
//	    prefix,
//	    start,
//	    end,
//	    enabled,
//	    expires,
//	    created_at
//	FROM unkey_root_keys
//	WHERE unkey_root_keys.for_workspace_id = ?
//	    AND unkey_root_keys.deleted_at IS NULL
//	    AND unkey_root_keys.id >= ?
//	UNION ALL
//	SELECT
//	    id,
//	    name,
//	    prefix,
//	    start,
//	    end,
//	    enabled,
//	    expires,
//	    created_at_m AS created_at
//	FROM `keys`
//	WHERE `keys`.for_workspace_id = ?
//	    AND `keys`.deleted_at_m IS NULL
//	    AND `keys`.id >= ?
//	    AND NOT EXISTS (
//	        SELECT 1
//	        FROM unkey_root_keys shadow
//	        WHERE shadow.id = `keys`.id
//	            AND shadow.for_workspace_id = `keys`.for_workspace_id
//	            AND shadow.deleted_at IS NULL
//	    )
//	ORDER BY id ASC
//	LIMIT ?
func (q *Queries) ListRootKeys(ctx context.Context, db DBTX, arg ListRootKeysParams) ([]ListRootKeysRow, error) {
	rows, err := db.QueryContext(ctx, listRootKeys,
		arg.ForWorkspaceID,
		arg.IDCursor,
		arg.ForWorkspaceID,
		arg.IDCursor,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRootKeysRow
	for rows.Next() {
		var i ListRootKeysRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Prefix,
			&i.Start,
			&i.End,
			&i.Enabled,
			&i.Expires,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
