// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sentinel_flip_deploy_status_if_progressing.sql

package db

import (
	"context"
	"database/sql"
)

const flipSentinelDeployStatusIfProgressing = `-- name: FlipSentinelDeployStatusIfProgressing :execrows
UPDATE sentinels SET
  deploy_status = ?,
  updated_at = ?
WHERE id = ?
  AND deploy_status = 'progressing'
`

type FlipSentinelDeployStatusIfProgressingParams struct {
	DeployStatus SentinelsDeployStatus `db:"deploy_status"`
	UpdatedAt    sql.NullInt64         `db:"updated_at"`
	ID           string                `db:"id"`
}

// FlipSentinelDeployStatusIfProgressing flips deploy_status from progressing
// to the target status, guarding against concurrent writers (e.g. the Deploy
// worker marking failed on timeout) by only updating rows whose current
// status is still 'progressing'. Returns the number of rows affected; the
// caller should treat 0 as "someone else already moved this sentinel out of
// progressing" and skip follow-up side effects (NotifyReady, etc.).
//
//	UPDATE sentinels SET
//	  deploy_status = ?,
//	  updated_at = ?
//	WHERE id = ?
//	  AND deploy_status = 'progressing'
func (q *Queries) FlipSentinelDeployStatusIfProgressing(ctx context.Context, db DBTX, arg FlipSentinelDeployStatusIfProgressingParams) (int64, error) {
	result, err := db.ExecContext(ctx, flipSentinelDeployStatusIfProgressing, arg.DeployStatus, arg.UpdatedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
