// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sentinel_delete_by_project.sql

package db

import (
	"context"
)

const deleteSentinelsByProjectId = `-- name: DeleteSentinelsByProjectId :exec
DELETE FROM sentinels WHERE project_id = ?
`

// DeleteSentinelsByProjectId
//
//	DELETE FROM sentinels WHERE project_id = ?
func (q *Queries) DeleteSentinelsByProjectId(ctx context.Context, db DBTX, projectID string) error {
	_, err := db.ExecContext(ctx, deleteSentinelsByProjectId, projectID)
	return err
}
