// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sentinel_mark_failed_if_progressing.sql

package db

import (
	"context"
	"database/sql"
)

const markSentinelFailedIfProgressing = `-- name: MarkSentinelFailedIfProgressing :exec
UPDATE sentinels
SET deploy_status = 'failed',
    updated_at    = ?
WHERE id = ?
  AND deploy_status = 'progressing'
`

type MarkSentinelFailedIfProgressingParams struct {
	UpdatedAt sql.NullInt64 `db:"updated_at"`
	ID        string        `db:"id"`
}

// Conditional flip to `failed`, only when the sentinel is currently
// `progressing`. Used by Deploy's compensation on abnormal exit so a
// concurrent ReportSentinelStatus that already flipped the sentinel to
// `ready` (the authoritative convergence path) doesn't get overwritten
// with `failed`.
//
//	UPDATE sentinels
//	SET deploy_status = 'failed',
//	    updated_at    = ?
//	WHERE id = ?
//	  AND deploy_status = 'progressing'
func (q *Queries) MarkSentinelFailedIfProgressing(ctx context.Context, db DBTX, arg MarkSentinelFailedIfProgressingParams) error {
	_, err := db.ExecContext(ctx, markSentinelFailedIfProgressing, arg.UpdatedAt, arg.ID)
	return err
}
