// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: unkey_permission_insert.sql

package db

import (
	"context"
	"database/sql"
)

const insertUnkeyPermission = `-- name: InsertUnkeyPermission :exec
INSERT INTO unkey_permissions (
    id, for_workspace_id, principal_type, principal_id, name, slug, description, created_at_m
) VALUES (
    ?, ?, ?, ?,
    ?, ?, ?, ?
)
`

type InsertUnkeyPermissionParams struct {
	ID             string         `db:"id"`
	ForWorkspaceID string         `db:"for_workspace_id"`
	PrincipalType  string         `db:"principal_type"`
	PrincipalID    string         `db:"principal_id"`
	Name           string         `db:"name"`
	Slug           string         `db:"slug"`
	Description    sql.NullString `db:"description"`
	CreatedAtM     int64          `db:"created_at_m"`
}

// InsertUnkeyPermission assigns a permission directly to a principal in the
// workspace it authorizes. Duplicate permissions for that principal are rejected.
//
//	INSERT INTO unkey_permissions (
//	    id, for_workspace_id, principal_type, principal_id, name, slug, description, created_at_m
//	) VALUES (
//	    ?, ?, ?, ?,
//	    ?, ?, ?, ?
//	)
func (q *Queries) InsertUnkeyPermission(ctx context.Context, db DBTX, arg InsertUnkeyPermissionParams) error {
	_, err := db.ExecContext(ctx, insertUnkeyPermission,
		arg.ID,
		arg.ForWorkspaceID,
		arg.PrincipalType,
		arg.PrincipalID,
		arg.Name,
		arg.Slug,
		arg.Description,
		arg.CreatedAtM,
	)
	return err
}
