// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: workspace_delete_billing_subscriptions.sql

package db

import (
	"context"
)

const deleteWorkspaceBillingSubscriptions = `-- name: DeleteWorkspaceBillingSubscriptions :exec
DELETE FROM ` + "`" + `billing_subscriptions` + "`" + ` WHERE workspace_id = ?
`

// Removes every Stripe subscription row for a workspace. Paired with
// ResetWorkspaceBilling by the `unkey dev stripe reset` tooling.
//
//	DELETE FROM `billing_subscriptions` WHERE workspace_id = ?
func (q *Queries) DeleteWorkspaceBillingSubscriptions(ctx context.Context, db DBTX, id string) error {
	_, err := db.ExecContext(ctx, deleteWorkspaceBillingSubscriptions, id)
	return err
}
