/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

/**
 * Connect a GitHub repository as the app source on creation.
 *
 * @remarks
 */
export type AppGitCreateInput = {
  /**
   * The GitHub repository to connect, as "owner/repo". The workspace must have
   *
   * @remarks
   * the Unkey GitHub App installed with access to it.
   */
  repository: string;
  /**
   * The branch this app's deployments track. Omit to adopt the repository's
   *
   * @remarks
   * default branch on GitHub.
   */
  defaultBranch?: string | undefined;
};

/** @internal */
export type AppGitCreateInput$Outbound = {
  repository: string;
  defaultBranch?: string | undefined;
};

/** @internal */
export const AppGitCreateInput$outboundSchema: z.ZodType<
  AppGitCreateInput$Outbound,
  z.ZodTypeDef,
  AppGitCreateInput
> = z.object({
  repository: z.string(),
  defaultBranch: z.string().optional(),
});

export function appGitCreateInputToJSON(
  appGitCreateInput: AppGitCreateInput,
): string {
  return JSON.stringify(
    AppGitCreateInput$outboundSchema.parse(appGitCreateInput),
  );
}
