/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type DeploymentGitAuthor = {
  /**
   * The GitHub login, or the handle the client sent.
   */
  handle: string;
  /**
   * The avatar URL for `handle`. Omitted when unknown.
   */
  avatarUrl?: string | undefined;
};

/** @internal */
export const DeploymentGitAuthor$inboundSchema: z.ZodType<
  DeploymentGitAuthor,
  z.ZodTypeDef,
  unknown
> = z.object({
  handle: z.string(),
  avatarUrl: z.string().optional(),
});

export function deploymentGitAuthorFromJSON(
  jsonString: string,
): SafeParseResult<DeploymentGitAuthor, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DeploymentGitAuthor$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DeploymentGitAuthor' from JSON`,
  );
}
