/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  DeploymentGitAuthor,
  DeploymentGitAuthor$inboundSchema,
} from "./deploymentgitauthor.js";

export type DeploymentGit = {
  /**
   * The git commit SHA this deployment was built from.
   */
  commitSha: string;
  /**
   * The git branch this deployment was built from. Omitted when unknown.
   */
  branch?: string | undefined;
  /**
   * The commit message. Omitted when unknown.
   */
  commitMessage?: string | undefined;
  /**
   * Unix timestamp in milliseconds when the commit was authored. Omitted when unknown.
   */
  commitTimestamp?: number | undefined;
  author?: DeploymentGitAuthor | undefined;
  /**
   * The pull request number this deployment was built for. Omitted when the commit is not part of a pull request.
   */
  prNumber?: number | undefined;
  /**
   * The `owner/repo` name of the fork this deployment was built from. Omitted
   *
   * @remarks
   * when it was built from the app's connected repository.
   */
  forkRepository?: string | undefined;
};

/** @internal */
export const DeploymentGit$inboundSchema: z.ZodType<
  DeploymentGit,
  z.ZodTypeDef,
  unknown
> = z.object({
  commitSha: z.string(),
  branch: z.string().optional(),
  commitMessage: z.string().optional(),
  commitTimestamp: z.number().int().optional(),
  author: DeploymentGitAuthor$inboundSchema.optional(),
  prNumber: z.number().int().optional(),
  forkRepository: z.string().optional(),
});

export function deploymentGitFromJSON(
  jsonString: string,
): SafeParseResult<DeploymentGit, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DeploymentGit$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DeploymentGit' from JSON`,
  );
}
