/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  BearerTokenLocation,
  BearerTokenLocation$inboundSchema,
  BearerTokenLocation$Outbound,
  BearerTokenLocation$outboundSchema,
} from "./bearertokenlocation.js";
import {
  HeaderKeyLocation,
  HeaderKeyLocation$inboundSchema,
  HeaderKeyLocation$Outbound,
  HeaderKeyLocation$outboundSchema,
} from "./headerkeylocation.js";
import {
  QueryParamKeyLocation,
  QueryParamKeyLocation$inboundSchema,
  QueryParamKeyLocation$Outbound,
  QueryParamKeyLocation$outboundSchema,
} from "./queryparamkeylocation.js";

/**
 * Where to look for the API key on incoming requests. Exactly one of
 *
 * @remarks
 * `bearer`, `header` or `queryParam` must be set.
 */
export type KeyLocation = {
  /**
   * Extract the key from the `Authorization Bearer` header.
   */
  bearer?: BearerTokenLocation | undefined;
  /**
   * Extract the key from a custom header.
   */
  header?: HeaderKeyLocation | undefined;
  /**
   * Extract the key from a query parameter.
   */
  queryParam?: QueryParamKeyLocation | undefined;
};

/** @internal */
export const KeyLocation$inboundSchema: z.ZodType<
  KeyLocation,
  z.ZodTypeDef,
  unknown
> = z.object({
  bearer: BearerTokenLocation$inboundSchema.optional(),
  header: HeaderKeyLocation$inboundSchema.optional(),
  queryParam: QueryParamKeyLocation$inboundSchema.optional(),
});
/** @internal */
export type KeyLocation$Outbound = {
  bearer?: BearerTokenLocation$Outbound | undefined;
  header?: HeaderKeyLocation$Outbound | undefined;
  queryParam?: QueryParamKeyLocation$Outbound | undefined;
};

/** @internal */
export const KeyLocation$outboundSchema: z.ZodType<
  KeyLocation$Outbound,
  z.ZodTypeDef,
  KeyLocation
> = z.object({
  bearer: BearerTokenLocation$outboundSchema.optional(),
  header: HeaderKeyLocation$outboundSchema.optional(),
  queryParam: QueryParamKeyLocation$outboundSchema.optional(),
});

export function keyLocationToJSON(keyLocation: KeyLocation): string {
  return JSON.stringify(KeyLocation$outboundSchema.parse(keyLocation));
}
export function keyLocationFromJSON(
  jsonString: string,
): SafeParseResult<KeyLocation, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => KeyLocation$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'KeyLocation' from JSON`,
  );
}
