/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  PortalBranding,
  PortalBranding$inboundSchema,
} from "./portalbranding.js";

/**
 * A Customer Portal configuration. Maps to exactly one keyspace or one app and
 *
 * @remarks
 * scopes the portal experience for a workspace's end users.
 */
export type PortalConfiguration = {
  /**
   * The unique identifier of the portal configuration, generated by Unkey.
   *
   * @remarks
   * Always begins with 'pc_'.
   */
  id: string;
  /**
   * Human-readable slug, unique within the workspace. Used by
   *
   * @remarks
   * `portal.createSession` to select the configuration.
   */
  slug: string;
  /**
   * Human-readable name for the portal, shown to end users in the portal UI
   *
   * @remarks
   * (e.g. the header and page titles). Unlike the slug, it is free-form.
   */
  displayName: string;
  /**
   * The keyspace this configuration maps to. Present when the configuration is
   *
   * @remarks
   * keyspace-mapped; omitted when it is app-mapped.
   */
  keyspaceId?: string | undefined;
  /**
   * The app this configuration maps to. Present when the configuration is
   *
   * @remarks
   * app-mapped; omitted when it is keyspace-mapped.
   */
  appId?: string | undefined;
  /**
   * Whether the portal configuration is enabled. Disabled configurations reject
   *
   * @remarks
   * new session creation.
   */
  enabled: boolean;
  /**
   * URL the end user is returned to when they exit the portal.
   *
   * @remarks
   */
  returnUrl?: string | undefined;
  /**
   * Optional branding applied to the Customer Portal for a configuration.
   *
   * @remarks
   */
  branding?: PortalBranding | undefined;
  /**
   * Unix timestamp in milliseconds when the configuration was created.
   *
   * @remarks
   */
  createdAt: number;
  /**
   * Unix timestamp in milliseconds when the configuration was last updated.
   *
   * @remarks
   * Omitted if the configuration has never been updated.
   */
  updatedAt?: number | undefined;
};

/** @internal */
export const PortalConfiguration$inboundSchema: z.ZodType<
  PortalConfiguration,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
  slug: z.string(),
  displayName: z.string(),
  keyspaceId: z.string().optional(),
  appId: z.string().optional(),
  enabled: z.boolean(),
  returnUrl: z.string().optional(),
  branding: PortalBranding$inboundSchema.optional(),
  createdAt: z.number().int(),
  updatedAt: z.number().int().optional(),
});

export function portalConfigurationFromJSON(
  jsonString: string,
): SafeParseResult<PortalConfiguration, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PortalConfiguration$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PortalConfiguration' from JSON`,
  );
}
