/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * Whether `id` names an app or a keyspace.
 *
 * @remarks
 */
export const PortalMappingType = {
  App: "app",
  Keyspace: "keyspace",
} as const;
/**
 * Whether `id` names an app or a keyspace.
 *
 * @remarks
 */
export type PortalMappingType = ClosedEnum<typeof PortalMappingType>;

/**
 * The single resource a portal serves keys for.
 *
 * @remarks
 *
 * A portal maps to exactly one app or one keyspace, never several and never
 * neither. Naming the kind and the id together makes that invariant part of the
 * request shape: there is no way to express a portal with two mappings, and no
 * way to express one with none.
 */
export type PortalMapping = {
  /**
   * Whether `id` names an app or a keyspace.
   *
   * @remarks
   */
  type: PortalMappingType;
  /**
   * The id of the app or keyspace this portal serves. Must belong to your
   *
   * @remarks
   * workspace.
   */
  id: string;
};

/** @internal */
export const PortalMappingType$inboundSchema: z.ZodNativeEnum<
  typeof PortalMappingType
> = z.nativeEnum(PortalMappingType);
/** @internal */
export const PortalMappingType$outboundSchema: z.ZodNativeEnum<
  typeof PortalMappingType
> = PortalMappingType$inboundSchema;

/** @internal */
export const PortalMapping$inboundSchema: z.ZodType<
  PortalMapping,
  z.ZodTypeDef,
  unknown
> = z.object({
  type: PortalMappingType$inboundSchema,
  id: z.string(),
});
/** @internal */
export type PortalMapping$Outbound = {
  type: string;
  id: string;
};

/** @internal */
export const PortalMapping$outboundSchema: z.ZodType<
  PortalMapping$Outbound,
  z.ZodTypeDef,
  PortalMapping
> = z.object({
  type: PortalMappingType$outboundSchema,
  id: z.string(),
});

export function portalMappingToJSON(portalMapping: PortalMapping): string {
  return JSON.stringify(PortalMapping$outboundSchema.parse(portalMapping));
}
export function portalMappingFromJSON(
  jsonString: string,
): SafeParseResult<PortalMapping, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PortalMapping$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PortalMapping' from JSON`,
  );
}
