/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

/**
 * Promote a ready deployment to become the current deployment for its environment.
 */
export type V2DeploymentsPromoteDeploymentRequestBody = {
  /**
   * Identifies a resource by either its unique ID or its slug.
   *
   * @remarks
   * Accepts a prefixed ID (such as 'proj_' or 'app_') or a slug.
   */
  deploymentId: string;
};

/** @internal */
export type V2DeploymentsPromoteDeploymentRequestBody$Outbound = {
  deploymentId: string;
};

/** @internal */
export const V2DeploymentsPromoteDeploymentRequestBody$outboundSchema:
  z.ZodType<
    V2DeploymentsPromoteDeploymentRequestBody$Outbound,
    z.ZodTypeDef,
    V2DeploymentsPromoteDeploymentRequestBody
  > = z.object({
    deploymentId: z.string(),
  });

export function v2DeploymentsPromoteDeploymentRequestBodyToJSON(
  v2DeploymentsPromoteDeploymentRequestBody:
    V2DeploymentsPromoteDeploymentRequestBody,
): string {
  return JSON.stringify(
    V2DeploymentsPromoteDeploymentRequestBody$outboundSchema.parse(
      v2DeploymentsPromoteDeploymentRequestBody,
    ),
  );
}
