/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

export type V2EnvironmentsGetEnvironmentRequestBody = {
  /**
   * Identifies a resource by either its unique ID or its slug.
   *
   * @remarks
   * Accepts a prefixed ID (such as 'proj_' or 'app_') or a slug.
   */
  project: string;
  /**
   * Identifies a resource by either its unique ID or its slug.
   *
   * @remarks
   * Accepts a prefixed ID (such as 'proj_' or 'app_') or a slug.
   */
  app: string;
  /**
   * Identifies a resource by either its unique ID or its slug.
   *
   * @remarks
   * Accepts a prefixed ID (such as 'proj_' or 'app_') or a slug.
   */
  environment: string;
};

/** @internal */
export type V2EnvironmentsGetEnvironmentRequestBody$Outbound = {
  project: string;
  app: string;
  environment: string;
};

/** @internal */
export const V2EnvironmentsGetEnvironmentRequestBody$outboundSchema: z.ZodType<
  V2EnvironmentsGetEnvironmentRequestBody$Outbound,
  z.ZodTypeDef,
  V2EnvironmentsGetEnvironmentRequestBody
> = z.object({
  project: z.string(),
  app: z.string(),
  environment: z.string(),
});

export function v2EnvironmentsGetEnvironmentRequestBodyToJSON(
  v2EnvironmentsGetEnvironmentRequestBody:
    V2EnvironmentsGetEnvironmentRequestBody,
): string {
  return JSON.stringify(
    V2EnvironmentsGetEnvironmentRequestBody$outboundSchema.parse(
      v2EnvironmentsGetEnvironmentRequestBody,
    ),
  );
}
