/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

export type V2GatewayListPoliciesRequestBody = {
  /**
   * Identifies a resource by either its unique ID or its slug.
   *
   * @remarks
   * Accepts a prefixed ID (such as 'proj_' or 'app_') or a slug.
   */
  project: string;
  /**
   * Identifies a resource by either its unique ID or its slug.
   *
   * @remarks
   * Accepts a prefixed ID (such as 'proj_' or 'app_') or a slug.
   */
  app: string;
  /**
   * Identifies a resource by either its unique ID or its slug.
   *
   * @remarks
   * Accepts a prefixed ID (such as 'proj_' or 'app_') or a slug.
   */
  environment: string;
};

/** @internal */
export type V2GatewayListPoliciesRequestBody$Outbound = {
  project: string;
  app: string;
  environment: string;
};

/** @internal */
export const V2GatewayListPoliciesRequestBody$outboundSchema: z.ZodType<
  V2GatewayListPoliciesRequestBody$Outbound,
  z.ZodTypeDef,
  V2GatewayListPoliciesRequestBody
> = z.object({
  project: z.string(),
  app: z.string(),
  environment: z.string(),
});

export function v2GatewayListPoliciesRequestBodyToJSON(
  v2GatewayListPoliciesRequestBody: V2GatewayListPoliciesRequestBody,
): string {
  return JSON.stringify(
    V2GatewayListPoliciesRequestBody$outboundSchema.parse(
      v2GatewayListPoliciesRequestBody,
    ),
  );
}
