/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

export type V2PermissionsUpdatePermissionRequestBody = {
  /**
   * The permission to update. Pass the permission ID (`perm_...`) or its current slug.
   *
   * @remarks
   */
  permission: string;
  /**
   * New human-readable name for the permission.
   *
   * @remarks
   * Omit this field to keep the current name.
   */
  name?: string | undefined;
  /**
   * New slug for the permission. Keys and roles that have this permission get the new slug in verification responses.
   *
   * @remarks
   * The slug must be unique in your workspace.
   * Omit this field to keep the current slug.
   */
  slug?: string | undefined;
  /**
   * New description for the permission.
   *
   * @remarks
   * Omit this field to keep the current description. Send null or an empty string to remove it.
   */
  description?: string | null | undefined;
};

/** @internal */
export type V2PermissionsUpdatePermissionRequestBody$Outbound = {
  permission: string;
  name?: string | undefined;
  slug?: string | undefined;
  description?: string | null | undefined;
};

/** @internal */
export const V2PermissionsUpdatePermissionRequestBody$outboundSchema: z.ZodType<
  V2PermissionsUpdatePermissionRequestBody$Outbound,
  z.ZodTypeDef,
  V2PermissionsUpdatePermissionRequestBody
> = z.object({
  permission: z.string(),
  name: z.string().optional(),
  slug: z.string().optional(),
  description: z.nullable(z.string()).optional(),
});

export function v2PermissionsUpdatePermissionRequestBodyToJSON(
  v2PermissionsUpdatePermissionRequestBody:
    V2PermissionsUpdatePermissionRequestBody,
): string {
  return JSON.stringify(
    V2PermissionsUpdatePermissionRequestBody$outboundSchema.parse(
      v2PermissionsUpdatePermissionRequestBody,
    ),
  );
}
