/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import {
  PortalBranding,
  PortalBranding$Outbound,
  PortalBranding$outboundSchema,
} from "./portalbranding.js";

export type V2PortalCreateConfigurationRequestBody = {
  /**
   * Human-readable slug for the configuration, unique within the workspace.
   *
   * @remarks
   * Must be 3-64 characters, lowercase alphanumeric and hyphens only, must not
   * start or end with a hyphen, and must not contain consecutive hyphens.
   */
  slug: string;
  /**
   * The keyspace the configuration maps to. Provide exactly one of
   *
   * @remarks
   * `keyspaceId` or `appId`.
   */
  keyspaceId?: string | undefined;
  /**
   * The app the configuration maps to. Provide exactly one of `keyspaceId` or
   *
   * @remarks
   * `appId`.
   */
  appId?: string | undefined;
  /**
   * Whether the configuration is enabled. Disabled configurations reject new
   *
   * @remarks
   * session creation.
   */
  enabled?: boolean | undefined;
  /**
   * URL the end user is returned to when they exit the portal.
   *
   * @remarks
   */
  returnUrl?: string | undefined;
  /**
   * Optional branding applied to the Customer Portal for a configuration.
   *
   * @remarks
   */
  branding?: PortalBranding | undefined;
};

/** @internal */
export type V2PortalCreateConfigurationRequestBody$Outbound = {
  slug: string;
  keyspaceId?: string | undefined;
  appId?: string | undefined;
  enabled: boolean;
  returnUrl?: string | undefined;
  branding?: PortalBranding$Outbound | undefined;
};

/** @internal */
export const V2PortalCreateConfigurationRequestBody$outboundSchema: z.ZodType<
  V2PortalCreateConfigurationRequestBody$Outbound,
  z.ZodTypeDef,
  V2PortalCreateConfigurationRequestBody
> = z.object({
  slug: z.string(),
  keyspaceId: z.string().optional(),
  appId: z.string().optional(),
  enabled: z.boolean().default(true),
  returnUrl: z.string().optional(),
  branding: PortalBranding$outboundSchema.optional(),
});

export function v2PortalCreateConfigurationRequestBodyToJSON(
  v2PortalCreateConfigurationRequestBody:
    V2PortalCreateConfigurationRequestBody,
): string {
  return JSON.stringify(
    V2PortalCreateConfigurationRequestBody$outboundSchema.parse(
      v2PortalCreateConfigurationRequestBody,
    ),
  );
}
