/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

export type V2RootKeysUpdateKeyRequestBody = {
  /**
   * Root key identifier returned by rootKeys.createKey or rootKeys.listKeys.
   */
  keyId: string;
  /**
   * New root key name. Set null to remove the name. Omit to keep the current name.
   */
  name?: string | null | undefined;
  /**
   * Whether the root key can authenticate. Omit to keep the current state.
   */
  enabled?: boolean | undefined;
  /**
   * Complete replacement permission set. Every permission must be a supported URN in the authenticated workspace
   *
   * @remarks
   * and within the caller's permissions. Omit to keep the current permissions.
   */
  permissions?: Array<string> | undefined;
};

/** @internal */
export type V2RootKeysUpdateKeyRequestBody$Outbound = {
  keyId: string;
  name?: string | null | undefined;
  enabled?: boolean | undefined;
  permissions?: Array<string> | undefined;
};

/** @internal */
export const V2RootKeysUpdateKeyRequestBody$outboundSchema: z.ZodType<
  V2RootKeysUpdateKeyRequestBody$Outbound,
  z.ZodTypeDef,
  V2RootKeysUpdateKeyRequestBody
> = z.object({
  keyId: z.string(),
  name: z.nullable(z.string()).optional(),
  enabled: z.boolean().optional(),
  permissions: z.array(z.string()).optional(),
});

export function v2RootKeysUpdateKeyRequestBodyToJSON(
  v2RootKeysUpdateKeyRequestBody: V2RootKeysUpdateKeyRequestBody,
): string {
  return JSON.stringify(
    V2RootKeysUpdateKeyRequestBody$outboundSchema.parse(
      v2RootKeysUpdateKeyRequestBody,
    ),
  );
}
