/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * A workspace compute limit and the capacity reserved against it.
 */
export type V2WorkspaceGetLimitsReservedMeter = {
  /**
   * The maximum the workspace can reserve.
   */
  limit: number;
  /**
   * The amount running deployments reserve now.
   */
  reserved: number;
};

/** @internal */
export const V2WorkspaceGetLimitsReservedMeter$inboundSchema: z.ZodType<
  V2WorkspaceGetLimitsReservedMeter,
  z.ZodTypeDef,
  unknown
> = z.object({
  limit: z.number().int(),
  reserved: z.number().int(),
});

export function v2WorkspaceGetLimitsReservedMeterFromJSON(
  jsonString: string,
): SafeParseResult<V2WorkspaceGetLimitsReservedMeter, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => V2WorkspaceGetLimitsReservedMeter$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'V2WorkspaceGetLimitsReservedMeter' from JSON`,
  );
}
