/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  V2WorkspaceGetUsageGateway,
  V2WorkspaceGetUsageGateway$inboundSchema,
} from "./v2workspacegetusagegateway.js";
import {
  V2WorkspaceGetUsageResource,
  V2WorkspaceGetUsageResource$inboundSchema,
} from "./v2workspacegetusageresource.js";

/**
 * Active gateway keys counted for one app in the period.
 */
export type V2WorkspaceGetUsageByAppRow = {
  /**
   * The project the app belongs to. Omitted when the app was deleted or `app` is omitted.
   */
  project?: V2WorkspaceGetUsageResource | undefined;
  /**
   * The app whose gateway verified the keys. Omitted for keys whose
   *
   * @remarks
   * verifications were all recorded before Unkey stored app ids.
   */
  app?: V2WorkspaceGetUsageResource | undefined;
  /**
   * Unkey gateway usage in the period.
   */
  gateway: V2WorkspaceGetUsageGateway;
};

/** @internal */
export const V2WorkspaceGetUsageByAppRow$inboundSchema: z.ZodType<
  V2WorkspaceGetUsageByAppRow,
  z.ZodTypeDef,
  unknown
> = z.object({
  project: V2WorkspaceGetUsageResource$inboundSchema.optional(),
  app: V2WorkspaceGetUsageResource$inboundSchema.optional(),
  gateway: V2WorkspaceGetUsageGateway$inboundSchema,
});

export function v2WorkspaceGetUsageByAppRowFromJSON(
  jsonString: string,
): SafeParseResult<V2WorkspaceGetUsageByAppRow, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => V2WorkspaceGetUsageByAppRow$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'V2WorkspaceGetUsageByAppRow' from JSON`,
  );
}
