/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import { Meta, Meta$inboundSchema } from "./meta.js";
import {
  V3DeploymentsCreateDeploymentResponseData,
  V3DeploymentsCreateDeploymentResponseData$inboundSchema,
} from "./v3deploymentscreatedeploymentresponsedata.js";

export type V3DeploymentsCreateDeploymentResponseBody = {
  /**
   * Metadata object included in every API response. This provides context about the request and is essential for debugging, audit trails, and support inquiries. The `requestId` is particularly important when troubleshooting issues with the Unkey support team.
   */
  meta: Meta;
  data: V3DeploymentsCreateDeploymentResponseData;
};

/** @internal */
export const V3DeploymentsCreateDeploymentResponseBody$inboundSchema: z.ZodType<
  V3DeploymentsCreateDeploymentResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  meta: Meta$inboundSchema,
  data: V3DeploymentsCreateDeploymentResponseData$inboundSchema,
});

export function v3DeploymentsCreateDeploymentResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<
  V3DeploymentsCreateDeploymentResponseBody,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      V3DeploymentsCreateDeploymentResponseBody$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'V3DeploymentsCreateDeploymentResponseBody' from JSON`,
  );
}
