/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type V3DeploymentsCreateDeploymentResponseData = {
  /**
   * Unique deployment identifier
   */
  deploymentId: string;
};

/** @internal */
export const V3DeploymentsCreateDeploymentResponseData$inboundSchema: z.ZodType<
  V3DeploymentsCreateDeploymentResponseData,
  z.ZodTypeDef,
  unknown
> = z.object({
  deploymentId: z.string(),
});

export function v3DeploymentsCreateDeploymentResponseDataFromJSON(
  jsonString: string,
): SafeParseResult<
  V3DeploymentsCreateDeploymentResponseData,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      V3DeploymentsCreateDeploymentResponseData$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'V3DeploymentsCreateDeploymentResponseData' from JSON`,
  );
}
