// Code generated by generate-rpc-clients. DO NOT EDIT.

package ctrl

import (
	"context"

	"connectrpc.com/connect"
	v1 "github.com/unkeyed/unkey/gen/proto/ctrl/v1"
	"github.com/unkeyed/unkey/gen/proto/ctrl/v1/ctrlv1connect"
)

// CustomDomainServiceClient wraps ctrlv1connect.CustomDomainServiceClient with simplified signatures.
// Request and response types are plain protobuf messages without connect wrappers.
type CustomDomainServiceClient interface {
	AddCustomDomain(ctx context.Context, req *v1.AddCustomDomainRequest) (*v1.AddCustomDomainResponse, error)
	DeleteCustomDomain(ctx context.Context, req *v1.DeleteCustomDomainRequest) (*v1.DeleteCustomDomainResponse, error)
	RetryVerification(ctx context.Context, req *v1.RetryVerificationRequest) (*v1.RetryVerificationResponse, error)
}

var _ CustomDomainServiceClient = (*ConnectCustomDomainServiceClient)(nil)

// ConnectCustomDomainServiceClient adapts a ctrlv1connect.CustomDomainServiceClient to the simplified CustomDomainServiceClient interface.
type ConnectCustomDomainServiceClient struct {
	inner ctrlv1connect.CustomDomainServiceClient
}

// NewConnectCustomDomainServiceClient creates a new ConnectCustomDomainServiceClient.
func NewConnectCustomDomainServiceClient(inner ctrlv1connect.CustomDomainServiceClient) *ConnectCustomDomainServiceClient {
	return &ConnectCustomDomainServiceClient{inner: inner}
}

func (c *ConnectCustomDomainServiceClient) AddCustomDomain(ctx context.Context, req *v1.AddCustomDomainRequest) (*v1.AddCustomDomainResponse, error) {
	resp, err := c.inner.AddCustomDomain(ctx, connect.NewRequest(req))
	if err != nil {
		return nil, err
	}
	return resp.Msg, nil
}

func (c *ConnectCustomDomainServiceClient) DeleteCustomDomain(ctx context.Context, req *v1.DeleteCustomDomainRequest) (*v1.DeleteCustomDomainResponse, error) {
	resp, err := c.inner.DeleteCustomDomain(ctx, connect.NewRequest(req))
	if err != nil {
		return nil, err
	}
	return resp.Msg, nil
}

func (c *ConnectCustomDomainServiceClient) RetryVerification(ctx context.Context, req *v1.RetryVerificationRequest) (*v1.RetryVerificationResponse, error) {
	resp, err := c.inner.RetryVerification(ctx, connect.NewRequest(req))
	if err != nil {
		return nil, err
	}
	return resp.Msg, nil
}
