export const tiers = {
  free: {
    name: "Free Tier",
    href: "/",
    price: 0,
    description: "Everything you need to start!",
    buttonText: "Free",
    features: [
      "1k API keys",
      "2.5k successful verifications / month",
      "100k successful ratelimits / month",
      "7-day analytics retention",
      "Unlimited APIs",
    ],
    footnotes: [],
  },
  pro: {
    name: "Pro Tier",
    href: "/",
    price: 25,
    description: "For growing teams with powerful demands",
    buttonText: "Pro",
    features: [
      "1M API keys",
      "150k successful verifications / month *",
      "2.5M successful ratelimits / month **",
      "90-day analytics retention",
      "90-day audit log retention",
      "Unlimited APIs",
      "Workspaces with team members",
    ],
    footnotes: [
      "* Additional verifications are billed at $1 per 10,000",
      "** Additional ratelimits are billed at $1 per 100,000",
    ],
  },
  custom: {
    name: "Custom",
    href: "https://cal.com/team/unkey/user-interview?utm_source=banner&utm_campaign=oss",
    price: "Let's talk",
    description: "We offer custom pricing for those with volume needs",
    buttonText: "Schedule a call",
    features: [
      "Custom Quotas",
      "IP Whitelisting",
      "Dedicated support",
      "Custom Active Key Limits",
      "Pricing based on your needs",
      "Custom Analytics Retention",
    ],
    footnotes: [],
  },
};
