name: Go
on:
  workflow_call:
permissions:
  contents: read
jobs:
  build:
    name: Build and Test
    runs-on: depot-ubuntu-24.04-8
    timeout-minutes: 30
    env:
      RASK_CACHE_DIR: ./.rask-cache #/mnt/depot-cache/rask
      RASK_REMOTE_CACHE_BUCKET: rask
      RASK_REMOTE_CACHE_PREFIX: ""
      RASK_REMOTE_CACHE_REGION: auto
      RASK_REMOTE_CACHE_ENDPOINT: ${{ secrets.RASK_REMOTE_CACHE_ENDPOINT }}
      RASK_REMOTE_CACHE_ACCESS_KEY_ID: ${{ secrets.RASK_REMOTE_CACHE_ACCESS_KEY_ID }}
      RASK_REMOTE_CACHE_SECRET_ACCESS_KEY: ${{ secrets.RASK_REMOTE_CACHE_SECRET_ACCESS_KEY }}
    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4
      # - name: Mount Rask cache disk
      #   uses: depot/cache-mount@v1
      #   with:
      #     name: unkey-rask-cache
      #     path: /mnt/depot-cache
      #     write-lock: /mnt/depot-cache/rask
      - name: Install mise
        run: |
          ./dev/install-mise
          echo "$HOME/.local/bin" >> "$GITHUB_PATH"
      - name: Install toolchain
        run: mise install --locked --yes
      - name: Build
        run: mise run build
      - name: Run tests
        run: mise run test
