// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: global_counters_imported.sql

package db

import (
	"context"
)

const globalCountersImported = `-- name: GlobalCountersImported :many
SELECT
    workspace_id,
    namespace,
    identifier,
    duration_ms,
    sequence,
    CAST(SUM(count) AS SIGNED) AS imported
FROM ratelimit_global_counters
WHERE expires_at > ?
  AND region != ?
GROUP BY workspace_id, namespace, identifier, duration_ms, sequence
`

type GlobalCountersImportedParams struct {
	Now        uint64 `db:"now"`
	SelfRegion string `db:"self_region"`
}

type GlobalCountersImportedRow struct {
	WorkspaceID string `db:"workspace_id"`
	Namespace   string `db:"namespace"`
	Identifier  string `db:"identifier"`
	DurationMs  uint64 `db:"duration_ms"`
	Sequence    int64  `db:"sequence"`
	Imported    int64  `db:"imported"`
}

// GlobalCountersImported returns the sum of foreign-region contributions for
// every still-active window cell, with each region's row excluded from its
// own caller. Receivers fold the returned `imported` directly into
// counterEntry.imported via atomicMax; aggregation runs in MySQL because
// the application only ever uses the sum, so transferring per-region rows
// just to collapse them in Go wastes bandwidth and memory. The SUM is cast
// to SIGNED so sqlc maps it to int64, matching atomic.Int64 in the caller.
//
//	SELECT
//	    workspace_id,
//	    namespace,
//	    identifier,
//	    duration_ms,
//	    sequence,
//	    CAST(SUM(count) AS SIGNED) AS imported
//	FROM ratelimit_global_counters
//	WHERE expires_at > ?
//	  AND region != ?
//	GROUP BY workspace_id, namespace, identifier, duration_ms, sequence
func (q *Queries) GlobalCountersImported(ctx context.Context, arg GlobalCountersImportedParams) ([]GlobalCountersImportedRow, error) {
	rows, err := q.db.QueryContext(ctx, globalCountersImported, arg.Now, arg.SelfRegion)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GlobalCountersImportedRow
	for rows.Next() {
		var i GlobalCountersImportedRow
		if err := rows.Scan(
			&i.WorkspaceID,
			&i.Namespace,
			&i.Identifier,
			&i.DurationMs,
			&i.Sequence,
			&i.Imported,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
