package main

//go:generate go run main.go

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"text/template"
	"time"
)

// TestCase defines a single rate limit test configuration
type TestCase struct {
	NodeCount   int
	Limit       int64
	Duration    int64
	LoadFactor  float64
	WindowCount int
}

func (tc TestCase) TestName() string {
	return fmt.Sprintf("TestIntegration_RateLimit_Nodes%02d_Limit%04d_Duration%09d_Load%s_Windows%03d",
		tc.NodeCount,
		tc.Limit,
		tc.Duration,
		strings.ReplaceAll(fmt.Sprintf("%05.2f", tc.LoadFactor), ".", "_"),
		tc.WindowCount,
	)

}

// Define test matrix parameters
var (
	nodeCounts   = []int{1, 3, 9}
	limits       = []int64{5, 100}
	durations    = []time.Duration{time.Second, time.Minute, time.Hour}
	loadFactors  = []float64{0.9, 2.0, 10.0}
	windowCounts = []int{10}
)

const testTemplate = `// Code generated by go generate; DO NOT EDIT.
package generated

import (
	"testing"

	"github.com/unkeyed/unkey/go/apps/api/integration"
	run "github.com/unkeyed/unkey/go/apps/api/integration/multi_node_ratelimiting"
	"github.com/unkeyed/unkey/go/pkg/testutil"
)

func {{ .TestName }}(t *testing.T) {
	testutil.SkipUnlessIntegration(t)

	h := integration.New(t, integration.Config{
		NumNodes: {{ .NodeCount }},
	})

	run.RunRateLimitTest(
		t,
		h,
		{{ .Limit }},            // limit
		{{ .Duration }},         // duration
		{{ .WindowCount }},      // window count
		{{ .LoadFactor }},       // load factor
		{{ .NodeCount }},        // node count
	)
}
`

func main() {
	// Create base directory for generated tests
	baseDir := "../generated"
	err := os.RemoveAll(baseDir)
	if err != nil {
		panic(err)
	}
	err = os.MkdirAll(baseDir, 0755)
	if err != nil {
		panic(err)
	}

	// Parse template
	testTmpl, err := template.New("test").Parse(testTemplate)
	if err != nil {
		panic(err)
	}

	// Generate test cases
	var testCases []TestCase
	for _, nodeCount := range nodeCounts {
		for _, limit := range limits {
			for _, duration := range durations {
				for _, loadFactor := range loadFactors {
					for _, windowCount := range windowCounts {
						testCases = append(testCases, TestCase{
							NodeCount:   nodeCount,
							Limit:       limit,
							Duration:    duration.Milliseconds(),
							LoadFactor:  loadFactor,
							WindowCount: windowCount,
						})
					}
				}
			}
		}
	}

	// Generate individual test files in the same package
	for i, tc := range testCases {
		fileName := fmt.Sprintf("%s_test.go", strings.ToLower(tc.TestName()[4:])) // Remove "Test" prefix and lowercase
		filePath := filepath.Join(baseDir, fileName)

		file, err := os.Create(filePath)
		if err != nil {
			panic(err)
		}

		err = testTmpl.Execute(file, tc)
		if err != nil {
			panic(err)
		}

		err = file.Close()
		if err != nil {
			panic(err)
		}

		if i < 5 { // Show first 5 files for feedback
			fmt.Printf("Generated: %s\n", fileName)
		}
	}

	fmt.Printf("Generated %d test files in package 'generated'\n", len(testCases))
}
