// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: acme_challenge_try_claiming.sql

package db

import (
	"context"
	"database/sql"
)

const updateAcmeChallengeTryClaiming = `-- name: UpdateAcmeChallengeTryClaiming :exec
UPDATE acme_challenges
SET status = ?, updated_at = ?
WHERE domain_id = ? AND status = 'waiting'
`

type UpdateAcmeChallengeTryClaimingParams struct {
	Status    AcmeChallengesStatus `db:"status"`
	UpdatedAt sql.NullInt64        `db:"updated_at"`
	DomainID  string               `db:"domain_id"`
}

// UpdateAcmeChallengeTryClaiming
//
//	UPDATE acme_challenges
//	SET status = ?, updated_at = ?
//	WHERE domain_id = ? AND status = 'waiting'
func (q *Queries) UpdateAcmeChallengeTryClaiming(ctx context.Context, db DBTX, arg UpdateAcmeChallengeTryClaimingParams) error {
	_, err := db.ExecContext(ctx, updateAcmeChallengeTryClaiming, arg.Status, arg.UpdatedAt, arg.DomainID)
	return err
}
