// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: branch_insert.sql

package db

import (
	"context"
	"database/sql"
)

const insertBranch = `-- name: InsertBranch :exec
INSERT INTO branches (
    id,
    workspace_id,
    project_id,
    name,
    created_at,
    updated_at
) VALUES (
    ?, ?, ?, ?, ?, ?
)
`

type InsertBranchParams struct {
	ID          string        `db:"id"`
	WorkspaceID string        `db:"workspace_id"`
	ProjectID   string        `db:"project_id"`
	Name        string        `db:"name"`
	CreatedAt   int64         `db:"created_at"`
	UpdatedAt   sql.NullInt64 `db:"updated_at"`
}

// InsertBranch
//
//	INSERT INTO branches (
//	    id,
//	    workspace_id,
//	    project_id,
//	    name,
//	    created_at,
//	    updated_at
//	) VALUES (
//	    ?, ?, ?, ?, ?, ?
//	)
func (q *Queries) InsertBranch(ctx context.Context, db DBTX, arg InsertBranchParams) error {
	_, err := db.ExecContext(ctx, insertBranch,
		arg.ID,
		arg.WorkspaceID,
		arg.ProjectID,
		arg.Name,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}
