// Code generated by sqlc bulk insert plugin. DO NOT EDIT.

package db

import (
	"context"
	"fmt"
	"strings"
)

// bulkInsertKeyRole is the base query for bulk insert
const bulkInsertKeyRole = `INSERT INTO keys_roles ( key_id, role_id, workspace_id, created_at_m ) VALUES %s`

// InsertKeyRoles performs bulk insert in a single query
func (q *BulkQueries) InsertKeyRoles(ctx context.Context, db DBTX, args []InsertKeyRoleParams) error {

	if len(args) == 0 {
		return nil
	}

	// Build the bulk insert query
	valueClauses := make([]string, len(args))
	for i := range args {
		valueClauses[i] = "( ?, ?, ?, ? )"
	}

	bulkQuery := fmt.Sprintf(bulkInsertKeyRole, strings.Join(valueClauses, ", "))

	// Collect all arguments
	var allArgs []any
	for _, arg := range args {
		allArgs = append(allArgs, arg.KeyID)
		allArgs = append(allArgs, arg.RoleID)
		allArgs = append(allArgs, arg.WorkspaceID)
		allArgs = append(allArgs, arg.CreatedAtM)
	}

	// Execute the bulk insert
	_, err := db.ExecContext(ctx, bulkQuery, allArgs...)
	return err
}
