// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: deployment_insert.sql

package db

import (
	"context"
	"database/sql"
)

const insertDeployment = `-- name: InsertDeployment :exec
INSERT INTO ` + "`" + `deployments` + "`" + ` (
    id,
    k8s_name,
    workspace_id,
    project_id,
    environment_id,
    git_commit_sha,
    git_branch,
    sentinel_config,
    git_commit_message,
    git_commit_author_handle,
    git_commit_author_avatar_url,
    git_commit_timestamp, -- Unix epoch milliseconds
    openapi_spec,
    status,
    cpu_millicores,
		memory_mib,
    created_at
)
VALUES (
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
		?,
		?
)
`

type InsertDeploymentParams struct {
	ID                       string            `db:"id"`
	K8sName                  string            `db:"k8s_name"`
	WorkspaceID              string            `db:"workspace_id"`
	ProjectID                string            `db:"project_id"`
	EnvironmentID            string            `db:"environment_id"`
	GitCommitSha             sql.NullString    `db:"git_commit_sha"`
	GitBranch                sql.NullString    `db:"git_branch"`
	SentinelConfig           []byte            `db:"sentinel_config"`
	GitCommitMessage         sql.NullString    `db:"git_commit_message"`
	GitCommitAuthorHandle    sql.NullString    `db:"git_commit_author_handle"`
	GitCommitAuthorAvatarUrl sql.NullString    `db:"git_commit_author_avatar_url"`
	GitCommitTimestamp       sql.NullInt64     `db:"git_commit_timestamp"`
	OpenapiSpec              sql.NullString    `db:"openapi_spec"`
	Status                   DeploymentsStatus `db:"status"`
	CpuMillicores            int32             `db:"cpu_millicores"`
	MemoryMib                int32             `db:"memory_mib"`
	CreatedAt                int64             `db:"created_at"`
}

// InsertDeployment
//
//	INSERT INTO `deployments` (
//	    id,
//	    k8s_name,
//	    workspace_id,
//	    project_id,
//	    environment_id,
//	    git_commit_sha,
//	    git_branch,
//	    sentinel_config,
//	    git_commit_message,
//	    git_commit_author_handle,
//	    git_commit_author_avatar_url,
//	    git_commit_timestamp, -- Unix epoch milliseconds
//	    openapi_spec,
//	    status,
//	    cpu_millicores,
//			memory_mib,
//	    created_at
//	)
//	VALUES (
//	    ?,
//	    ?,
//	    ?,
//	    ?,
//	    ?,
//	    ?,
//	    ?,
//	    ?,
//	    ?,
//	    ?,
//	    ?,
//	    ?,
//	    ?,
//	    ?,
//	    ?,
//			?,
//			?
//	)
func (q *Queries) InsertDeployment(ctx context.Context, db DBTX, arg InsertDeploymentParams) error {
	_, err := db.ExecContext(ctx, insertDeployment,
		arg.ID,
		arg.K8sName,
		arg.WorkspaceID,
		arg.ProjectID,
		arg.EnvironmentID,
		arg.GitCommitSha,
		arg.GitBranch,
		arg.SentinelConfig,
		arg.GitCommitMessage,
		arg.GitCommitAuthorHandle,
		arg.GitCommitAuthorAvatarUrl,
		arg.GitCommitTimestamp,
		arg.OpenapiSpec,
		arg.Status,
		arg.CpuMillicores,
		arg.MemoryMib,
		arg.CreatedAt,
	)
	return err
}
