// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: domain_challenge_update_status.sql

package db

import (
	"context"
	"database/sql"
)

const updateDomainChallengeStatus = `-- name: UpdateDomainChallengeStatus :exec
UPDATE domain_challenges
SET status = ?, updated_at = ?
WHERE domain_id = ?
`

type UpdateDomainChallengeStatusParams struct {
	Status    DomainChallengesStatus `db:"status"`
	UpdatedAt sql.NullInt64          `db:"updated_at"`
	DomainID  string                 `db:"domain_id"`
}

// UpdateDomainChallengeStatus
//
//	UPDATE domain_challenges
//	SET status = ?, updated_at = ?
//	WHERE domain_id = ?
func (q *Queries) UpdateDomainChallengeStatus(ctx context.Context, db DBTX, arg UpdateDomainChallengeStatusParams) error {
	_, err := db.ExecContext(ctx, updateDomainChallengeStatus, arg.Status, arg.UpdatedAt, arg.DomainID)
	return err
}
