// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: domain_find_by_domain.sql

package db

import (
	"context"
)

const findDomainByDomain = `-- name: FindDomainByDomain :one
SELECT id, workspace_id, project_id, environment_id, deployment_id, rolled_back_deployment_id, domain, type, sticky, created_at, updated_at FROM domains WHERE domain = ?
`

// FindDomainByDomain
//
//	SELECT id, workspace_id, project_id, environment_id, deployment_id, rolled_back_deployment_id, domain, type, sticky, created_at, updated_at FROM domains WHERE domain = ?
func (q *Queries) FindDomainByDomain(ctx context.Context, db DBTX, domain string) (Domain, error) {
	row := db.QueryRowContext(ctx, findDomainByDomain, domain)
	var i Domain
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ProjectID,
		&i.EnvironmentID,
		&i.DeploymentID,
		&i.RolledBackDeploymentID,
		&i.Domain,
		&i.Type,
		&i.Sticky,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
