// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: domain_challenge_update_expires_at.sql

package db

import (
	"context"
	"database/sql"
)

const updateDomainChallengeExpiresAt = `-- name: UpdateDomainChallengeExpiresAt :exec
UPDATE domain_challenges SET expires_at = ? WHERE domain_id = ?
`

type UpdateDomainChallengeExpiresAtParams struct {
	ExpiresAt sql.NullInt64 `db:"expires_at"`
	DomainID  string        `db:"domain_id"`
}

// UpdateDomainChallengeExpiresAt
//
//	UPDATE domain_challenges SET expires_at = ? WHERE domain_id = ?
func (q *Queries) UpdateDomainChallengeExpiresAt(ctx context.Context, db DBTX, arg UpdateDomainChallengeExpiresAtParams) error {
	_, err := db.ExecContext(ctx, updateDomainChallengeExpiresAt, arg.ExpiresAt, arg.DomainID)
	return err
}
