// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: gateways_find_by_environment_id.sql

package db

import (
	"context"
)

const findGatewaysByEnvironmentID = `-- name: FindGatewaysByEnvironmentID :many
SELECT id, workspace_id, environment_id, k8s_service_name, region, image, health, replicas FROM gateways WHERE environment_id = ?
`

// FindGatewaysByEnvironmentID
//
//	SELECT id, workspace_id, environment_id, k8s_service_name, region, image, health, replicas FROM gateways WHERE environment_id = ?
func (q *Queries) FindGatewaysByEnvironmentID(ctx context.Context, db DBTX, environmentID string) ([]Gateway, error) {
	rows, err := db.QueryContext(ctx, findGatewaysByEnvironmentID, environmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Gateway
	for rows.Next() {
		var i Gateway
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.EnvironmentID,
			&i.K8sServiceName,
			&i.Region,
			&i.Image,
			&i.Health,
			&i.Replicas,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
