// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: gateway_insert.sql

package db

import (
	"context"
)

const insertGateway = `-- name: InsertGateway :exec
INSERT INTO gateways (
id,
workspace_id,
k8s_service_name,
region,
image,
health,
replicas

)
VALUES (
?,
?,
?,
?,
?,
?,
?

)
`

type InsertGatewayParams struct {
	ID             string             `db:"id"`
	WorkspaceID    string             `db:"workspace_id"`
	K8sServiceName string             `db:"k8s_service_name"`
	Region         string             `db:"region"`
	Image          string             `db:"image"`
	Health         NullGatewaysHealth `db:"health"`
	Replicas       int32              `db:"replicas"`
}

// InsertGateway
//
//	INSERT INTO gateways (
//	id,
//	workspace_id,
//	k8s_service_name,
//	region,
//	image,
//	health,
//	replicas
//
//	)
//	VALUES (
//	?,
//	?,
//	?,
//	?,
//	?,
//	?,
//	?
//
//	)
func (q *Queries) InsertGateway(ctx context.Context, db DBTX, arg InsertGatewayParams) error {
	_, err := db.ExecContext(ctx, insertGateway,
		arg.ID,
		arg.WorkspaceID,
		arg.K8sServiceName,
		arg.Region,
		arg.Image,
		arg.Health,
		arg.Replicas,
	)
	return err
}
