// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: ingress_route_insert.sql

package db

import (
	"context"
	"database/sql"
)

const insertFrontlineRoute = `-- name: InsertFrontlineRoute :exec
INSERT INTO frontline_routes (
    id,
    project_id,
    deployment_id,
    environment_id,
    hostname,
    sticky,
    created_at,
    updated_at
)
VALUES (
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?
)
`

type InsertFrontlineRouteParams struct {
	ID            string                `db:"id"`
	ProjectID     string                `db:"project_id"`
	DeploymentID  string                `db:"deployment_id"`
	EnvironmentID string                `db:"environment_id"`
	Hostname      string                `db:"hostname"`
	Sticky        FrontlineRoutesSticky `db:"sticky"`
	CreatedAt     int64                 `db:"created_at"`
	UpdatedAt     sql.NullInt64         `db:"updated_at"`
}

// InsertFrontlineRoute
//
//	INSERT INTO frontline_routes (
//	    id,
//	    project_id,
//	    deployment_id,
//	    environment_id,
//	    hostname,
//	    sticky,
//	    created_at,
//	    updated_at
//	)
//	VALUES (
//	    ?,
//	    ?,
//	    ?,
//	    ?,
//	    ?,
//	    ?,
//	    ?,
//	    ?
//	)
func (q *Queries) InsertFrontlineRoute(ctx context.Context, db DBTX, arg InsertFrontlineRouteParams) error {
	_, err := db.ExecContext(ctx, insertFrontlineRoute,
		arg.ID,
		arg.ProjectID,
		arg.DeploymentID,
		arg.EnvironmentID,
		arg.Hostname,
		arg.Sticky,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}
