// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: instance_upsert.sql

package db

import (
	"context"
)

const upsertInstance = `-- name: UpsertInstance :exec
INSERT INTO instances (
	id,
	deployment_id,
	workspace_id,
	project_id,
	region,
	address,
	cpu_millicores,
	memory_mb,
	status
)
VALUES (
	?,
	?,
	?,
	?,
	?,
	?,
	?,
	?,
	?
)
ON DUPLICATE KEY UPDATE
	address = ?,
	cpu_millicores = ?,
	memory_mb = ?,
	status = ?
`

type UpsertInstanceParams struct {
	ID            string          `db:"id"`
	DeploymentID  string          `db:"deployment_id"`
	WorkspaceID   string          `db:"workspace_id"`
	ProjectID     string          `db:"project_id"`
	Region        string          `db:"region"`
	Address       string          `db:"address"`
	CpuMillicores int32           `db:"cpu_millicores"`
	MemoryMb      int32           `db:"memory_mb"`
	Status        InstancesStatus `db:"status"`
}

// UpsertInstance
//
//	INSERT INTO instances (
//		id,
//		deployment_id,
//		workspace_id,
//		project_id,
//		region,
//		address,
//		cpu_millicores,
//		memory_mb,
//		status
//	)
//	VALUES (
//		?,
//		?,
//		?,
//		?,
//		?,
//		?,
//		?,
//		?,
//		?
//	)
//	ON DUPLICATE KEY UPDATE
//		address = ?,
//		cpu_millicores = ?,
//		memory_mb = ?,
//		status = ?
func (q *Queries) UpsertInstance(ctx context.Context, db DBTX, arg UpsertInstanceParams) error {
	_, err := db.ExecContext(ctx, upsertInstance,
		arg.ID,
		arg.DeploymentID,
		arg.WorkspaceID,
		arg.ProjectID,
		arg.Region,
		arg.Address,
		arg.CpuMillicores,
		arg.MemoryMb,
		arg.Status,
		arg.Address,
		arg.CpuMillicores,
		arg.MemoryMb,
		arg.Status,
	)
	return err
}
