// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: key_update_hash_and_migration.sql

package db

import (
	"context"
	"database/sql"
)

const updateKeyHashAndMigration = `-- name: UpdateKeyHashAndMigration :exec
UPDATE ` + "`" + `keys` + "`" + `
SET 
    hash = ?,
    pending_migration_id = ?,
    updated_at_m = ?
WHERE id = ?
`

type UpdateKeyHashAndMigrationParams struct {
	Hash               string         `db:"hash"`
	PendingMigrationID sql.NullString `db:"pending_migration_id"`
	UpdatedAtM         sql.NullInt64  `db:"updated_at_m"`
	ID                 string         `db:"id"`
}

// UpdateKeyHashAndMigration
//
//	UPDATE `keys`
//	SET
//	    hash = ?,
//	    pending_migration_id = ?,
//	    updated_at_m = ?
//	WHERE id = ?
func (q *Queries) UpdateKeyHashAndMigration(ctx context.Context, db DBTX, arg UpdateKeyHashAndMigrationParams) error {
	_, err := db.ExecContext(ctx, updateKeyHashAndMigration,
		arg.Hash,
		arg.PendingMigrationID,
		arg.UpdatedAtM,
		arg.ID,
	)
	return err
}
