// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: key_migration_find_by_id.sql

package db

import (
	"context"
)

const findKeyMigrationByID = `-- name: FindKeyMigrationByID :one
SELECT
    id,
    workspace_id,
    algorithm
FROM key_migrations
WHERE id = ? and workspace_id = ?
`

type FindKeyMigrationByIDParams struct {
	ID          string `db:"id"`
	WorkspaceID string `db:"workspace_id"`
}

// FindKeyMigrationByID
//
//	SELECT
//	    id,
//	    workspace_id,
//	    algorithm
//	FROM key_migrations
//	WHERE id = ? and workspace_id = ?
func (q *Queries) FindKeyMigrationByID(ctx context.Context, db DBTX, arg FindKeyMigrationByIDParams) (KeyMigration, error) {
	row := db.QueryRowContext(ctx, findKeyMigrationByID, arg.ID, arg.WorkspaceID)
	var i KeyMigration
	err := row.Scan(&i.ID, &i.WorkspaceID, &i.Algorithm)
	return i, err
}
