// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: keyring_update_key_encryption.sql

package db

import (
	"context"
)

const updateKeyringKeyEncryption = `-- name: UpdateKeyringKeyEncryption :exec
UPDATE ` + "`" + `key_auth` + "`" + ` SET store_encrypted_keys = ? WHERE id = ?
`

type UpdateKeyringKeyEncryptionParams struct {
	StoreEncryptedKeys bool   `db:"store_encrypted_keys"`
	ID                 string `db:"id"`
}

// UpdateKeyringKeyEncryption
//
//	UPDATE `key_auth` SET store_encrypted_keys = ? WHERE id = ?
func (q *Queries) UpdateKeyringKeyEncryption(ctx context.Context, db DBTX, arg UpdateKeyringKeyEncryptionParams) error {
	_, err := db.ExecContext(ctx, updateKeyringKeyEncryption, arg.StoreEncryptedKeys, arg.ID)
	return err
}
