// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: permissions_find_role_by_id.sql

package db

import (
	"context"
)

const findRoleById = `-- name: FindRoleById :one
SELECT id, workspace_id, name, description, created_at_m, updated_at_m
FROM roles
WHERE id = ?
LIMIT 1
`

// Finds a role record by its ID
// Returns: The role record if found
//
//	SELECT id, workspace_id, name, description, created_at_m, updated_at_m
//	FROM roles
//	WHERE id = ?
//	LIMIT 1
func (q *Queries) FindRoleById(ctx context.Context, db DBTX, roleID string) (Role, error) {
	row := db.QueryRowContext(ctx, findRoleById, roleID)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.Description,
		&i.CreatedAtM,
		&i.UpdatedAtM,
	)
	return i, err
}
