// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: permissions_delete_role_permissions_by_permission_id.sql

package db

import (
	"context"
)

const deleteRolePermissionsByPermissionId = `-- name: DeleteRolePermissionsByPermissionId :exec
DELETE FROM roles_permissions
WHERE permission_id = ?
`

// DeleteRolePermissionsByPermissionId
//
//	DELETE FROM roles_permissions
//	WHERE permission_id = ?
func (q *Queries) DeleteRolePermissionsByPermissionId(ctx context.Context, db DBTX, permissionID string) error {
	_, err := db.ExecContext(ctx, deleteRolePermissionsByPermissionId, permissionID)
	return err
}
