// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: project_update_active_deployment_id.sql

package db

import (
	"context"
	"database/sql"
)

const updateProjectActiveDeploymentId = `-- name: UpdateProjectActiveDeploymentId :exec
UPDATE projects
SET active_deployment_id = ?, updated_at = ?
WHERE id = ?
`

type UpdateProjectActiveDeploymentIdParams struct {
	ActiveDeploymentID sql.NullString `db:"active_deployment_id"`
	UpdatedAt          sql.NullInt64  `db:"updated_at"`
	ID                 string         `db:"id"`
}

// UpdateProjectActiveDeploymentId
//
//	UPDATE projects
//	SET active_deployment_id = ?, updated_at = ?
//	WHERE id = ?
func (q *Queries) UpdateProjectActiveDeploymentId(ctx context.Context, db DBTX, arg UpdateProjectActiveDeploymentIdParams) error {
	_, err := db.ExecContext(ctx, updateProjectActiveDeploymentId, arg.ActiveDeploymentID, arg.UpdatedAt, arg.ID)
	return err
}
