// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: sentinel_find_by_id.sql

package db

import (
	"context"
)

const findSentinelByID = `-- name: FindSentinelByID :one
SELECT id, workspace_id, project_id, environment_id, k8s_namespace, k8s_name, k8s_address, region, image, desired_state, health, desired_replicas, replicas, cpu_millicores, memory_mib, created_at, updated_at FROM sentinels
WHERE id = ? LIMIT 1
`

// FindSentinelByID
//
//	SELECT id, workspace_id, project_id, environment_id, k8s_namespace, k8s_name, k8s_address, region, image, desired_state, health, desired_replicas, replicas, cpu_millicores, memory_mib, created_at, updated_at FROM sentinels
//	WHERE id = ? LIMIT 1
func (q *Queries) FindSentinelByID(ctx context.Context, db DBTX, id string) (Sentinel, error) {
	row := db.QueryRowContext(ctx, findSentinelByID, id)
	var i Sentinel
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ProjectID,
		&i.EnvironmentID,
		&i.K8sNamespace,
		&i.K8sName,
		&i.K8sAddress,
		&i.Region,
		&i.Image,
		&i.DesiredState,
		&i.Health,
		&i.DesiredReplicas,
		&i.Replicas,
		&i.CpuMillicores,
		&i.MemoryMib,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
