// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: version_insert.sql

package db

import (
	"context"
	"database/sql"
	"encoding/json"
)

const insertVersion = `-- name: InsertVersion :exec
INSERT INTO ` + "`" + `versions` + "`" + ` (
    id,
    workspace_id,
    project_id,
    environment_id,
    branch_id,
    build_id,
    rootfs_image_id,
    git_commit_sha,
    git_branch,
    config_snapshot,
    topology_config,
    status,
    created_at_m,
    updated_at_m
)
VALUES (
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?
)
`

type InsertVersionParams struct {
	ID             string          `db:"id"`
	WorkspaceID    string          `db:"workspace_id"`
	ProjectID      string          `db:"project_id"`
	EnvironmentID  string          `db:"environment_id"`
	BranchID       sql.NullString  `db:"branch_id"`
	BuildID        sql.NullString  `db:"build_id"`
	RootfsImageID  string          `db:"rootfs_image_id"`
	GitCommitSha   sql.NullString  `db:"git_commit_sha"`
	GitBranch      sql.NullString  `db:"git_branch"`
	ConfigSnapshot json.RawMessage `db:"config_snapshot"`
	TopologyConfig json.RawMessage `db:"topology_config"`
	Status         VersionsStatus  `db:"status"`
	CreatedAtM     int64           `db:"created_at_m"`
	UpdatedAtM     sql.NullInt64   `db:"updated_at_m"`
}

// InsertVersion
//
//	INSERT INTO `versions` (
//	    id,
//	    workspace_id,
//	    project_id,
//	    environment_id,
//	    branch_id,
//	    build_id,
//	    rootfs_image_id,
//	    git_commit_sha,
//	    git_branch,
//	    config_snapshot,
//	    topology_config,
//	    status,
//	    created_at_m,
//	    updated_at_m
//	)
//	VALUES (
//	    ?,
//	    ?,
//	    ?,
//	    ?,
//	    ?,
//	    ?,
//	    ?,
//	    ?,
//	    ?,
//	    ?,
//	    ?,
//	    ?,
//	    ?,
//	    ?
//	)
func (q *Queries) InsertVersion(ctx context.Context, db DBTX, arg InsertVersionParams) error {
	_, err := db.ExecContext(ctx, insertVersion,
		arg.ID,
		arg.WorkspaceID,
		arg.ProjectID,
		arg.EnvironmentID,
		arg.BranchID,
		arg.BuildID,
		arg.RootfsImageID,
		arg.GitCommitSha,
		arg.GitBranch,
		arg.ConfigSnapshot,
		arg.TopologyConfig,
		arg.Status,
		arg.CreatedAtM,
		arg.UpdatedAtM,
	)
	return err
}
