#!/usr/bin/env bash
#MISE description="Clean up dangling test containers"
set -euo pipefail

docker rm -vf $(docker ps -q -f label="owner=testutil-containers") >/dev/null 2>&1 || true
docker rm -vf $(docker ps -q -f label="owner=dockertest") >/dev/null 2>&1 || true
