#!/usr/bin/env bash
#MISE description="Run local development setup for dashboard"
#MISE depends=["build","oci-load"]
set -euo pipefail

docker compose -f web/apps/dashboard/dev/docker-compose.yaml up -d --wait
bin/unkey dev seed local
pnpm --dir=web/apps/dashboard dev
