#!/usr/bin/env bash
#MISE description="Start dev environment"
#MISE depends=["install-web"]
#MISE raw=true
set -euo pipefail

bash ./dev/start-cluster.sh ./dev/cluster.yaml
exec tilt up -f ./dev/Tiltfile -- "$@"
