#!/usr/bin/env bash
#MISE description="Start dev environment"
#MISE depends=["install-web", "oci-load"]
#MISE raw=true
set -euo pipefail

ctlptl apply -f ./dev/cluster.yaml
minikube addons enable metrics-server
tilt up -f ./dev/Tiltfile
