#!/usr/bin/env bash
#MISE description="Generate code from protobuf and other sources (NOT eBPF, see generate-bpf)"
#MISE depends=["generate-sql"]
set -euo pipefail

GO_ROOT="$(mise where go)"
GO_BIN="${GO_ROOT}/bin/go"
export GOROOT="${GO_ROOT}"
export PATH="${GO_ROOT}/bin:${PATH}"

rm -rf ./gen || true
rm ./pkg/db/*_generated.go || true
"${GO_BIN}" generate ./...
"${GO_BIN}" run ./tools/exportoneof ./gen/proto
bazel run //:gazelle
"${GO_BIN}" fmt ./...
pnpm --dir=web fmt
