#!/usr/bin/env bash
#MISE description="Install Homebrew tools if they don't exist"
set -euo pipefail

command -v tilt >/dev/null 2>&1 || { echo "Installing tilt..."; brew install tilt; }
command -v ctlptl >/dev/null 2>&1 || { echo "Installing ctlptl..."; brew install ctlptl; }
command -v minikube >/dev/null 2>&1 || { echo "Installing minikube..."; brew install minikube; }
command -v bazel >/dev/null 2>&1 || { echo "Installing bazel..."; brew install bazelisk; }
command -v dprint >/dev/null 2>&1 || { echo "Installing dprint..."; brew install dprint; }
command -v ngrok >/dev/null 2>&1 || { echo "Installing ngrok..."; brew install ngrok; }
