#!/usr/bin/env bash
#MISE description="Run the Bazel test suite"
#MISE depends=["oci-load"]


bazel test //...

docker rm -vf $(docker ps -q -f label="owner=testutil-containers") >/dev/null 2>&1 || true
