// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: alert_event_find_open_by_group.sql

package db

import (
	"context"
)

const findOpenAlertEventsByGroup = `-- name: FindOpenAlertEventsByGroup :many
SELECT
    pk,
    id,
    workspace_id,
    project_id,
    app_id,
    environment_id,
    deployment_id,
    metric,
    status,
    fired_at,
    last_seen_at,
    resolved_at,
    resolved_by,
    resolution_message,
    observed_value,
    baseline_mean,
    baseline_stddev,
    threshold_sigma,
    window_start,
    window_end,
    created_at,
    updated_at
FROM alert_events
WHERE workspace_id = ?
  AND app_id = ?
  AND environment_id = ?
  AND status = 'open'
ORDER BY metric ASC
`

type FindOpenAlertEventsByGroupParams struct {
	WorkspaceID   string `db:"workspace_id"`
	AppID         string `db:"app_id"`
	EnvironmentID string `db:"environment_id"`
}

// FindOpenAlertEventsByGroup
//
//	SELECT
//	    pk,
//	    id,
//	    workspace_id,
//	    project_id,
//	    app_id,
//	    environment_id,
//	    deployment_id,
//	    metric,
//	    status,
//	    fired_at,
//	    last_seen_at,
//	    resolved_at,
//	    resolved_by,
//	    resolution_message,
//	    observed_value,
//	    baseline_mean,
//	    baseline_stddev,
//	    threshold_sigma,
//	    window_start,
//	    window_end,
//	    created_at,
//	    updated_at
//	FROM alert_events
//	WHERE workspace_id = ?
//	  AND app_id = ?
//	  AND environment_id = ?
//	  AND status = 'open'
//	ORDER BY metric ASC
func (q *Queries) FindOpenAlertEventsByGroup(ctx context.Context, arg FindOpenAlertEventsByGroupParams) ([]AlertEvent, error) {
	rows, err := q.db.QueryContext(ctx, findOpenAlertEventsByGroup, arg.WorkspaceID, arg.AppID, arg.EnvironmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AlertEvent
	for rows.Next() {
		var i AlertEvent
		if err := rows.Scan(
			&i.Pk,
			&i.ID,
			&i.WorkspaceID,
			&i.ProjectID,
			&i.AppID,
			&i.EnvironmentID,
			&i.DeploymentID,
			&i.Metric,
			&i.Status,
			&i.FiredAt,
			&i.LastSeenAt,
			&i.ResolvedAt,
			&i.ResolvedBy,
			&i.ResolutionMessage,
			&i.ObservedValue,
			&i.BaselineMean,
			&i.BaselineStddev,
			&i.ThresholdSigma,
			&i.WindowStart,
			&i.WindowEnd,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
