// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: app_runtime_settings_count_by_workspace_id.sql

package db

import (
	"context"
)

const countAppRuntimeSettingsByWorkspaceId = `-- name: CountAppRuntimeSettingsByWorkspaceId :one
SELECT COUNT(*)
FROM ` + "`" + `app_runtime_settings` + "`" + `
WHERE workspace_id = ?
`

// CountAppRuntimeSettingsByWorkspaceId counts a workspace's runtime settings rows. Only tests use this query.
//
//	SELECT COUNT(*)
//	FROM `app_runtime_settings`
//	WHERE workspace_id = ?
func (q *Queries) CountAppRuntimeSettingsByWorkspaceId(ctx context.Context, workspaceID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAppRuntimeSettingsByWorkspaceId, workspaceID)
	var count int64
	err := row.Scan(&count)
	return count, err
}
