// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: app_docker_source_upsert.sql

package db

import (
	"context"
	"database/sql"
)

const upsertAppDockerSource = `-- name: UpsertAppDockerSource :exec
INSERT INTO app_docker_sources (
    workspace_id,
    app_id,
    image,
    created_at,
    updated_at
) VALUES (
    ?,
    ?,
    ?,
    ?,
    ?
)
ON DUPLICATE KEY UPDATE
    image = VALUES(image),
    updated_at = VALUES(updated_at)
`

type UpsertAppDockerSourceParams struct {
	WorkspaceID string        `db:"workspace_id"`
	AppID       string        `db:"app_id"`
	Image       string        `db:"image"`
	CreatedAt   int64         `db:"created_at"`
	UpdatedAt   sql.NullInt64 `db:"updated_at"`
}

// UpsertAppDockerSource
//
//	INSERT INTO app_docker_sources (
//	    workspace_id,
//	    app_id,
//	    image,
//	    created_at,
//	    updated_at
//	) VALUES (
//	    ?,
//	    ?,
//	    ?,
//	    ?,
//	    ?
//	)
//	ON DUPLICATE KEY UPDATE
//	    image = VALUES(image),
//	    updated_at = VALUES(updated_at)
func (q *Queries) UpsertAppDockerSource(ctx context.Context, arg UpsertAppDockerSourceParams) error {
	_, err := q.db.ExecContext(ctx, upsertAppDockerSource,
		arg.WorkspaceID,
		arg.AppID,
		arg.Image,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}
