// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: app_build_settings_count_by_workspace_id.sql

package db

import (
	"context"
)

const countAppBuildSettingsByWorkspaceId = `-- name: CountAppBuildSettingsByWorkspaceId :one
SELECT COUNT(*)
FROM ` + "`" + `app_build_settings` + "`" + `
WHERE workspace_id = ?
`

// CountAppBuildSettingsByWorkspaceId counts a workspace's build settings rows. Only tests use this query.
//
//	SELECT COUNT(*)
//	FROM `app_build_settings`
//	WHERE workspace_id = ?
func (q *Queries) CountAppBuildSettingsByWorkspaceId(ctx context.Context, workspaceID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAppBuildSettingsByWorkspaceId, workspaceID)
	var count int64
	err := row.Scan(&count)
	return count, err
}
