// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: billing_subscription_insert.sql

package db

import (
	"context"
)

const insertBillingSubscription = `-- name: InsertBillingSubscription :exec
INSERT INTO ` + "`" + `billing_subscriptions` + "`" + ` (
    workspace_id,
    product,
    stripe_subscription_id
) VALUES (
    ?,
    ?,
    ?
)
`

type InsertBillingSubscriptionParams struct {
	WorkspaceID          string                      `db:"workspace_id"`
	Product              BillingSubscriptionsProduct `db:"product"`
	StripeSubscriptionID string                      `db:"stripe_subscription_id"`
}

// InsertBillingSubscription records a workspace's Stripe subscription for one
// product. Only tests use this query.
//
//	INSERT INTO `billing_subscriptions` (
//	    workspace_id,
//	    product,
//	    stripe_subscription_id
//	) VALUES (
//	    ?,
//	    ?,
//	    ?
//	)
func (q *Queries) InsertBillingSubscription(ctx context.Context, arg InsertBillingSubscriptionParams) error {
	_, err := q.db.ExecContext(ctx, insertBillingSubscription, arg.WorkspaceID, arg.Product, arg.StripeSubscriptionID)
	return err
}
