// Code generated by sqlc bulk insert plugin. DO NOT EDIT.

package db

import (
	"context"
	"fmt"
	"strings"
)

// bulkInsertAppBinding is the base query for bulk insert
const bulkInsertAppBinding = `INSERT INTO app_bindings ( id, workspace_id, project_id, app_id, environment_id, resource_type, resource_id, name, selection_mode, target_environment_id, target_deployment_id, created_at ) VALUES %s`

// InsertAppBindings performs bulk insert in a single query

func (q *BulkQueries) InsertAppBindings(ctx context.Context, args []InsertAppBindingParams) error {

	if len(args) == 0 {
		return nil
	}

	// Build the bulk insert query
	valueClauses := make([]string, len(args))
	for i := range args {
		valueClauses[i] = "( ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ? )"
	}

	bulkQuery := fmt.Sprintf(bulkInsertAppBinding, strings.Join(valueClauses, ", "))

	// Collect all arguments
	var allArgs []any
	for _, arg := range args {
		allArgs = append(allArgs, arg.ID)
		allArgs = append(allArgs, arg.WorkspaceID)
		allArgs = append(allArgs, arg.ProjectID)
		allArgs = append(allArgs, arg.AppID)
		allArgs = append(allArgs, arg.EnvironmentID)
		allArgs = append(allArgs, arg.ResourceType)
		allArgs = append(allArgs, arg.ResourceID)
		allArgs = append(allArgs, arg.Name)
		allArgs = append(allArgs, arg.SelectionMode)
		allArgs = append(allArgs, arg.TargetEnvironmentID)
		allArgs = append(allArgs, arg.TargetDeploymentID)
		allArgs = append(allArgs, arg.CreatedAt)
	}

	// Execute the bulk insert
	_, err := q.db.ExecContext(ctx, bulkQuery, allArgs...)
	return err
}
