// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: certificate_health.sql

package db

import (
	"context"
)

const getCertificateHealth = `-- name: GetCertificateHealth :one
SELECT
    COUNT(CASE WHEN dc.status = 'failed' THEN 1 END) AS failed_challenges,
    CAST(COALESCE(MIN(CASE WHEN c.id IS NOT NULL AND dc.expires_at > 0 THEN dc.expires_at END), 0) AS SIGNED) AS earliest_expiry
FROM acme_challenges dc
JOIN custom_domains d ON dc.domain_id = d.id
LEFT JOIN certificates c ON c.hostname = d.domain
`

type GetCertificateHealthRow struct {
	FailedChallenges int64 `db:"failed_challenges"`
	EarliestExpiry   int64 `db:"earliest_expiry"`
}

// GetCertificateHealth
//
//	SELECT
//	    COUNT(CASE WHEN dc.status = 'failed' THEN 1 END) AS failed_challenges,
//	    CAST(COALESCE(MIN(CASE WHEN c.id IS NOT NULL AND dc.expires_at > 0 THEN dc.expires_at END), 0) AS SIGNED) AS earliest_expiry
//	FROM acme_challenges dc
//	JOIN custom_domains d ON dc.domain_id = d.id
//	LEFT JOIN certificates c ON c.hostname = d.domain
func (q *Queries) GetCertificateHealth(ctx context.Context) (GetCertificateHealthRow, error) {
	row := q.db.QueryRowContext(ctx, getCertificateHealth)
	var i GetCertificateHealthRow
	err := row.Scan(&i.FailedChallenges, &i.EarliestExpiry)
	return i, err
}
