// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: clickhouse_workspace_settings_update_provisioning_state.sql

package db

import (
	"context"
	"database/sql"
)

const updateClickhouseWorkspaceSettingsProvisioningState = `-- name: UpdateClickhouseWorkspaceSettingsProvisioningState :exec
UPDATE ` + "`" + `clickhouse_workspace_settings` + "`" + `
SET
    provisioning_state = ?,
    updated_at = ?
WHERE workspace_id = ?
`

type UpdateClickhouseWorkspaceSettingsProvisioningStateParams struct {
	ProvisioningState string        `db:"provisioning_state"`
	UpdatedAt         sql.NullInt64 `db:"updated_at"`
	WorkspaceID       string        `db:"workspace_id"`
}

// UpdateClickhouseWorkspaceSettingsProvisioningState
//
//	UPDATE `clickhouse_workspace_settings`
//	SET
//	    provisioning_state = ?,
//	    updated_at = ?
//	WHERE workspace_id = ?
func (q *Queries) UpdateClickhouseWorkspaceSettingsProvisioningState(ctx context.Context, arg UpdateClickhouseWorkspaceSettingsProvisioningStateParams) error {
	_, err := q.db.ExecContext(ctx, updateClickhouseWorkspaceSettingsProvisioningState, arg.ProvisioningState, arg.UpdatedAt, arg.WorkspaceID)
	return err
}
