// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: custom_domain_find_by_domain_or_wildcard.sql

package db

import (
	"context"
)

const findCustomDomainByDomainOrWildcard = `-- name: FindCustomDomainByDomainOrWildcard :one
SELECT custom_domains.pk, custom_domains.id, custom_domains.workspace_id, custom_domains.project_id, custom_domains.app_id, custom_domains.environment_id, custom_domains.domain, custom_domains.challenge_type, custom_domains.verification_status, custom_domains.verification_token, custom_domains.ownership_verified, custom_domains.cname_verified, custom_domains.target_cname, custom_domains.last_checked_at, custom_domains.check_attempts, custom_domains.verification_error, custom_domains.domain_connect_provider, custom_domains.domain_connect_url, custom_domains.invocation_id, custom_domains.created_at, custom_domains.updated_at FROM custom_domains
WHERE domain IN (?, ?)
ORDER BY
    CASE WHEN domain = ? THEN 0 ELSE 1 END
LIMIT 1
`

type FindCustomDomainByDomainOrWildcardParams struct {
	Domain   string `db:"domain"`
	Domain_2 string `db:"domain_2"`
	Domain_3 string `db:"domain_3"`
}

// FindCustomDomainByDomainOrWildcard
//
//	SELECT custom_domains.pk, custom_domains.id, custom_domains.workspace_id, custom_domains.project_id, custom_domains.app_id, custom_domains.environment_id, custom_domains.domain, custom_domains.challenge_type, custom_domains.verification_status, custom_domains.verification_token, custom_domains.ownership_verified, custom_domains.cname_verified, custom_domains.target_cname, custom_domains.last_checked_at, custom_domains.check_attempts, custom_domains.verification_error, custom_domains.domain_connect_provider, custom_domains.domain_connect_url, custom_domains.invocation_id, custom_domains.created_at, custom_domains.updated_at FROM custom_domains
//	WHERE domain IN (?, ?)
//	ORDER BY
//	    CASE WHEN domain = ? THEN 0 ELSE 1 END
//	LIMIT 1
func (q *Queries) FindCustomDomainByDomainOrWildcard(ctx context.Context, arg FindCustomDomainByDomainOrWildcardParams) (CustomDomain, error) {
	row := q.db.QueryRowContext(ctx, findCustomDomainByDomainOrWildcard, arg.Domain, arg.Domain_2, arg.Domain_3)
	var i CustomDomain
	err := row.Scan(
		&i.Pk,
		&i.ID,
		&i.WorkspaceID,
		&i.ProjectID,
		&i.AppID,
		&i.EnvironmentID,
		&i.Domain,
		&i.ChallengeType,
		&i.VerificationStatus,
		&i.VerificationToken,
		&i.OwnershipVerified,
		&i.CnameVerified,
		&i.TargetCname,
		&i.LastCheckedAt,
		&i.CheckAttempts,
		&i.VerificationError,
		&i.DomainConnectProvider,
		&i.DomainConnectUrl,
		&i.InvocationID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
