// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: deployment_update_image.sql

package db

import (
	"context"
	"database/sql"
)

const updateDeploymentImage = `-- name: UpdateDeploymentImage :exec
UPDATE deployments
SET image_resolved = ?,
    updated_at = ?
WHERE id = ?
`

type UpdateDeploymentImageParams struct {
	ImageResolved sql.NullString `db:"image_resolved"`
	UpdatedAt     sql.NullInt64  `db:"updated_at"`
	ID            string         `db:"id"`
}

// UpdateDeploymentImage
//
//	UPDATE deployments
//	SET image_resolved = ?,
//	    updated_at = ?
//	WHERE id = ?
func (q *Queries) UpdateDeploymentImage(ctx context.Context, arg UpdateDeploymentImageParams) error {
	_, err := q.db.ExecContext(ctx, updateDeploymentImage, arg.ImageResolved, arg.UpdatedAt, arg.ID)
	return err
}
