// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: deployment_update_status_if_active.sql

package db

import (
	"context"
	"database/sql"
	"strings"
)

const updateDeploymentStatusIfActive = `-- name: UpdateDeploymentStatusIfActive :exec
UPDATE deployments
SET status = ?, updated_at = ?
WHERE id = ?
  AND status NOT IN (/*SLICE:terminal_statuses*/?)
`

type UpdateDeploymentStatusIfActiveParams struct {
	Status           DeploymentsStatus   `db:"status"`
	UpdatedAt        sql.NullInt64       `db:"updated_at"`
	ID               string              `db:"id"`
	TerminalStatuses []DeploymentsStatus `db:"terminal_statuses"`
}

// Transition a deployment's status only when its current status is still
// "active" (non-terminal). Prevents the Deploy handler's compensation
// stack from overwriting a status that was set intentionally by the dedup
// path (e.g. superseded) or by a successful completion (ready). Callers
// pass db.TerminalDeploymentStatuses so the terminal set has a single
// source of truth.
//
//	UPDATE deployments
//	SET status = ?, updated_at = ?
//	WHERE id = ?
//	  AND status NOT IN (/*SLICE:terminal_statuses*/?)
func (q *Queries) UpdateDeploymentStatusIfActive(ctx context.Context, arg UpdateDeploymentStatusIfActiveParams) error {
	query := updateDeploymentStatusIfActive
	var queryParams []interface{}
	queryParams = append(queryParams, arg.Status)
	queryParams = append(queryParams, arg.UpdatedAt)
	queryParams = append(queryParams, arg.ID)
	if len(arg.TerminalStatuses) > 0 {
		for _, v := range arg.TerminalStatuses {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:terminal_statuses*/?", strings.Repeat(",?", len(arg.TerminalStatuses))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:terminal_statuses*/?", "NULL", 1)
	}
	_, err := q.db.ExecContext(ctx, query, queryParams...)
	return err
}
