// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: deployment_count_active_by_ids.sql

package db

import (
	"context"
	"strings"
)

const countActiveDeploymentsByIds = `-- name: CountActiveDeploymentsByIds :one
SELECT COUNT(DISTINCT i.deployment_id) AS count
FROM instances i
WHERE i.deployment_id IN (/*SLICE:ids*/?)
`

// Counts how many of the given deployments still have live compute to drain.
// Teardown polls this until it returns 0. A deployment is draining only while it
// has instance rows; krane deletes those rows when it tears the pods down (see
// DeleteDeploymentInstances), so their absence is the drain signal. A deployment
// that never had instances (pending/building/awaiting_approval, all born
// desired_state='running' and swept into the teardown set) counts zero here
// rather than waiting out the grace window for a krane Delete that never comes.
//
//	SELECT COUNT(DISTINCT i.deployment_id) AS count
//	FROM instances i
//	WHERE i.deployment_id IN (/*SLICE:ids*/?)
func (q *Queries) CountActiveDeploymentsByIds(ctx context.Context, ids []string) (int64, error) {
	query := countActiveDeploymentsByIds
	var queryParams []interface{}
	if len(ids) > 0 {
		for _, v := range ids {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:ids*/?", strings.Repeat(",?", len(ids))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:ids*/?", "NULL", 1)
	}
	row := q.db.QueryRowContext(ctx, query, queryParams...)
	var count int64
	err := row.Scan(&count)
	return count, err
}
