// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: deployment_topology_confirm_removal.sql

package db

import (
	"context"
)

const confirmDeploymentTopologyRemoval = `-- name: ConfirmDeploymentTopologyRemoval :execrows
DELETE dt FROM deployment_topology dt
LEFT JOIN deployments d ON d.id = dt.deployment_id
LEFT JOIN projects p ON p.id = d.project_id
LEFT JOIN apps a ON a.id = d.app_id
LEFT JOIN environments e ON e.id = d.environment_id
WHERE dt.deployment_id = ?
  AND dt.region_id = ?
  AND (d.id IS NULL OR p.id IS NULL OR a.id IS NULL OR e.id IS NULL
    OR p.deleting_at IS NOT NULL OR a.deleting_at IS NOT NULL OR e.deleting_at IS NOT NULL)
`

type ConfirmDeploymentTopologyRemovalParams struct {
	DeploymentID string `db:"deployment_id"`
	RegionID     string `db:"region_id"`
}

// ConfirmDeploymentTopologyRemoval
//
//	DELETE dt FROM deployment_topology dt
//	LEFT JOIN deployments d ON d.id = dt.deployment_id
//	LEFT JOIN projects p ON p.id = d.project_id
//	LEFT JOIN apps a ON a.id = d.app_id
//	LEFT JOIN environments e ON e.id = d.environment_id
//	WHERE dt.deployment_id = ?
//	  AND dt.region_id = ?
//	  AND (d.id IS NULL OR p.id IS NULL OR a.id IS NULL OR e.id IS NULL
//	    OR p.deleting_at IS NOT NULL OR a.deleting_at IS NOT NULL OR e.deleting_at IS NOT NULL)
func (q *Queries) ConfirmDeploymentTopologyRemoval(ctx context.Context, arg ConfirmDeploymentTopologyRemovalParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, confirmDeploymentTopologyRemoval, arg.DeploymentID, arg.RegionID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
