// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: deployment_topology_stop_by_environment.sql

package db

import (
	"context"
	"database/sql"
)

const stopDeploymentTopologiesByEnvironment = `-- name: StopDeploymentTopologiesByEnvironment :exec
UPDATE deployment_topology dt
JOIN deployments d ON d.id = dt.deployment_id
SET dt.desired_status = 'stopped',
    dt.updated_at = GREATEST(COALESCE(dt.updated_at, 0) + 1, CAST(? AS SIGNED))
WHERE d.environment_id = ?
`

type StopDeploymentTopologiesByEnvironmentParams struct {
	UpdatedAt     sql.NullInt64 `db:"updated_at"`
	EnvironmentID string        `db:"environment_id"`
}

// StopDeploymentTopologiesByEnvironment
//
//	UPDATE deployment_topology dt
//	JOIN deployments d ON d.id = dt.deployment_id
//	SET dt.desired_status = 'stopped',
//	    dt.updated_at = GREATEST(COALESCE(dt.updated_at, 0) + 1, CAST(? AS SIGNED))
//	WHERE d.environment_id = ?
func (q *Queries) StopDeploymentTopologiesByEnvironment(ctx context.Context, arg StopDeploymentTopologiesByEnvironmentParams) error {
	_, err := q.db.ExecContext(ctx, stopDeploymentTopologiesByEnvironment, arg.UpdatedAt, arg.EnvironmentID)
	return err
}
