// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: environment_list_preview.sql

package db

import (
	"context"
	"database/sql"
)

const listPreviewEnvironments = `-- name: ListPreviewEnvironments :many
SELECT environments.pk, environments.id, environments.workspace_id, environments.project_id, environments.app_id, environments.slug, environments.description, environments.delete_protection, environments.created_at, environments.updated_at
FROM environments
WHERE kind = 'preview'
AND pk > ?
ORDER BY pk ASC
LIMIT ?
`

type ListPreviewEnvironmentsParams struct {
	PaginationCursor uint64 `db:"pagination_cursor"`
	Limit            int32  `db:"limit"`
}

type ListPreviewEnvironmentsRow struct {
	Pk               uint64        `db:"pk"`
	ID               string        `db:"id"`
	WorkspaceID      string        `db:"workspace_id"`
	ProjectID        string        `db:"project_id"`
	AppID            string        `db:"app_id"`
	Slug             string        `db:"slug"`
	Description      string        `db:"description"`
	DeleteProtection sql.NullBool  `db:"delete_protection"`
	CreatedAt        int64         `db:"created_at"`
	UpdatedAt        sql.NullInt64 `db:"updated_at"`
}

// ListPreviewEnvironments
//
//	SELECT environments.pk, environments.id, environments.workspace_id, environments.project_id, environments.app_id, environments.slug, environments.description, environments.delete_protection, environments.created_at, environments.updated_at
//	FROM environments
//	WHERE kind = 'preview'
//	AND pk > ?
//	ORDER BY pk ASC
//	LIMIT ?
func (q *Queries) ListPreviewEnvironments(ctx context.Context, arg ListPreviewEnvironmentsParams) ([]ListPreviewEnvironmentsRow, error) {
	rows, err := q.db.QueryContext(ctx, listPreviewEnvironments, arg.PaginationCursor, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPreviewEnvironmentsRow
	for rows.Next() {
		var i ListPreviewEnvironmentsRow
		if err := rows.Scan(
			&i.Pk,
			&i.ID,
			&i.WorkspaceID,
			&i.ProjectID,
			&i.AppID,
			&i.Slug,
			&i.Description,
			&i.DeleteProtection,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
