// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: instance_record_waiting.sql

package db

import (
	"context"
)

const recordInstanceWaiting = `-- name: RecordInstanceWaiting :exec
UPDATE instances
SET container_status = JSON_SET(
	container_status,
	'$.restartCount', CAST(? AS UNSIGNED),
	'$.statusObservedAt', CAST(? AS UNSIGNED),
	'$.waiting', JSON_OBJECT(
		'reason', ?,
		'message', ?
	)
)
WHERE k8s_name = ?
	AND region_id = ?
	AND COALESCE(CAST(JSON_VALUE(container_status, '$.statusObservedAt') AS UNSIGNED), 0) <= CAST(? AS UNSIGNED)
	AND CAST(JSON_VALUE(container_status, '$.restartCount') AS UNSIGNED) <= CAST(? AS UNSIGNED)
`

type RecordInstanceWaitingParams struct {
	RestartCount       int64       `db:"restart_count"`
	StatusObservedAt   int64       `db:"status_observed_at"`
	Reason             interface{} `db:"reason"`
	Message            interface{} `db:"message"`
	K8sName            string      `db:"k8s_name"`
	RegionID           string      `db:"region_id"`
	StatusObservedAt_2 int64       `db:"status_observed_at_2"`
	RestartCount_2     int64       `db:"restart_count_2"`
}

// RecordInstanceWaiting
//
//	UPDATE instances
//	SET container_status = JSON_SET(
//		container_status,
//		'$.restartCount', CAST(? AS UNSIGNED),
//		'$.statusObservedAt', CAST(? AS UNSIGNED),
//		'$.waiting', JSON_OBJECT(
//			'reason', ?,
//			'message', ?
//		)
//	)
//	WHERE k8s_name = ?
//		AND region_id = ?
//		AND COALESCE(CAST(JSON_VALUE(container_status, '$.statusObservedAt') AS UNSIGNED), 0) <= CAST(? AS UNSIGNED)
//		AND CAST(JSON_VALUE(container_status, '$.restartCount') AS UNSIGNED) <= CAST(? AS UNSIGNED)
func (q *Queries) RecordInstanceWaiting(ctx context.Context, arg RecordInstanceWaitingParams) error {
	_, err := q.db.ExecContext(ctx, recordInstanceWaiting,
		arg.RestartCount,
		arg.StatusObservedAt,
		arg.Reason,
		arg.Message,
		arg.K8sName,
		arg.RegionID,
		arg.StatusObservedAt_2,
		arg.RestartCount_2,
	)
	return err
}
