// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: limits_list_with_builds_concurrent_max_above.sql

package db

import (
	"context"
)

const listLimitsWithBuildsConcurrentMaxAbove = `-- name: ListLimitsWithBuildsConcurrentMaxAbove :many
SELECT workspace_id, builds_concurrent_max
FROM ` + "`" + `limits` + "`" + `
WHERE builds_concurrent_max > ?
ORDER BY workspace_id
`

type ListLimitsWithBuildsConcurrentMaxAboveRow struct {
	WorkspaceID         string `db:"workspace_id"`
	BuildsConcurrentMax uint16 `db:"builds_concurrent_max"`
}

// ListLimitsWithBuildsConcurrentMaxAbove
//
//	SELECT workspace_id, builds_concurrent_max
//	FROM `limits`
//	WHERE builds_concurrent_max > ?
//	ORDER BY workspace_id
func (q *Queries) ListLimitsWithBuildsConcurrentMaxAbove(ctx context.Context, buildsConcurrentMax uint16) ([]ListLimitsWithBuildsConcurrentMaxAboveRow, error) {
	rows, err := q.db.QueryContext(ctx, listLimitsWithBuildsConcurrentMaxAbove, buildsConcurrentMax)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListLimitsWithBuildsConcurrentMaxAboveRow
	for rows.Next() {
		var i ListLimitsWithBuildsConcurrentMaxAboveRow
		if err := rows.Scan(&i.WorkspaceID, &i.BuildsConcurrentMax); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
