// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sentinel_count_by_project.sql

package db

import (
	"context"
)

const countSentinelsByProjectId = `-- name: CountSentinelsByProjectId :one
SELECT COUNT(*) as count FROM sentinels WHERE project_id = ?
`

// CountSentinelsByProjectId
//
//	SELECT COUNT(*) as count FROM sentinels WHERE project_id = ?
func (q *Queries) CountSentinelsByProjectId(ctx context.Context, projectID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countSentinelsByProjectId, projectID)
	var count int64
	err := row.Scan(&count)
	return count, err
}
