// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: workspace_billing_find_by_workspace_id.sql

package db

import (
	"context"
	"database/sql"
)

const findWorkspaceBillingByWorkspaceID = `-- name: FindWorkspaceBillingByWorkspaceID :one
SELECT
   b.pk,
   b.workspace_id,
   b.tier,
   b.stripe_customer_id,
   bs_api.stripe_subscription_id AS stripe_subscription_id,
   bs_deploy.stripe_subscription_id AS stripe_deploy_subscription_id,
   b.plan,
   b.plan_override,
   b.spend_budget_cents,
   b.spend_budget_stop,
   b.spend_suspended,
   b.created_at_m,
   b.updated_at_m,
   b.deleted_at_m
FROM ` + "`" + `workspace_billing` + "`" + ` b
LEFT JOIN ` + "`" + `billing_subscriptions` + "`" + ` bs_api
   ON (bs_api.workspace_id = b.workspace_id COLLATE utf8mb4_0900_ai_ci AND bs_api.workspace_id = b.workspace_id COLLATE utf8mb4_0900_as_cs) AND bs_api.product = 'api'
LEFT JOIN ` + "`" + `billing_subscriptions` + "`" + ` bs_deploy
   ON (bs_deploy.workspace_id = b.workspace_id COLLATE utf8mb4_0900_ai_ci AND bs_deploy.workspace_id = b.workspace_id COLLATE utf8mb4_0900_as_cs) AND bs_deploy.product = 'compute'
WHERE b.workspace_id = ?
`

type FindWorkspaceBillingByWorkspaceIDRow struct {
	Pk                         uint64         `db:"pk"`
	WorkspaceID                string         `db:"workspace_id"`
	Tier                       sql.NullString `db:"tier"`
	StripeCustomerID           sql.NullString `db:"stripe_customer_id"`
	StripeSubscriptionID       sql.NullString `db:"stripe_subscription_id"`
	StripeDeploySubscriptionID sql.NullString `db:"stripe_deploy_subscription_id"`
	Plan                       sql.NullString `db:"plan"`
	PlanOverride               sql.NullString `db:"plan_override"`
	SpendBudgetCents           sql.NullInt64  `db:"spend_budget_cents"`
	SpendBudgetStop            bool           `db:"spend_budget_stop"`
	SpendSuspended             bool           `db:"spend_suspended"`
	CreatedAtM                 int64          `db:"created_at_m"`
	UpdatedAtM                 sql.NullInt64  `db:"updated_at_m"`
	DeletedAtM                 sql.NullInt64  `db:"deleted_at_m"`
}

// Reads a workspace's billing row directly (Stripe linkage, tier, Compute plan,
// spend budget and spend-cap state). Used by the Deploy cancel path to read the
// current plan and Stripe subscription. When a workspace is already being
// fetched, prefer joining workspace_billing in that query over a second round
// trip. Stripe subscription ids now live on billing_subscriptions, one row per
// (workspace, product).
// Temporary staged-collation bridge: the native-collation term preserves
// index lookup while the as_cs term enforces exact ID equality. Remove after
// all counterpart columns are utf8mb4_0900_as_cs.
//
//	SELECT
//	   b.pk,
//	   b.workspace_id,
//	   b.tier,
//	   b.stripe_customer_id,
//	   bs_api.stripe_subscription_id AS stripe_subscription_id,
//	   bs_deploy.stripe_subscription_id AS stripe_deploy_subscription_id,
//	   b.plan,
//	   b.plan_override,
//	   b.spend_budget_cents,
//	   b.spend_budget_stop,
//	   b.spend_suspended,
//	   b.created_at_m,
//	   b.updated_at_m,
//	   b.deleted_at_m
//	FROM `workspace_billing` b
//	LEFT JOIN `billing_subscriptions` bs_api
//	   ON (bs_api.workspace_id = b.workspace_id COLLATE utf8mb4_0900_ai_ci AND bs_api.workspace_id = b.workspace_id COLLATE utf8mb4_0900_as_cs) AND bs_api.product = 'api'
//	LEFT JOIN `billing_subscriptions` bs_deploy
//	   ON (bs_deploy.workspace_id = b.workspace_id COLLATE utf8mb4_0900_ai_ci AND bs_deploy.workspace_id = b.workspace_id COLLATE utf8mb4_0900_as_cs) AND bs_deploy.product = 'compute'
//	WHERE b.workspace_id = ?
func (q *Queries) FindWorkspaceBillingByWorkspaceID(ctx context.Context, workspaceID string) (FindWorkspaceBillingByWorkspaceIDRow, error) {
	row := q.db.QueryRowContext(ctx, findWorkspaceBillingByWorkspaceID, workspaceID)
	var i FindWorkspaceBillingByWorkspaceIDRow
	err := row.Scan(
		&i.Pk,
		&i.WorkspaceID,
		&i.Tier,
		&i.StripeCustomerID,
		&i.StripeSubscriptionID,
		&i.StripeDeploySubscriptionID,
		&i.Plan,
		&i.PlanOverride,
		&i.SpendBudgetCents,
		&i.SpendBudgetStop,
		&i.SpendSuspended,
		&i.CreatedAtM,
		&i.UpdatedAtM,
		&i.DeletedAtM,
	)
	return i, err
}
