// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: workspace_billing_find_by_workspace_id.sql

package db

import (
	"context"
)

const findWorkspaceBillingByWorkspaceID = `-- name: FindWorkspaceBillingByWorkspaceID :one
SELECT pk, workspace_id, tier, stripe_customer_id, stripe_subscription_id, plan, plan_override, spend_budget_cents, spend_budget_stop, spend_suspended, created_at_m, updated_at_m, deleted_at_m FROM ` + "`" + `workspace_billing` + "`" + `
WHERE workspace_id = ?
`

// Reads a workspace's billing row directly (Stripe linkage, tier, Compute plan,
// spend budget and spend-cap state). Used by the Deploy cancel path to read the
// current plan and Stripe subscription. When a workspace is already being
// fetched, prefer joining workspace_billing in that query over a second round
// trip.
//
//	SELECT pk, workspace_id, tier, stripe_customer_id, stripe_subscription_id, plan, plan_override, spend_budget_cents, spend_budget_stop, spend_suspended, created_at_m, updated_at_m, deleted_at_m FROM `workspace_billing`
//	WHERE workspace_id = ?
func (q *Queries) FindWorkspaceBillingByWorkspaceID(ctx context.Context, workspaceID string) (WorkspaceBilling, error) {
	row := q.db.QueryRowContext(ctx, findWorkspaceBillingByWorkspaceID, workspaceID)
	var i WorkspaceBilling
	err := row.Scan(
		&i.Pk,
		&i.WorkspaceID,
		&i.Tier,
		&i.StripeCustomerID,
		&i.StripeSubscriptionID,
		&i.Plan,
		&i.PlanOverride,
		&i.SpendBudgetCents,
		&i.SpendBudgetStop,
		&i.SpendSuspended,
		&i.CreatedAtM,
		&i.UpdatedAtM,
		&i.DeletedAtM,
	)
	return i, err
}
