// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql"
)

type IpAllocation struct {
	ID                  int64        `db:"id" json:"id"`
	VmID                string       `db:"vm_id" json:"vm_id"`
	IpAddr              string       `db:"ip_addr" json:"ip_addr"`
	NetworkAllocationID int64        `db:"network_allocation_id" json:"network_allocation_id"`
	AllocatedAt         sql.NullTime `db:"allocated_at" json:"allocated_at"`
}

type Network struct {
	ID          int64  `db:"id" json:"id"`
	BaseNetwork string `db:"base_network" json:"base_network"`
	IsAllocated int64  `db:"is_allocated" json:"is_allocated"`
}

type NetworkAllocation struct {
	ID           int64        `db:"id" json:"id"`
	DeploymentID string       `db:"deployment_id" json:"deployment_id"`
	NetworkID    int64        `db:"network_id" json:"network_id"`
	BridgeName   string       `db:"bridge_name" json:"bridge_name"`
	AvailableIps string       `db:"available_ips" json:"available_ips"`
	AllocatedAt  sql.NullTime `db:"allocated_at" json:"allocated_at"`
}
