type: object
required:
  - project
  - app
  - environment
properties:
  project:
    "$ref": "../../../../common/ResourceIdentifier.yaml"
  app:
    "$ref": "../../../../common/ResourceIdentifier.yaml"
  environment:
    "$ref": "../../../../common/ResourceIdentifier.yaml"
  git:
    "$ref": "../../../v2/deployments/createDeployment/DeploymentSourceGit.yaml"
  oci:
    "$ref": "./DeploymentSourceOCI.yaml"
  deployment:
    "$ref": "../../../v2/deployments/createDeployment/DeploymentSourceDeployment.yaml"
additionalProperties: false
description: Create a deployment. Omit the source to use the app default, or provide one source override.
