type: object
required:
  - meta
  - data
properties:
  meta:
    "$ref": "../../../../common/Meta.yaml"
  data:
    "$ref": "./V3DeploymentsCreateDeploymentResponseData.yaml"
additionalProperties: false
