type: object
required:
  - meta
  - data
properties:
  meta:
    "$ref": "../../../../common/Meta.yaml"
  data:
    "$ref": "../../../../common/EmptyResponse.yaml"
additionalProperties: false
examples:
  success:
    summary: Stop enqueued
    description: The deployment stop was successfully enqueued
    value:
      meta:
        requestId: req_1234abcd
      data: {}
