import { schema } from "@/lib/db";

export const alertSelection = {
  id: schema.alertEvents.id,
  workspaceId: schema.alertEvents.workspaceId,
  projectId: schema.alertEvents.projectId,
  appId: schema.alertEvents.appId,
  environmentId: schema.alertEvents.environmentId,
  deploymentId: schema.alertEvents.deploymentId,
  metric: schema.alertEvents.metric,
  status: schema.alertEvents.status,
  firedAt: schema.alertEvents.firedAt,
  lastSeenAt: schema.alertEvents.lastSeenAt,
  resolvedAt: schema.alertEvents.resolvedAt,
  resolutionMessage: schema.alertEvents.resolutionMessage,
  observedValue: schema.alertEvents.observedValue,
  baselineMean: schema.alertEvents.baselineMean,
  baselineStddev: schema.alertEvents.baselineStddev,
  thresholdSigma: schema.alertEvents.thresholdSigma,
  windowStart: schema.alertEvents.windowStart,
  windowEnd: schema.alertEvents.windowEnd,
  createdAt: schema.alertEvents.createdAt,
  updatedAt: schema.alertEvents.updatedAt,
  projectName: schema.projects.name,
  appName: schema.apps.name,
  appSlug: schema.apps.slug,
  environmentName: schema.environments.slug,
};
