type: object
required:
  - deploymentId
properties:
  deploymentId:
    "$ref": "../../../../common/ResourceIdentifier.yaml"
additionalProperties: false
description: Promote a ready deployment to become the live deployment for its environment.
