---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vitess-pvc
  namespace: unkey
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: unkey
  labels:
    app: mysql
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      terminationGracePeriodSeconds: 60
      securityContext:
        runAsUser: 999
        runAsGroup: 999
        fsGroup: 999
      containers:
        - name: mysql
          image: unkey/mysql:local
          imagePullPolicy: Never
          ports:
            - name: mysql
              containerPort: 33577
            - name: vstream
              containerPort: 33575
          volumeMounts:
            - name: vitess-storage
              mountPath: /vt/vtdataroot
          startupProbe:
            exec:
              command: [
                "mysql",
                "--protocol=tcp",
                "-h127.0.0.1",
                "-P33577",
                "-uunkey",
                "-ppassword",
                "unkey",
                "-e",
                "SELECT COUNT(*) FROM workspaces",
              ]
            periodSeconds: 5
            failureThreshold: 60
          readinessProbe:
            exec:
              command: [
                "mysql",
                "--protocol=tcp",
                "-h127.0.0.1",
                "-P33577",
                "-uunkey",
                "-ppassword",
                "unkey",
                "-e",
                "SELECT COUNT(*) FROM workspaces",
              ]
            timeoutSeconds: 5
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: mysql
            periodSeconds: 30
      volumes:
        - name: vitess-storage
          persistentVolumeClaim:
            claimName: vitess-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: unkey
  labels:
    app: mysql
spec:
  selector:
    app: mysql
  ports:
    - name: mysql
      port: 3306
      targetPort: mysql
      protocol: TCP
    - name: vstream
      port: 33575
      targetPort: vstream
      protocol: TCP
  type: LoadBalancer
