/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { domainsCreateDomain } from "../funcs/domainsCreateDomain.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as components from "../models/components/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Domains extends ClientSDK {
  /**
   * Create domain
   *
   * @remarks
   * Attach a custom domain to an environment and start verifying it.
   *
   * The domain is created in the `pending` state and does not serve traffic until verification succeeds. Verification runs in the background and polls DNS, so it is eventually consistent.
   *
   * The response returns `dnsRecords`: every record needed to finish setup, already resolved for whether this domain is an apex or a subdomain. Create every entry exactly as given. One record establishes routing and one proves ownership, and both are needed: whether ownership can be inferred from the routing record depends on how your provider publishes it, and a name another workspace has already verified can only be claimed through the ownership record. Neither is knowable before the records exist.
   *
   * When your DNS provider supports Domain Connect, the response also carries `domainConnectProvider` and `domainConnectUrl`; opening that URL applies the same records at the provider in one step.
   *
   * Domains are unique per workspace, so the same name cannot be attached to two environments. Attaching a domain that already exists in your workspace returns a 409 conflict.
   *
   * **Important**: verification stops after 24 hours without the required DNS records, and the domain moves to `failed`.
   *
   * **Required Permissions**
   *
   * Your root key must have one of the following permissions:
   * - `environment.*.create_domain` (to attach domains to any environment)
   * - `environment.<environment_id>.create_domain` (to attach domains to a specific environment)
   */
  async createDomain(
    request: components.V2DomainsCreateDomainRequestBody,
    options?: RequestOptions,
  ): Promise<components.V2DomainsCreateDomainResponseBody> {
    return unwrapAsync(domainsCreateDomain(
      this,
      request,
      options,
    ));
  }
}
