/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { rootKeysCreateKey } from "../funcs/rootKeysCreateKey.js";
import { rootKeysDeleteKey } from "../funcs/rootKeysDeleteKey.js";
import { rootKeysListKeys } from "../funcs/rootKeysListKeys.js";
import { rootKeysRerollKey } from "../funcs/rootKeysRerollKey.js";
import { rootKeysUpdateKey } from "../funcs/rootKeysUpdateKey.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as components from "../models/components/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";
import { PageIterator, unwrapResultIterator } from "../types/operations.js";

export class RootKeys extends ClientSDK {
  /**
   * Create root key
   *
   * @remarks
   * Creates a root key for the authenticated workspace.
   * Requires `unkey:v1:<workspace_id>:rootKeys/*#write`.
   * The created root key cannot have more permissions than the caller.
   */
  async createKey(
    request: components.V2RootKeysCreateKeyRequestBody,
    options?: RequestOptions,
  ): Promise<components.V2RootKeysCreateKeyResponseBody> {
    return unwrapAsync(rootKeysCreateKey(
      this,
      request,
      options,
    ));
  }

  /**
   * Delete root key
   *
   * @remarks
   * Deletes a root key in the authenticated workspace.
   * Requires `unkey:v1:<workspace_id>:rootKeys/<key_id>#delete`.
   * Use `rootKeys/*#delete` to delete any root key in the workspace.
   * Deleted keys cannot authenticate.
   */
  async deleteKey(
    request: components.V2RootKeysDeleteKeyRequestBody,
    options?: RequestOptions,
  ): Promise<components.V2RootKeysDeleteKeyResponseBody> {
    return unwrapAsync(rootKeysDeleteKey(
      this,
      request,
      options,
    ));
  }

  /**
   * List root keys
   *
   * @remarks
   * Lists readable root keys in the authenticated workspace, ordered by key ID.
   * Requires `unkey:v1:<workspace_id>:rootKeys/<key_id>#read` for each returned key.
   * Use `rootKeys/*#read` to read all root keys. Write permission does not imply read.
   * A caller with no readable keys receives an empty page.
   *
   * Includes disabled and expired keys from the new root-key store.
   * Deleted keys are excluded. Secrets and hashes are never returned.
   * Pass the returned cursor when hasMore is true to retrieve the next page.
   */
  async listKeys(
    request: components.V2RootKeysListKeysRequestBody,
    options?: RequestOptions,
  ): Promise<
    PageIterator<operations.RootKeysListKeysResponse, { cursor: string }>
  > {
    return unwrapResultIterator(rootKeysListKeys(
      this,
      request,
      options,
    ));
  }

  /**
   * Reroll root key
   *
   * @remarks
   * Creates a new root key secret with the same name, enabled state, expiration, and
   * effective permissions as an existing root key in the authenticated workspace.
   * Requires `unkey:v1:<workspace_id>:rootKeys/<key_id>#write`, and the caller must
   * already hold every permission of the original key. When `expiration` is not null,
   * it also requires `unkey:v1:<workspace_id>:rootKeys/<key_id>#delete`.
   *
   * `expiration` controls the original key: 0 revokes it immediately, a positive value
   * keeps it valid for that many milliseconds, and null keeps its current expiration.
   */
  async rerollKey(
    request: components.V2RootKeysRerollKeyRequestBody,
    options?: RequestOptions,
  ): Promise<components.V2RootKeysRerollKeyResponseBody> {
    return unwrapAsync(rootKeysRerollKey(
      this,
      request,
      options,
    ));
  }

  /**
   * Update root key
   *
   * @remarks
   * Updates a root key in the authenticated workspace.
   * Requires `unkey:v1:<workspace_id>:rootKeys/<key_id>#write`.
   * Use `rootKeys/*#write` to update any root key in the workspace.
   *
   * `permissions` replaces the complete permission set. Each permission must be a supported URN
   * in the authenticated workspace and within the caller's permissions.
   * An expiring root key can only update root keys that expire no later than itself.
   */
  async updateKey(
    request: components.V2RootKeysUpdateKeyRequestBody,
    options?: RequestOptions,
  ): Promise<components.V2RootKeysUpdateKeyResponseBody> {
    return unwrapAsync(rootKeysUpdateKey(
      this,
      request,
      options,
    ));
  }
}
