import { MiddlewareRequest, MiddlewareResponse } from "@redwoodjs/vite/middleware";
import { Ratelimit } from "@unkey/ratelimit";
import type { RatelimitConfig, RatelimitResponse } from "@unkey/ratelimit";
import { assert, describe, expect, it, vi } from "vitest";
import withUnkey from "../index";
import type { withUnkeyOptions } from "../index";

/**
 * Mock the Ratelimit class
 *
 * Use namespace to store the ratelimit identifier that determines if the rate limit is exceeded
 *
 * If namespace matches the identifier generated by withUnkey middlewate, the rate limit is exceeded
 * and the response status is 429 because success is false
 */
vi.mock("@unkey/ratelimit", () => {
  let rateLimitIdentifier = "";

  return {
    Ratelimit: class {
      constructor(config: RatelimitConfig) {
        console.debug(">>>> in Ratelimit constructor", config);
        rateLimitIdentifier = config.namespace;
      }
      limit(identifier: string): Promise<RatelimitResponse> {
        console.debug(">>>> in limit", identifier);
        return Promise.resolve({
          success: identifier === rateLimitIdentifier,
          limit: 0,
          remaining: 0,
          reset: 0,
        });
      }
    },
  };
});

describe("withUnkey", () => {
  it("should work", async () => {
    const options: withUnkeyOptions = {
      ratelimitConfig: {
        rootKey: "foo",
        namespace: "192.168.1.1",
        limit: 1,
        duration: "30s",
        async: true,
      },
      matcher: ["/api/user"],
    };
    const unkeyMiddleware = withUnkey(options);
    const request = new Request("http://localhost:8910/api/user");
    const req = new MiddlewareRequest(request);
    const res = new MiddlewareResponse();
    const result = await unkeyMiddleware(req, res);
    expect(result.status).toBe(200);
  });

  it("should be limited", async () => {
    // here the namespace will cause the rate limit to be exceeded because it does not match the identifier
    // generated by the withUnkey middleware
    const options: withUnkeyOptions = {
      ratelimitConfig: {
        rootKey: "foo",
        namespace: "my-app",
        limit: 1,
        duration: "30s",
        async: true,
      },
      matcher: ["/api/user"],
    };
    const unkeyMiddleware = withUnkey(options);
    const request = new Request("http://localhost:8910/api/user");
    const req = new MiddlewareRequest(request);
    const res = new MiddlewareResponse();
    const result = await unkeyMiddleware(req, res);
    expect(result.status).toBe(429);
  });
});
