type: object
required:
  - meta
  - data
  - pagination
properties:
  meta:
    "$ref": "../../../../common/Meta.yaml"
  data:
    type: array
    maxItems: 100
    items:
      "$ref": "../../../../common/Deployment.yaml"
    description: Array of deployments, ordered newest first.
  pagination:
    "$ref": "../../../../common/Pagination.yaml"
additionalProperties: false
