type: object
required:
  - meta
  - data
properties:
  meta:
    "$ref": "../../../../common/Meta.yaml"
  data:
    type: array
    maxItems: 100
    items:
      "$ref": "../../../../common/Deployment.yaml"
    description: Array of deployments, ordered newest first.
  pagination:
    "$ref": "../../../../common/Pagination.yaml"
    x-go-type-skip-optional-pointer: true
    x-go-type-skip-optional-pointer-with-omitzero: true
additionalProperties: false
