load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "deploymentcleanup",
    srcs = ["handler.go"],
    importpath = "github.com/unkeyed/unkey/svc/ctrl/worker/cron/deploymentcleanup",
    visibility = ["//visibility:public"],
    deps = [
        "//gen/proto/hydra/v1:hydra",
        "//pkg/assert",
        "//pkg/healthcheck",
        "//pkg/logger",
        "//pkg/restate/restateutil",
        "//svc/ctrl/internal/db",
        "//svc/ctrl/worker/cron/registrysweep",
        "@com_github_restatedev_sdk_go//:sdk-go",
    ],
)
