/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

export type V2AnalyticsGetVerificationsRequestBody = {
  /**
   * SQL query to execute against your analytics data.
   *
   * @remarks
   * Only SELECT queries are allowed.
   */
  query: string;
};

/** @internal */
export type V2AnalyticsGetVerificationsRequestBody$Outbound = {
  query: string;
};

/** @internal */
export const V2AnalyticsGetVerificationsRequestBody$outboundSchema: z.ZodType<
  V2AnalyticsGetVerificationsRequestBody$Outbound,
  z.ZodTypeDef,
  V2AnalyticsGetVerificationsRequestBody
> = z.object({
  query: z.string(),
});

export function v2AnalyticsGetVerificationsRequestBodyToJSON(
  v2AnalyticsGetVerificationsRequestBody:
    V2AnalyticsGetVerificationsRequestBody,
): string {
  return JSON.stringify(
    V2AnalyticsGetVerificationsRequestBody$outboundSchema.parse(
      v2AnalyticsGetVerificationsRequestBody,
    ),
  );
}
