/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import { Meta, Meta$inboundSchema } from "./meta.js";
import {
  V2ApisCreateApiResponseData,
  V2ApisCreateApiResponseData$inboundSchema,
} from "./v2apiscreateapiresponsedata.js";

export type V2ApisCreateApiResponseBody = {
  /**
   * Metadata object included in every API response. This provides context about the request and is essential for debugging, audit trails, and support inquiries. The `requestId` is particularly important when troubleshooting issues with the Unkey support team.
   */
  meta: Meta;
  data: V2ApisCreateApiResponseData;
};

/** @internal */
export const V2ApisCreateApiResponseBody$inboundSchema: z.ZodType<
  V2ApisCreateApiResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  meta: Meta$inboundSchema,
  data: V2ApisCreateApiResponseData$inboundSchema,
});

export function v2ApisCreateApiResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<V2ApisCreateApiResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => V2ApisCreateApiResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'V2ApisCreateApiResponseBody' from JSON`,
  );
}
