/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import { Meta, Meta$inboundSchema } from "./meta.js";
import { Role, Role$inboundSchema } from "./role.js";

export type V2PermissionsGetRoleResponseBody = {
  /**
   * Metadata object included in every API response. This provides context about the request and is essential for debugging, audit trails, and support inquiries. The `requestId` is particularly important when troubleshooting issues with the Unkey support team.
   */
  meta: Meta;
  data: Role;
};

/** @internal */
export const V2PermissionsGetRoleResponseBody$inboundSchema: z.ZodType<
  V2PermissionsGetRoleResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  meta: Meta$inboundSchema,
  data: Role$inboundSchema,
});

export function v2PermissionsGetRoleResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<V2PermissionsGetRoleResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => V2PermissionsGetRoleResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'V2PermissionsGetRoleResponseBody' from JSON`,
  );
}
