/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type V2RatelimitSetOverrideResponseData = {
  /**
   * The unique identifier for the newly created or updated rate limit override. This ID can be used to:
   *
   * @remarks
   *
   * - Reference this specific override in subsequent API calls
   * - Delete or modify this override later
   * - Track which override is being applied in rate limit responses
   * - Associate override effects with specific rules in analytics
   *
   * Store this ID if you need to manage the override in the future.
   */
  overrideId: string;
};

/** @internal */
export const V2RatelimitSetOverrideResponseData$inboundSchema: z.ZodType<
  V2RatelimitSetOverrideResponseData,
  z.ZodTypeDef,
  unknown
> = z.object({
  overrideId: z.string(),
});

export function v2RatelimitSetOverrideResponseDataFromJSON(
  jsonString: string,
): SafeParseResult<V2RatelimitSetOverrideResponseData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      V2RatelimitSetOverrideResponseData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'V2RatelimitSetOverrideResponseData' from JSON`,
  );
}
