// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: deployment_topology_find_regions.sql

package db

import (
	"context"
)

const findDeploymentRegions = `-- name: FindDeploymentRegions :many
SELECT r.pk, r.id, r.name, r.platform
FROM ` + "`" + `deployment_topology` + "`" + ` dt
INNER JOIN ` + "`" + `regions` + "`" + ` r ON dt.region_id = r.id
WHERE dt.deployment_id = ?
`

// Returns all regions where a deployment is configured.
// Used for fan-out: when a deployment changes, emit state_change to each region.
//
//	SELECT r.pk, r.id, r.name, r.platform
//	FROM `deployment_topology` dt
//	INNER JOIN `regions` r ON dt.region_id = r.id
//	WHERE dt.deployment_id = ?
func (q *Queries) FindDeploymentRegions(ctx context.Context, deploymentID string) ([]Region, error) {
	rows, err := q.db.QueryContext(ctx, findDeploymentRegions, deploymentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Region
	for rows.Next() {
		var i Region
		if err := rows.Scan(
			&i.Pk,
			&i.ID,
			&i.Name,
			&i.Platform,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
