instance_id = "ctrl-api-dev"
region = "local"
http_port = 7091
auth_token = "your-local-dev-key"
default_domain = "unkey.local"
cname_domain = "unkey.local"

[database]
primary = "unkey:password@tcp(mysql:3306)/unkey?parseTime=true&interpolateParams=true"

[restate]
url = "http://restate:8080"
admin_url = "http://restate:9070"

[domain_connect]
private_key_pem = """${UNKEY_DOMAIN_CONNECT_PRIVATE_KEY}"""

[github]
webhook_secret = "${UNKEY_GITHUB_APP_WEBHOOK_SECRET}"
app_id = ${UNKEY_GITHUB_APP_ID}
private_key_pem = """${UNKEY_GITHUB_PRIVATE_KEY_PEM}"""
