services:
  restate:
    image: docker.io/restatedev/restate:1.6.0@sha256:33f227db946864b5482340a8621e32ec5eaf464f4dc41d5deccfd3282bb930ae
    ports:
      - "18080:8080"
      - "19070:9070"
    extra_hosts:
      - "host.docker.internal:host-gateway"
