// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: certificate_find_by_hostnames.sql

package db

import (
	"context"
	"strings"
)

const findBestCertificateByCandidates = `-- name: FindBestCertificateByCandidates :one
SELECT
  hostname,
  workspace_id,
  certificate,
  encrypted_private_key
FROM certificates
WHERE hostname IN (/*SLICE:hostnames*/?)
ORDER BY hostname = ? DESC
LIMIT 1
`

type FindBestCertificateByCandidatesParams struct {
	Hostnames     []string `db:"hostnames"`
	ExactHostname string   `db:"exact_hostname"`
}

type FindBestCertificateByCandidatesRow struct {
	Hostname            string `db:"hostname"`
	WorkspaceID         string `db:"workspace_id"`
	Certificate         string `db:"certificate"`
	EncryptedPrivateKey string `db:"encrypted_private_key"`
}

// FindBestCertificateByCandidates returns a single certificate row for the
// provided candidates, preferring an exact hostname over wildcard matches.
// MySQL does not preserve IN-list order, so exact-first behavior is enforced
// by ORDER BY against the exact_hostname argument rather than by candidate
// position.
//
// For example, if candidates are ['api.example.com', '*.example.com'] and
// exact_hostname is 'api.example.com', the query returns 'api.example.com'
// when both rows exist.
//
// If only '*.example.com' exists, the query returns that wildcard row as the
// fallback.
//
// LIMIT 1 keeps the lookup to one selected row and avoids returning unused
// certificate and key payloads.
//
//	SELECT
//	  hostname,
//	  workspace_id,
//	  certificate,
//	  encrypted_private_key
//	FROM certificates
//	WHERE hostname IN (/*SLICE:hostnames*/?)
//	ORDER BY hostname = ? DESC
//	LIMIT 1
func (q *Queries) FindBestCertificateByCandidates(ctx context.Context, db DBTX, arg FindBestCertificateByCandidatesParams) (FindBestCertificateByCandidatesRow, error) {
	query := findBestCertificateByCandidates
	var queryParams []interface{}
	if len(arg.Hostnames) > 0 {
		for _, v := range arg.Hostnames {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:hostnames*/?", strings.Repeat(",?", len(arg.Hostnames))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:hostnames*/?", "NULL", 1)
	}
	queryParams = append(queryParams, arg.ExactHostname)
	row := db.QueryRowContext(ctx, query, queryParams...)
	var i FindBestCertificateByCandidatesRow
	err := row.Scan(
		&i.Hostname,
		&i.WorkspaceID,
		&i.Certificate,
		&i.EncryptedPrivateKey,
	)
	return i, err
}
