// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package mysql

import (
	"database/sql"
)

type Kv struct {
	ID          int64
	WorkspaceID string
	Key         string
	Value       []byte
	Ttl         sql.NullInt64
	CreatedAt   int64
}
