package deploy

import "fmt"

func PrintDeployHelp() {
	fmt.Println("unkey deploy - Deploy a new version")
	fmt.Println("")
	fmt.Println("USAGE:")
	fmt.Println("    unkey deploy [FLAGS]")
	fmt.Println("")
	fmt.Println("DESCRIPTION:")
	fmt.Println("    Build and deploy a new version of your application.")
	fmt.Println("    Builds a Docker image from the specified context and")
	fmt.Println("    deploys it to the Unkey platform.")
	fmt.Println("")
	fmt.Println("REQUIRED FLAGS:")
	fmt.Println("    --workspace-id <id>    Workspace ID")
	fmt.Println("    --project-id <id>      Project ID")
	fmt.Println("")
	fmt.Println("OPTIONAL FLAGS:")
	fmt.Println("    --context <path>       Docker context path (default: .)")
	fmt.Println("    --branch <name>        Git branch (default: main)")
	fmt.Println("    --docker-image <tag>   Pre-built docker image")
	fmt.Println("    --dockerfile <path>    Path to Dockerfile (default: Dockerfile)")
	fmt.Println("    --commit <sha>         Git commit SHA")
	fmt.Println("    --registry <registry>  Docker registry (default: ghcr.io/unkeyed/deploy)")
	fmt.Println("    --skip-push            Skip pushing to registry")
	fmt.Println("")
	fmt.Println("ENVIRONMENT VARIABLES:")
	fmt.Println("    UNKEY_WORKSPACE_ID     Default workspace ID")
	fmt.Println("    UNKEY_PROJECT_ID       Default project ID")
	fmt.Println("    UNKEY_DOCKER_REGISTRY  Default Docker registry")
	fmt.Println("")
	fmt.Println("EXAMPLES:")
	fmt.Println("    # Basic deployment")
	fmt.Println("    unkey deploy \\")
	fmt.Println("      --workspace-id=ws_4QgQsKsKfdm3nGeC \\")
	fmt.Println("      --project-id=proj_9aiaks2dzl6mcywnxjf \\")
	fmt.Println("      --context=./demo_api")
	fmt.Println("")
	fmt.Println("    # Deploy with your own registry")
	fmt.Println("    unkey deploy \\")
	fmt.Println("      --workspace-id=ws_4QgQsKsKfdm3nGeC \\")
	fmt.Println("      --project-id=proj_9aiaks2dzl6mcywnxjf \\")
	fmt.Println("      --registry=docker.io/mycompany/myapp")
	fmt.Println("")
	fmt.Println("    # Local development (skip push)")
	fmt.Println("    unkey deploy \\")
	fmt.Println("      --workspace-id=ws_4QgQsKsKfdm3nGeC \\")
	fmt.Println("      --project-id=proj_9aiaks2dzl6mcywnxjf \\")
	fmt.Println("      --skip-push")
	fmt.Println("")
	fmt.Println("    # Deploy pre-built image")
	fmt.Println("    unkey deploy \\")
	fmt.Println("      --workspace-id=ws_4QgQsKsKfdm3nGeC \\")
	fmt.Println("      --project-id=proj_9aiaks2dzl6mcywnxjf \\")
	fmt.Println("      --docker-image=ghcr.io/user/app:v1.0.0")
}
