// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package sdkerrors

import (
	"encoding/json"
	"fmt"
)

// ErrInternalServerErrorCode - A machine readable error code.
type ErrInternalServerErrorCode string

const (
	ErrInternalServerErrorCodeInternalServerError ErrInternalServerErrorCode = "INTERNAL_SERVER_ERROR"
)

func (e ErrInternalServerErrorCode) ToPointer() *ErrInternalServerErrorCode {
	return &e
}

func (e *ErrInternalServerErrorCode) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "INTERNAL_SERVER_ERROR":
		*e = ErrInternalServerErrorCode(v)
		return nil
	default:
		return fmt.Errorf("invalid value for ErrInternalServerErrorCode: %v", v)
	}
}

type ErrInternalServerErrorError struct {
	// A machine readable error code.
	Code ErrInternalServerErrorCode `json:"code"`
	// A link to our documentation with more details about this error code
	Docs string `json:"docs"`
	// A human readable explanation of what went wrong
	Message string `json:"message"`
	// Please always include the requestId in your error report
	RequestID string `json:"requestId"`
}

func (o *ErrInternalServerErrorError) GetCode() ErrInternalServerErrorCode {
	if o == nil {
		return ErrInternalServerErrorCode("")
	}
	return o.Code
}

func (o *ErrInternalServerErrorError) GetDocs() string {
	if o == nil {
		return ""
	}
	return o.Docs
}

func (o *ErrInternalServerErrorError) GetMessage() string {
	if o == nil {
		return ""
	}
	return o.Message
}

func (o *ErrInternalServerErrorError) GetRequestID() string {
	if o == nil {
		return ""
	}
	return o.RequestID
}

// ErrInternalServerError - The server has encountered a situation it does not know how to handle.
type ErrInternalServerError struct {
	Error_ ErrInternalServerErrorError `json:"error"`
}

var _ error = &ErrInternalServerError{}

func (e *ErrInternalServerError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}
