// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: gateway_upsert.sql

package db

import (
	"context"
)

const upsertGateway = `-- name: UpsertGateway :exec
INSERT INTO gateways (
workspace_id,
deployment_id,
hostname,
config
)
VALUES (
?,
?,
?,
?
)
ON DUPLICATE KEY UPDATE
    workspace_id = ?,
    deployment_id = ?,
    config = ?
`

type UpsertGatewayParams struct {
	WorkspaceID  string `db:"workspace_id"`
	DeploymentID string `db:"deployment_id"`
	Hostname     string `db:"hostname"`
	Config       []byte `db:"config"`
}

// UpsertGateway
//
//	INSERT INTO gateways (
//	workspace_id,
//	deployment_id,
//	hostname,
//	config
//	)
//	VALUES (
//	?,
//	?,
//	?,
//	?
//	)
//	ON DUPLICATE KEY UPDATE
//	    workspace_id = ?,
//	    deployment_id = ?,
//	    config = ?
func (q *Queries) UpsertGateway(ctx context.Context, db DBTX, arg UpsertGatewayParams) error {
	_, err := db.ExecContext(ctx, upsertGateway,
		arg.WorkspaceID,
		arg.DeploymentID,
		arg.Hostname,
		arg.Config,
		arg.WorkspaceID,
		arg.DeploymentID,
		arg.Config,
	)
	return err
}
