// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: gateway_find_config_by_hostname.sql

package db

import (
	"context"
)

const findGatewayByHostname = `-- name: FindGatewayByHostname :one
SELECT hostname, config
FROM gateways
WHERE hostname = ?
`

type FindGatewayByHostnameRow struct {
	Hostname string `db:"hostname"`
	Config   []byte `db:"config"`
}

// FindGatewayByHostname
//
//	SELECT hostname, config
//	FROM gateways
//	WHERE hostname = ?
func (q *Queries) FindGatewayByHostname(ctx context.Context, db DBTX, hostname string) (FindGatewayByHostnameRow, error) {
	row := db.QueryRowContext(ctx, findGatewayByHostname, hostname)
	var i FindGatewayByHostnameRow
	err := row.Scan(&i.Hostname, &i.Config)
	return i, err
}
