// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: instance_find_by_deployment_id.sql

package db

import (
	"context"
)

const findInstancesByDeploymentId = `-- name: FindInstancesByDeploymentId :many
SELECT id, deployment_id, status, config FROM instance WHERE deployment_id = ?
`

// FindInstancesByDeploymentId
//
//	SELECT id, deployment_id, status, config FROM instance WHERE deployment_id = ?
func (q *Queries) FindInstancesByDeploymentId(ctx context.Context, db DBTX, deploymentID string) ([]Instance, error) {
	rows, err := db.QueryContext(ctx, findInstancesByDeploymentId, deploymentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Instance
	for rows.Next() {
		var i Instance
		if err := rows.Scan(
			&i.ID,
			&i.DeploymentID,
			&i.Status,
			&i.Config,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
