// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: instance_find_by_deployment_ids.sql

package db

import (
	"context"
	"strings"
)

const findInstancesByDeploymentIds = `-- name: FindInstancesByDeploymentIds :many
SELECT id, deployment_id, status, config FROM instance WHERE deployment_id IN (/*SLICE:deployment_ids*/?)
`

// FindInstancesByDeploymentIds
//
//	SELECT id, deployment_id, status, config FROM instance WHERE deployment_id IN (/*SLICE:deployment_ids*/?)
func (q *Queries) FindInstancesByDeploymentIds(ctx context.Context, db DBTX, deploymentIds []string) ([]Instance, error) {
	query := findInstancesByDeploymentIds
	var queryParams []interface{}
	if len(deploymentIds) > 0 {
		for _, v := range deploymentIds {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:deployment_ids*/?", strings.Repeat(",?", len(deploymentIds))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:deployment_ids*/?", "NULL", 1)
	}
	rows, err := db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Instance
	for rows.Next() {
		var i Instance
		if err := rows.Scan(
			&i.ID,
			&i.DeploymentID,
			&i.Status,
			&i.Config,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
