// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"context"
)

type Querier interface {
	//DeleteGatewayConfig
	//
	//  DELETE FROM gateways
	//  WHERE hostname = ?
	DeleteGatewayConfig(ctx context.Context, db DBTX, hostname string) error
	//GetGatewayConfig
	//
	//  SELECT hostname, gateway_config
	//  FROM gateways
	//  WHERE hostname = ?
	GetGatewayConfig(ctx context.Context, db DBTX, hostname string) (Gateway, error)
	//UpsertGatewayConfig
	//
	//  INSERT INTO gateways (hostname, gateway_config)
	//  VALUES (?, ?)
	//  ON DUPLICATE KEY UPDATE
	//      gateway_config = VALUES(gateway_config)
	UpsertGatewayConfig(ctx context.Context, db DBTX, arg UpsertGatewayConfigParams) error
}

var _ Querier = (*Queries)(nil)
