export const DEFAULT_FETCH_COUNT = 50;

export const eventGroups = {
  create: [
    "workspace.create",
    "gateway.create",
    "llmGateway.create",
    "api.create",
    "key.create",
    "ratelimitNamespace.create",
    "vercelIntegration.create",
    "vercelBinding.create",
    "role.create",
    "permission.create",
    "secret.create",
    "webhook.create",
    "reporter.create",
    "identity.create",
    "ratelimit.create",
    "auditLogBucket.create",
  ],
  delete: [
    "workspace.delete",
    "llmGateway.delete",
    "api.delete",
    "key.delete",
    "ratelimitNamespace.delete",
    "vercelIntegration.delete",
    "vercelBinding.delete",
    "role.delete",
    "permission.delete",
    "webhook.delete",
    "identity.delete",
    "ratelimit.delete",
    "ratelimit.delete_override",
  ],
  update: [
    "workspace.update",
    "api.update",
    "key.update",
    "ratelimitNamespace.update",
    "vercelIntegration.update",
    "vercelBinding.update",
    "role.update",
    "permission.update",
    "secret.update",
    "webhook.update",
    "identity.update",
    "ratelimit.update",
    "authorization.connect_role_and_permission",
    "authorization.disconnect_role_and_permissions",
    "authorization.connect_role_and_key",
    "authorization.disconnect_role_and_key",
    "authorization.connect_permission_and_key",
    "authorization.disconnect_permission_and_key",
    "ratelimit.set_override",
  ],
  other: ["workspace.opt_in", "secret.decrypt", "ratelimit.read_override"],
} as const;
