-- name: CreateKey :exec
INSERT INTO
    `keys` (
        id,
        hash,
        start,
        owner_id,
        meta,
        created_at,
        expires,
        ratelimit_type,
        ratelimit_limit,
        ratelimit_refill_rate,
        ratelimit_refill_interval,
        workspace_id,
        for_workspace_id,
        name,
        remaining_requests,
        key_auth_id
    )
VALUES
    (
        sqlc.arg("id"),
        sqlc.arg("hash"),
        sqlc.arg("start"),
        sqlc.arg("owner_id"),
        sqlc.arg("meta"),
        sqlc.arg("created_at"),
        sqlc.arg("expires"),
        sqlc.arg("ratelimit_type"),
        sqlc.arg("ratelimit_limit"),
        sqlc.arg("ratelimit_refill_rate"),
        sqlc.arg("ratelimit_refill_interval"),
        sqlc.arg("workspace_id"),
        sqlc.arg("for_workspace_id"),
        sqlc.arg("name"),
        sqlc.arg("remaining_requests"),
        sqlc.arg("key_auth_id")
    );