// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: logdrain_update_config.sql

package db

import (
	"context"
)

const updateLogdrainConfig = `-- name: UpdateLogdrainConfig :exec
UPDATE logdrains
SET config = ?,
  lease_expires_at = 0,
  consecutive_failures = 0,
  next_attempt_at = 0
WHERE id = ?
`

type UpdateLogdrainConfigParams struct {
	Config []byte `db:"config"`
	ID     string `db:"id"`
}

// UpdateLogdrainConfig replaces a drain's delivery config the way the
// dashboard does: it expires the lease so in-flight state writes fail and
// resets failure state. Only tests call it.
//
//	UPDATE logdrains
//	SET config = ?,
//	  lease_expires_at = 0,
//	  consecutive_failures = 0,
//	  next_attempt_at = 0
//	WHERE id = ?
func (q *Queries) UpdateLogdrainConfig(ctx context.Context, arg UpdateLogdrainConfigParams) error {
	_, err := q.db.ExecContext(ctx, updateLogdrainConfig, arg.Config, arg.ID)
	return err
}
