// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: logdrain_delete.sql

package db

import (
	"context"
)

const deleteLogdrain = `-- name: DeleteLogdrain :exec
DELETE FROM logdrains
WHERE id = ?
`

// DeleteLogdrain hard-deletes one drain. Only tests call it.
//
//	DELETE FROM logdrains
//	WHERE id = ?
func (q *Queries) DeleteLogdrain(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteLogdrain, id)
	return err
}
