import type { DiffData } from "./types";

export const sampleDiffData: DiffData = {
  changes: [
    {
      id: "new-required-request-parameter",
      text: "added the new required 'query' request parameter 'status'",
      level: 3,
      operation: "GET",
      path: "/users",
      source: "/tmp/tmp2461057470/revision",
      section: "paths",
    },
    {
      id: "new-required-request-property",
      text: "added the new required request property 'acceptTerms'",
      level: 3,
      operation: "POST",
      path: "/users",
      source: "/tmp/tmp2461057470/revision",
      section: "paths",
    },
    {
      id: "new-required-request-property",
      text: "added the new required request property 'fullName'",
      level: 3,
      operation: "POST",
      path: "/users",
      source: "/tmp/tmp2461057470/revision",
      section: "paths",
    },
    {
      id: "request-property-max-length-decreased",
      text: "the 'username' request property's maxLength was decreased to '30'",
      level: 3,
      operation: "POST",
      path: "/users",
      source: "/tmp/tmp2461057470/revision",
      section: "paths",
    },
    {
      id: "request-property-min-length-increased",
      text: "the 'password' request property's minLength was increased from '8' to '12'",
      level: 3,
      operation: "POST",
      path: "/users",
      source: "/tmp/tmp2461057470/revision",
      section: "paths",
    },
    {
      id: "request-property-min-length-increased",
      text: "the 'username' request property's minLength was increased from '3' to '5'",
      level: 3,
      operation: "POST",
      path: "/users",
      source: "/tmp/tmp2461057470/revision",
      section: "paths",
    },
    {
      id: "response-property-type-changed",
      text: "the 'id' response's property type/format changed from 'string'/'uuid' to 'integer'/'int64' for status '201'",
      level: 3,
      operation: "POST",
      path: "/users",
      source: "/tmp/tmp2461057470/revision",
      section: "paths",
    },
    {
      id: "request-parameter-type-changed",
      text: "for the 'path' request parameter 'userId', the type/format was changed from 'string'/'uuid' to 'integer'/'int64'",
      level: 3,
      operation: "DELETE",
      path: "/users/{userId}",
      source: "/tmp/tmp2461057470/revision",
      section: "paths",
    },
    {
      id: "request-parameter-type-changed",
      text: "for the 'path' request parameter 'userId', the type/format was changed from 'string'/'uuid' to 'integer'/'int64'",
      level: 3,
      operation: "GET",
      path: "/users/{userId}",
      source: "/tmp/tmp2461057470/revision",
      section: "paths",
    },
    {
      id: "response-property-type-changed",
      text: "the 'id' response's property type/format changed from 'string'/'uuid' to 'integer'/'int64' for status '200'",
      level: 3,
      operation: "GET",
      path: "/users/{userId}",
      source: "/tmp/tmp2461057470/revision",
      section: "paths",
    },
    {
      id: "api-removed-without-deprecation",
      text: "api removed without deprecation",
      level: 3,
      operation: "PUT",
      path: "/users/{userId}",
      source: "/tmp/tmp2461057470/base",
      section: "paths",
    },
    {
      id: "request-parameter-type-changed",
      text: "for the 'path' request parameter 'userId', the type/format was changed from 'string'/'uuid' to 'integer'/'int64'",
      level: 3,
      operation: "GET",
      path: "/users/{userId}/profile",
      source: "/tmp/tmp2461057470/revision",
      section: "paths",
    },
    {
      id: "response-property-type-changed",
      text: "the 'userId' response's property type/format changed from 'string'/'uuid' to 'integer'/'int64' for status '200'",
      level: 3,
      operation: "GET",
      path: "/users/{userId}/profile",
      source: "/tmp/tmp2461057470/revision",
      section: "paths",
    },
    {
      id: "response-required-property-removed",
      text: "removed the required property 'bio' from the response with the '200' status",
      level: 3,
      operation: "GET",
      path: "/users/{userId}/profile",
      source: "/tmp/tmp2461057470/revision",
      section: "paths",
    },
    {
      id: "request-parameter-removed",
      text: "deleted the 'query' request parameter 'limit'",
      comment:
        "This is a warning because some apps may return an error when receiving a parameter that they do not expect. It is recommended to deprecate the parameter first.",
      level: 2,
      operation: "GET",
      path: "/users",
      source: "/tmp/tmp2461057470/revision",
      section: "paths",
    },
    {
      id: "request-parameter-removed",
      text: "deleted the 'query' request parameter 'offset'",
      comment:
        "This is a warning because some apps may return an error when receiving a parameter that they do not expect. It is recommended to deprecate the parameter first.",
      level: 2,
      operation: "GET",
      path: "/users",
      source: "/tmp/tmp2461057470/revision",
      section: "paths",
    },
    {
      id: "response-optional-property-removed",
      text: "removed the optional property 'limit' from the response with the '200' status",
      level: 2,
      operation: "GET",
      path: "/users",
      source: "/tmp/tmp2461057470/revision",
      section: "paths",
    },
    {
      id: "response-optional-property-removed",
      text: "removed the optional property 'offset' from the response with the '200' status",
      level: 2,
      operation: "GET",
      path: "/users",
      source: "/tmp/tmp2461057470/revision",
      section: "paths",
    },
    {
      id: "response-optional-property-removed",
      text: "removed the optional property 'total' from the response with the '200' status",
      level: 2,
      operation: "GET",
      path: "/users",
      source: "/tmp/tmp2461057470/revision",
      section: "paths",
    },
    {
      id: "response-optional-property-removed",
      text: "removed the optional property 'users' from the response with the '200' status",
      level: 2,
      operation: "GET",
      path: "/users",
      source: "/tmp/tmp2461057470/revision",
      section: "paths",
    },
    {
      id: "request-property-pattern-added",
      text: "added the pattern '^(?=.*[a-z])(?=.*[A-Z])(?=.*\\d)(?=.*[@$!%*?&])[A-Za-z\\d@$!%*?&]' to the request property 'password'",
      comment:
        "This is a warning because it is difficult to automatically analyze if the new pattern is a superset of the previous pattern (e.g. changed from '[0-9]+' to '[0-9]*')",
      level: 2,
      operation: "POST",
      path: "/users",
      source: "/tmp/tmp2461057470/revision",
      section: "paths",
    },
  ],
};
