packages:
  - "packages/*"
  - "internal/*"
  - "apps/*"
  - "tools/*"

minimumReleaseAge: 2880

allowBuilds:
  "@biomejs/biome": true
  "@sentry/cli": true
  cpu-features: true
  esbuild: true
  sharp: true
  ssh2: true

catalog:
  zod: 4.3.5
  mysql2: 3.10.3
  tailwindcss: 4.2.1
  clsx: 2.1.1
  "@clickhouse/client-web": 1.11.1

overrides:
  "zod": "4.3.5"
  "@tanstack/router-generator>zod": "3.24.4"
  "@tanstack/start-plugin-core>zod": "3.24.4"
  "@tanstack/router-plugin>zod": "3.24.4"
  "@tanstack/react-router>zod": "3.24.4"
  "@tanstack/react-start-plugin>zod": "3.24.4"
  "@tanstack/react-start-config>zod": "3.24.4"
  "@types/react": "19.2.4"
  "@types/react-dom": "19.2.3"
